- examples/README.md
- examples/rocket/hello-world/Cargo.lock
- examples/rocket/hello-world/Cargo.toml
- examples/rocket/postgres/Cargo.lock
- examples/rocket/postgres/Cargo.toml
- examples/rocket/postgres/src/lib.rs
- service/Cargo.toml
- service/src/factory.rs
- service/src/lib.rs
Since it does not appear to be the cause of our `segmentation fauit`
> feat: restore get_postgres_connection_pool

- .github/workflows/www.yml
- api/src/auth.rs
- api/src/auth_admin.rs
- api/src/main.rs
- docker-compose.yml
- www/lib/shuttle-api.ts
- return api keys for existing users
- add auth using `SHUTTLE_ADMIN_SECRET` env var
> update users api

- api/src/deployment.rs
- common/src/project.rs
https://app.clickup.com/t/21pccn4
> refactor: job queue based around multi-producer single-consumer channel

- service/src/lib.rs
Improve docs around feature flags
> docs: feature flags

- .github/workflows/ci.yaml
Switching the CI over to our public registry
> ci: public registry

- Dockerfile.dev
Just trying to speedup local test runs by using Docker layers. Also fixes an intermittent crash in tests due to some cargo.lock thing related to `rust-src`
> chore: testing issues

- terraform/backend.tf
- terraform/modules/shuttle/README.md
- terraform/modules/shuttle/certs.tf
- terraform/modules/shuttle/output.tf
- terraform/modules/shuttle/variables.tf
Some misc TF errors found during the latest prod apply
> refactor: TF updates

- .github/workflows/ci.yaml
- terraform/modules/shuttle/locals.tf
Use our easy to remember ECR repository alias
> refactor: use ecr alias

- Cargo.lock
- README.md
- api/Cargo.toml
- cargo-shuttle/Cargo.toml
- codegen/Cargo.toml
- examples/axum/hello-world/Cargo.toml
- examples/axum/websocket/Cargo.toml
- examples/axum/websocket/index.html
- examples/rocket/authentication/Cargo.toml
- examples/rocket/hello-world/Cargo.toml
- examples/rocket/postgres/Cargo.toml
- examples/tide/hello-world/Cargo.toml
- examples/tower/hello-world/Cargo.toml
- examples/url-shortener/Cargo.toml
- service/Cargo.toml
- service/src/lib.rs
- terraform/modules/shuttle/misc/cloud-config.yaml
- terraform/modules/shuttle/service.tf
I missed a bump on `codegen` :man_facepalming: 
[skip-ci]
> chore: v0.3.3

- Cargo.lock
- deployer/Cargo.toml
- deployer/src/deployment/deploy_layer.rs
- deployer/src/deployment/queue.rs
- deployer/src/error.rs
- deployer/src/handlers.rs
- deployer/tests/resources/tests-fail/Cargo.toml
- deployer/tests/resources/tests-fail/Shuttle.toml
- deployer/tests/resources/tests-fail/src/lib.rs
- deployer/tests/resources/tests-pass/Cargo.toml
- deployer/tests/resources/tests-pass/Shuttle.toml
- deployer/tests/resources/tests-pass/src/lib.rs
Run user-defined unit tests on deployer server after building and moving moving to the loading/executing stage.
> feat: run a service's unit tests on server side before loading and executing

- Cargo.lock
- api/src/main.rs
- cargo-shuttle/src/client.rs
Addresses some new clippy issues
> chore: clippy issues

- README.md
As suggested. It's time for a small update :)
> Update `README` with `cargo shuttle init`

- README.md
- e2e/README.md
Tiny housekeeping fix I ran into
> Fixes e2e Readme link

- .circleci/config.yml
- CONTRIBUTING.md
- Cargo.lock
- Makefile
- deployer/Cargo.toml
- docker-compose.dev.yml
- docker-compose.yml
This creates a shared cargo registry cache to be shared by deployers
> feat: deployer registry cache

- Cargo.lock
- cargo-shuttle/Cargo.toml
- cargo-shuttle/src/client.rs
- cargo-shuttle/src/config.rs
- cargo-shuttle/src/factory.rs
- cargo-shuttle/src/lib.rs
- cargo-shuttle/src/main.rs
> refactor: erroring on raw response (deployer)

- Cargo.lock
- cargo-shuttle/README.md
- service/src/lib.rs
The subcommand sections for `auth`, `status` and `logs` can use some improvements :) 
All feedback is welcome so we can make this a great README for the amazing `cargo-shuttle`.
Closes #71.
> `cargo-shuttle` README

- www/_blog/2022-07-28-patterns-with-rust-types.mdx
@christoshadjiaslanis minor grammar fixes
> minor grammar fixes

- www/_blog/2022-08-04-middleware.mdx
Nice post! :smile: Here's a few corrections for some typos I found as I was reading it.
> fix(blog): typos

- proto/src/lib.rs
- scripts/publish.sh
- scripts/release.sh
- shell.nix
Chore of development environment updates after a release
> chore: env update

- Cargo.lock
- deployer/Cargo.toml
- deployer/src/deployment/queue.rs
- deployer/src/deployment/run.rs
- deployer/src/handlers.rs
- deployer/src/main.rs
- service/src/loader.rs
- shell.nix
Waits on #235 
Fixes ENG-63, ENG-42
> feat: deployer telemetery

- .circleci/config.yml
- Cargo.lock
- Containerfile
- api/Cargo.toml
- api/src/lib.rs
- cargo-shuttle/Cargo.toml
- codegen/Cargo.toml
- common/Cargo.toml
- examples/poem/postgres/Cargo.toml
- examples/rocket/authentication/Cargo.toml
- examples/rocket/hello-world/Cargo.toml
- examples/rocket/postgres/Cargo.toml
- examples/rocket/url-shortener/Cargo.toml
- examples/tide/postgres/Cargo.toml
- proto/Cargo.toml
- proto/src/lib.rs
- provisioner/Cargo.toml
- provisioner/src/lib.rs
- scripts/upgrade-deps.sh
- service/Cargo.toml
- service/src/lib.rs
- service/src/secrets.rs
- service/tests/integration/loader.rs
- service/tests/resources/is-cdylib/Cargo.toml
- service/tests/resources/not-cdylib/Cargo.toml
- service/tests/resources/sqlx-pool/Cargo.toml
- shell.nix
Upgrades a bunch of dependencies. Also closes #297
> chore: dependencies upgrades

- Cargo.lock
- cargo-shuttle/Cargo.toml
- deployer/Cargo.toml
- deployer/src/args.rs
- deployer/src/deployment/deploy_layer.rs
- deployer/src/deployment/queue.rs
- deployer/src/deployment/run.rs
- deployer/src/deployment/runtime_logger.rs
- deployer/src/handlers/error.rs
- deployer/src/handlers/mod.rs
- deployer/src/lib.rs
- deployer/src/main.rs
- deployer/src/persistence/deployment.rs
- deployer/src/persistence/mod.rs
- deployer/src/proxy.rs
- service/Cargo.toml
Adds proxy support to deployer to close ENG-144
> feat: deployer proxy

- Cargo.lock
- gateway/Cargo.toml
- gateway/src/args.rs
- gateway/src/main.rs
- gateway/src/service.rs
Allows priming the gateway with an init subcommand
> feat: gateway init

- common/src/project.rs
- deployer/src/handlers/mod.rs
- gateway/src/api/latest.rs
- gateway/src/auth.rs
- gateway/src/lib.rs
- gateway/src/main.rs
- gateway/src/project.rs
- gateway/src/service.rs
Also fixes the broken test on gateway (less one :disappointed: )
> feat: deleting a project on gateway frees it for good

- deployer/src/deployment/deploy_layer.rs
- deployer/src/deployment/mod.rs
- deployer/src/deployment/run.rs
- deployer/src/error.rs
- deployer/src/lib.rs
- deployer/src/persistence/mod.rs
- deployer/tests/deploy_layer/self-stop/Cargo.toml
- docker-compose.dev.yml
Shutdown a deployment if a never deployment has passed the `build` call
Closes ENG-173
> feat: G&D shutdown on build

- gateway/src/api/latest.rs
- gateway/src/lib.rs
- gateway/src/main.rs
- gateway/src/service.rs
- gateway/src/worker.rs
Paving the way for health checks
> refactor: remove mutex in gateway sender

- cargo-shuttle/Cargo.toml
- cargo-shuttle/src/lib.rs
- cargo-shuttle/tests/integration/run.rs
- codegen/src/main/mod.rs
- common/Cargo.toml
- common/src/log.rs
- deployer/src/deployment/deploy_layer.rs
- deployer/src/deployment/run.rs
- deployer/src/deployment/runtime_logger.rs
- examples/poem/postgres/src/lib.rs
- examples/rocket/postgres/src/lib.rs
- examples/rocket/secrets/Cargo.toml
- examples/rocket/secrets/src/lib.rs
- examples/serenity/hello-world/Cargo.toml
- examples/serenity/hello-world/src/lib.rs
- examples/serenity/postgres/Cargo.toml
- examples/serenity/postgres/src/lib.rs
- resources/persist/src/lib.rs
- service/Cargo.toml
- service/src/logger.rs
- service/tests/integration/loader.rs
> tests: fixes hanging tests

- Cargo.lock
- common/Cargo.toml
- common/src/models/error.rs
- deployer/src/handlers/error.rs
- gateway/Cargo.toml
- gateway/src/lib.rs
Includes HTTP status code in errors, and includes some more information for common errors.
> feat(cargo-shuttle): better client errors

- docker-compose.yml
- gateway/src/api/latest.rs
- gateway/src/main.rs
- gateway/src/project.rs
- gateway/src/proxy.rs
- gateway/src/worker.rs
- migrator/.gitignore
- migrator/Cargo.toml
- migrator/db_script.sh
- migrator/script.sh
- migrator/src/main.rs
- shell.nix
Some files and fixes needed for migration
> misc: migration

- cargo-shuttle/src/client.rs
- cargo-shuttle/src/lib.rs
- common/src/log.rs
- deployer/src/deployment/deploy_layer.rs
- deployer/src/deployment/provisioner_factory.rs
- deployer/src/deployment/queue.rs
- deployer/src/handlers/mod.rs
- deployer/src/persistence/log.rs
- deployer/src/persistence/mod.rs
- service/src/loader.rs
Have better log output on errors.
Closes ENG-187
Closes ENG-188
Closes ENG-189
> bug: error logs

- deployer/src/deployment/mod.rs
- deployer/src/deployment/provisioner_factory.rs
- deployer/src/deployment/run.rs
- deployer/src/lib.rs
- deployer/src/main.rs
- runtime/README.md
- runtime/src/legacy/mod.rs
- runtime/src/lib.rs
- runtime/src/main.rs
- runtime/src/provisioner_factory.rs
Move the provisioner factory from deployer to runtime.
> feat: move factory to runtime

- CONTRIBUTING.md
- e2e/tests/integration/helpers/mod.rs
Signed-off-by: Federico Guerinoni <guerinoni.federico@gmail.com>
> Doc: Fix command to prime database with docker-compose

- CONTRIBUTING.md
In the doc it mentions to go to subfolder of examples but it was not
there :).
Signed-off-by: Federico Guerinoni <guerinoni.federico@gmail.com>
> Doc: Improve contributing documentation

- Cargo.lock
- cargo-shuttle/src/init.rs
- service/Cargo.toml
- service/src/lib.rs
The actix integration was not compatible with shared state (PgPool does not implement copy), so I removed the Copy bound. Added example in https://github.com/shuttle-hq/examples/pull/8
> fix: actix integration with state

- cargo-shuttle/src/factory.rs
- common/src/deployment.rs
- common/src/project.rs
- deployer/src/deployment/deploy_layer.rs
- deployer/src/deployment/provisioner_factory.rs
- deployer/src/deployment/run.rs
- resources/aws-rds/README.md
- resources/aws-rds/src/lib.rs
- resources/shared-db/README.md
- resources/shared-db/src/lib.rs
- resources/static-folder/src/lib.rs
- service/src/lib.rs
- service/tests/integration/loader.rs
> feat: local uri

- Cargo.lock
- cargo-shuttle/Cargo.toml
- cargo-shuttle/src/args.rs
- cargo-shuttle/src/lib.rs
- provisioner/Cargo.toml
- provisioner/src/args.rs
> Upgraded to clap v4

- Containerfile
- Makefile
Same as we did for shuttle-next, build our images with release profile when `PROD=true`.
> feat: build prod images in release profile

- provisioner/src/lib.rs
Closes #557
However, this breaks some PG clients like PgAdmin. Other clients like beekeeper-studio still work though. For anyone that needs fuller PG support, there is still the RDS option that will work with all clients.
> refactor: hide some pg catalogs

- auth/src/api/handlers.rs
- auth/src/secrets.rs
- auth/tests/api/session.rs
- common/src/backends/auth.rs
Needed to update claims a bit so that it reads in the public key
> [auth] feat: public key endpoint

- CONTRIBUTING.md
Good morning,
I took a stab at a fix for the "docker-buildx" related issue shuttle-hq/shuttle-docs#29 in the open issues noted in the docs repo.
Just trying to get comfy with this process by helping with simple issues. :)
Thanks,
~Jeff Mitchell
> Fix for install docker buildx issue #29

- CONTRIBUTING.md
Expand a bit on some of the commands and restructure parts of the document.
> docs: clean up the contributing doc

- common/src/backends/auth.rs
- common/src/backends/future.rs
- common/src/backends/mod.rs
- common/src/backends/tracing.rs
I also pulled out the ResponseFuture type, it's very simple and we can reuse it.
> feat: unbox InjectPropagation and ExtractPropagation

- Cargo.lock
- Cargo.toml
- common/Cargo.toml
- deployer/Cargo.toml
We updated the layers in common, and we're going to re-deploy gateway with the updated deployer for the sqlite bug fix.
> chore: v0.11.1

- Cargo.lock
- Cargo.toml
- cargo-shuttle/Cargo.toml
- common/Cargo.toml
- gateway/Cargo.toml
> chore: v0.11.2

- cargo-shuttle/src/init.rs
First line in the generated `src/lib.rs` file for poise project was wrongly indented. Fixing the indentation in `indoc!` fixes it.
> Fix indentation for poise init example

- .circleci/config.yml
- admin/src/args.rs
- admin/src/client.rs
- admin/src/main.rs
- gateway/src/api/latest.rs
- gateway/src/project.rs
Merge main into prod for 0.12.0 release artifacts publishing.
> shuttle-next: publish shuttle artifcats

- common/src/resource.rs
- deployer/src/handlers/mod.rs
Prepares a resources endpoint for the upcoming console :speak_no_evil: 
NA
> feat: resources endpoint

- .circleci/config.yml
- Cargo.lock
Introduced previously in a PR and this doesn't need to live in the repo.
> Cargo.lock: remove patch unused occurrences

- gateway/src/main.rs
Make gateway start its worker before pushing work to it
Locally started up gateway to test the production error is not hit
> bug: blocked channel on gateway worker

- gateway/src/main.rs
- gateway/src/service.rs
> Fix gateway clippy

- runtime/src/alpha/mod.rs
We're hard-wired to a local environment for every new alpha shuttle runtime we start. When the `local_uri` is mentioned for a db resource and the project gets deployed on shuttle, then the deployment logic will get confused thinking it deploys on a local environment where it uses a `local_uri` for a db connection.
The issue was described here: https://discord.com/channels/803236282088161321/1094663126810624151.
The fix consists in inferring the environment based on the storage type.
WIP
> runtime: infer environment based on storage type

- README.md
Add algora shields to readme to increase bounty visibility.
> feat: add algora shields to readme

- .circleci/config.yml
- .circleci/qa-docker.sh
- .circleci/qa-wasm.sh
- .circleci/qa.sh
- cargo-shuttle/src/lib.rs
QA tests to ensure everything works on a mac machine before a release.
Yip, using the CI
> ci: add mac qa

- README.md
Add a note about https://github.com/shuttle-hq/shuttle/issues/821 to the readme.
> docs: add note about init bug to readme

- .circleci/config.yml
I accidentally removed the `strawberryperl` install when I removed protoc, added it back in this PR.
Ran the workflow.
> ci: fix windows binary build

- cargo-shuttle/src/args.rs
- cargo-shuttle/src/client.rs
- cargo-shuttle/src/lib.rs
- gateway/src/api/latest.rs
I noticed that this endpoint is not active, so I clarify that to the user.
> fix: Remove unused project list filtering

- proto/README.md
This documents how to regenerate the protofiles in shuttle-proto.
> docs: document how to generate protofiles

- CONTRIBUTING.md
- e2e/tests/integration/helpers/mod.rs
closes issue #849 
Tests ran locally
> fix: `make test`

- auth/Cargo.toml
- auth/src/api/handlers.rs
- auth/src/lib.rs
- auth/src/user.rs
This is a auto-generated revert PR that reverts shuttle-hq/shuttle#886. We should not merge this before ensuring we have updated all of our own keys that do not confirm to the new requirements in ApiKey.
> revert: revert #886

- Cargo.lock
- provisioner/Cargo.toml
- provisioner/src/error.rs
- provisioner/src/lib.rs
Updated AWS crates. Fixed resulting errors.
Closes #896.
Ran
```
cargo check
cargo fmt
cargo clippy
```
> chore: update aws crates

- Makefile
Add a missing line break escape.
N/A
> release(prod): fix the missing line break escape

- .circleci/config.yml
Sync main with production.
N/A
> release(prod): add protoc dependency and fix the crates order (#938)

- .circleci/config.yml
> production: sync production with main

- CONTRIBUTING.md
Add sections on PR and reviews to contributing.md.
> docs: add sections on PR and reviews

- runtime/src/alpha/mod.rs
> provide better error message

- deployer/src/deployment/queue.rs
- service/src/builder.rs
Closes #990, Closes #1034. Two birds with one stone, or as we say in Sweden: Two flies with one whack
Haven't double checked in a Windows env, but it should work, confirmed by https://discord.com/channels/803236282088161321/1120727478332313760/1121093833250328576
> fix: Target directory from config, Windows .exe suffix

- .circleci/config.yml
Also sort the list of resources to publish.
> ci: add turso to publish job

- .circleci/config.yml
Push otel traces to honeycomb too for both unstable and prod.
Deployed the changes to unstable and saw traces in honeycomb for staging (unstable) env.
> circleci: set HONEYCOMB env variable

- README.md
- cargo-shuttle/src/args.rs
- runtime/README.md
Just fixes a nitpick of mine. Accompanies https://github.com/shuttle-hq/shuttle-docs/pull/148.
Docs only change.
> chore: fix Actix Web typos

- gateway/migrations/0005_refactor_to_ulid_primary_key.sql
Copied the certificate for custom_domains for the last gateway migration.
Deployed successfully on unstable.
> Fix gateway migration in terms of custom_domains certs

- .circleci/config.yml
> ci: separate jobs for faster ci verdict

- Cargo.lock
- gateway/Cargo.toml
Bump gateway for new release
NA
> chore: gateway v0.23.1

- .circleci/config.yml
- common/src/models/project.rs
- deployer/build.rs
- gateway/build.rs
- gateway/src/api/latest.rs
- gateway/src/project.rs
- gateway/src/proxy.rs
- gateway/src/service.rs
- gateway/src/task.rs
This PR works with https://github.com/shuttle-hq/console-ui/pull/44
Appends project ID to the response payload so that its creation date can be deduced.
Yes, tested in combination with Console UI
> fix: project date

- .circleci/config.yml
- Cargo.toml
- Makefile
- common/src/wasm.rs
- gateway/src/proxy.rs
- runtime/src/alpha/mod.rs
- shell.nix
> chore: Rust 1.72.0

- .circleci/config.yml
See failed run: https://app.circleci.com/pipelines/github/shuttle-hq/shuttle/3997/workflows/2ed1af2d-64ba-4753-9ebf-e5499bb38e4f/jobs/84418
Tested deploying to staging in CI.
> ci: fix invalid resource-class for deploy job

- Cargo.lock
- cargo-shuttle/Cargo.toml
Bump cargo-shuttle to release the fix for windows install.
> chore: cargo-shuttle v0.25.1

- resources/persist/README.md
I created this PR to update the associated README.md within the persist crate with the new methods added today as part of the 0.25.1 release.
No tests are needed.
> chore: update readme with new persist methods

- Makefile
This remove the publish parts of the Makefile.
Close https://github.com/shuttle-hq/shuttle/issues/1160
By ensuring that the CI is green.
> feat: remove publish steps from the Makefile

- codegen/Cargo.toml
- services/shuttle-actix-web/Cargo.toml
- services/shuttle-axum/Cargo.toml
- services/shuttle-poem/Cargo.toml
- services/shuttle-poise/Cargo.toml
- services/shuttle-rocket/Cargo.toml
- services/shuttle-salvo/Cargo.toml
- services/shuttle-serenity/Cargo.toml
- services/shuttle-thruster/Cargo.toml
- services/shuttle-tide/Cargo.toml
- services/shuttle-tower/Cargo.toml
- services/shuttle-warp/Cargo.toml
> chore(services): disable default features for shuttle-runtime

- proto/src/lib.rs
> refactor(proto): fix the use of deprecated chrono datetime

- cargo-shuttle/src/lib.rs
Makes the logs look the same
Local runner
> refactor: match local logs with deployer logs

- Makefile
- docker-compose.yml
Switch to the connection uri to allow staging to connect to RDS
By deploying to staging
> refactor: switch to LOGGER_POSTGRES_URI

- logger/src/lib.rs
Only sends logs for requested deployment id, and end closed streams.
Na
> refactor: improve stream logs

- logger/migrations/0001_index.sql
Add an index to reduce the time to fetch logs
On staging
> refactor: add index to deployment id

- cargo-shuttle/Cargo.toml
- cargo-shuttle/src/lib.rs
- codegen/src/shuttle_main/mod.rs
- common-tests/Cargo.toml
- common-tests/src/logger.rs
- common/Cargo.toml
- common/src/backends/tracing.rs
- common/src/lib.rs
- common/src/tracing.rs
- deployer/src/deployment/mod.rs
- deployer/src/deployment/run.rs
- deployer/src/deployment/state_change_layer.rs
- deployer/src/handlers/mod.rs
- deployer/src/persistence/error.rs
- deployer/src/persistence/mod.rs
- deployer/src/persistence/state.rs
- logger/Cargo.toml
- logger/src/dal.rs
- logger/src/lib.rs
- proto/runtime.proto
- proto/src/generated/runtime.rs
- runtime/src/alpha/mod.rs
- runtime/tests/integration/helpers.rs
- runtime/tests/integration/loader.rs
- runtime/tests/resources/axum-wasm-expanded/src/lib.rs
- service/Cargo.toml
Address reviews in https://github.com/shuttle-hq/shuttle/pull/1225
CI, local environment setup and a service deploy.
> fix: logger branch cleanups

- .circleci/config.yml
We need to set the logger postgres uri when deploying our images.
Tested by deploying to staging in CI.
> ci: logger postgres uri

- cargo-shuttle/src/client.rs
- cargo-shuttle/src/lib.rs
Improve error message caused by incompatibility between 0.25 & 0.26
EDIT: yes, I did test it. 🥺
> feat: outdated log parse warning

- Containerfile
- Makefile
- deployer/src/args.rs
- deployer/src/main.rs
- docker-compose.yml
- gateway/src/args.rs
- gateway/src/lib.rs
- gateway/src/project.rs
- gateway/src/service.rs
This sets up the makefile/containerfile config and args needed for connecting the deployer to the builder service.
Tested with full local environment.
> feat(deployer): connect deployer to builder service

- Containerfile
- builder/src/lib.rs
Is there anything else to do here? Most of the things were already done.
> feat(builder): update tracing logs

- resources/metadata/src/lib.rs
Missed this detail in #1050
Example works
> fix: metadata re-export

- cargo-shuttle/src/provisioner_server.rs
- provisioner/tests/helpers.rs
- provisioner/tests/provisioner.rs
Bumps the local version of pgsql to match our deployed versions 
Addresses: #1072
> chore: bump local pgsql from 11 to 14

- .circleci/config.yml
- Containerfile
- DEVELOPING.md
- Makefile
- auth/src/main.rs
- builder/prepare.sh
- builder/src/lib.rs
- builder/src/main.rs
- cargo-shuttle/src/lib.rs
- common-tests/src/builder.rs
- common-tests/src/lib.rs
- common/src/backends/tracing.rs
- deployer/src/deployment/mod.rs
- deployer/src/deployment/queue.rs
- deployer/src/deployment/state_change_layer.rs
- deployer/src/lib.rs
- deployer/src/main.rs
- gateway/src/main.rs
- logger/src/main.rs
- provisioner/src/main.rs
- resource-recorder/src/main.rs
- service/src/builder.rs
Send the deployment archive to the builder.
On staging and locally.
> feat(deployer): send deployment archive to the builder

- .circleci/config.yml
It better work next release :angry:
> ci: fix cargo-shuttle publish ordering

- .circleci/config.yml
"it better work next time" :joy: :clown_face:
> ci: fix release ordering

- common/src/claims.rs
> fix: scope enum serialization compatibility

- Cargo.lock
- Cargo.toml
- auth/Cargo.toml
- builder/Cargo.toml
- common/Cargo.toml
- deployer/Cargo.toml
- gateway/Cargo.toml
- logger/Cargo.toml
- provisioner/Cargo.toml
- resource-recorder/Cargo.toml
> chore: v0.30.1

- gateway/src/api/latest.rs
Fixes bug were renewal of custom domains does not persist.
Na
> bug: push renewed domain certificate to DB

- DEVELOPING.md
We could consider making this a feature in c-s if needed :thinking: 
Works on my machine :blush:
> docs: add Docker Desktop config tip

- Cargo.lock
Update our lock file to make CI green again
CI will
> misc: cargo update to fix audit issue

- cargo-shuttle/src/args.rs
- cargo-shuttle/src/lib.rs
- cargo-shuttle/src/suggestions/api_key.rs
- cargo-shuttle/src/suggestions/deploy.rs
- cargo-shuttle/src/suggestions/deployment.rs
- cargo-shuttle/src/suggestions/logs.rs
- cargo-shuttle/src/suggestions/project.rs
- cargo-shuttle/src/suggestions/resources.rs
- common/src/backends/auth.rs
- common/src/deployment.rs
- common/src/log.rs
- deployer/src/runtime_manager.rs
- gateway/src/api/latest.rs
- gateway/src/project.rs
- resource-recorder/src/dal.rs
- resources/persist/src/lib.rs
- service/src/lib.rs
Fix typos found while reading the codebase.
> fix typos found in codebase

- .circleci/config.yml
> ci: audit on main, build release stack sooner, release crates faster

- install.sh
Adds a function to install script for installing the Alpine Linux package.
See: #1365
> feat(installer): support installing the Alpine Linux package

- cargo-shuttle/README.md
- cargo-shuttle/src/args.rs
> feat(cargo-shuttle): make command-line aliases visible

- Cargo.lock
- Cargo.toml
- common/Cargo.toml
- common/src/backends/tracing.rs
axum bump context: https://discord.com/channels/803236282088161321/1174067454507503698/1174070481238884412
otel bump cause it's fun
stack built locally
> misc: bump axum minimum version, bump otel crates

- README.md
Updated Twitter's Old Name to New Name in README.md Community and Support Section
Closes https://github.com/shuttle-hq/shuttle/issues/1400
> docs(readme): update the alt text for Twitter page

- Cargo.lock
- common/Cargo.toml
> chore: cargo update

- services/shuttle-rocket/Cargo.toml
Updated Rocket dependency in shuttle-rocket to version 0.5.0 stable.
Ran unit tests from shuttle-rocket create, both passed. Also tested against all the shuttle-rocket examples, all the examples compiled and ran successfully.
> improvement: rocket-0.5.0 stable

- Makefile
- shell.nix
Upgrades version in our stack and new deployers.
MSRV remains 1.70.
Stack builds locally and no errors in sight
> chore: Rust 1.74

- cargo-shuttle/src/lib.rs
Ran local run with a normal axum app, and the timeout worked.
> feat(cargo-shuttle): better handling of runtime version checks

- cargo-shuttle/src/lib.rs
Apply same logic as logs command does.
-
> fix(cargo-shuttle): handle log stream errors in deploy command

- deployer/src/deployment/run.rs
Swap the order of the hashmap merge.
Not tested
> fix(deployer): new secrets override old ones

- services/shuttle-axum/Cargo.toml
- services/shuttle-axum/src/lib.rs
Closes #1438 
Tested in the same way as #1439
CI fails due to features being mutually exclusive. Can be fixed later.
> feat(shuttle-axum): support axum 0.7 through feature flag

- deployer/src/deployment/queue.rs
Improves the queueing messages for CCH
Na
> refactor: improve build queue messages and increase queueing time

- gateway/src/project.rs
- gateway/src/task.rs
Connect the ambulance tasks correctly to be able to understand why it takes long
Local runs
> feat: propagate ambulance traces

- gateway/src/project.rs
- gateway/src/task.rs
Attempt to retry three times on error, with exponential backoff, starting from 100 milliseconds.
Not tested yet.
> Add back retry logic on project error

- .circleci/config.yml
- proto/src/generated/builder.rs
- proto/src/generated/logger.rs
- proto/src/generated/provisioner.rs
- proto/src/generated/resource_recorder.rs
- proto/src/generated/runtime.rs
The update just bumps generation to tonic 0.10, nothing else.
bumped generated files, checking CI
> chore: upgrade proto-gen to 0.2.0

- .circleci/config.yml
- Makefile
- shell.nix
> chore: Rust 1.75

- .circleci/config.yml
Allows more granular re-runs of the release flow if parts of it is failing.
Test in production :partying_face:
> ci: split release flow

- Cargo.lock
Resolves https://github.com/advisories/GHSA-8r5v-vm4m-4g25.
> chore: upgrade h2 to resolve cargo audit

- resources/qdrant/Cargo.toml
- resources/qdrant/src/lib.rs
> fix: qdrant docker image name

- resources/qdrant/Cargo.toml
> fix(shuttle-qdrant): v0.38.0

- gateway/src/project.rs
We have a lot of errors like the below in the gateway, due to the `start_last_deploy` call trying to deserialize the response from deployer as a `service::Summary` no matter what the status is, but the deployer only returns a `service::Summary` for 200s.
```
{"level":"ERROR","target":"shuttle_gateway::project","exception.message":"EOF while parsing a value at line 1 column 0","exception.stacktrace":"[]","error":"EOF while parsing a value at line 1 column 0","error.chain":"[]","code.filepath":"gateway/src/project.rs","code.namespace":"shuttle_gateway::project","code.lineno":"1441"}}]
```
This PR resolves that. We might want to refactor the error handling here further, but this will resolve at lot of inaccurate errors.
Tested with local env Datadog, and this change removes the …
> fix: don't try to deserialize non-200 res to service summary

- logger/src/dal.rs
Temporary solution until something proper is built
Worked like a charm on my local logger
> feat(logger): clean old logs on startup

- Cargo.lock
Resolves https://github.com/advisories/GHSA-22q8-ghmq-63vf
CI
> chore: bump git2 to resolve vulnerability

- cargo-shuttle/README.md
- cargo-shuttle/src/args.rs
Adding loco as a framework selection
> add loco to shuttle cli

- gateway/src/api/latest.rs
- don't restart project on custom domain add
- fix returned url
not tested
> fix(gateway): custom domain followup improvements

- Cargo.lock
- Cargo.toml
- cargo-shuttle/Cargo.toml
- cargo-shuttle/README.md
- cargo-shuttle/src/args.rs
- cargo-shuttle/src/lib.rs
- common-tests/Cargo.toml
- common/Cargo.toml
- common/src/backends/otlp_tracing_bridge.rs
- common/src/backends/trace.rs
- common/src/extract_propagation.rs
- common/src/lib.rs
- deployer/Cargo.toml
- deployer/prepare.sh
- gateway/Cargo.toml
- logger/Cargo.toml
- logger/src/main.rs
- proto/Cargo.toml
- proto/src/lib.rs
- provisioner/Cargo.toml
- provisioner/src/main.rs
- resource-recorder/Cargo.toml
- resource-recorder/src/main.rs
- runtime/Cargo.toml
- runtime/src/alpha/mod.rs
- runtime/src/bin/shuttle-next.rs
- service/Cargo.toml
- bump trunk
- move c-s readme docs to docs site
- reduce runtime dependency weight by refactoring proto and cargo features (axum hello world compile steps: 291 -> 222)
- fix bug where --wd would create directories
> fix: various fixes

- docker-compose.yml
> fix: remove builder from compose

- provisioner/src/lib.rs
Increase password lengths to 32
Na
> misc: make passwords longer

- common/src/lib.rs
- common/src/templates.rs
used by https://github.com/shuttle-hq/shuttle-examples/pull/148
> feat(common): add template definition schema

- .circleci/config.yml
- Makefile
Can test the buildx bump on next unstable build
> ci: remove buildx cache, bump versions

- auth/src/lib.rs
- auth/src/user.rs
- auth/tests/api/helpers.rs
Fixes CI for auth after #1663 
Tests pass
> fix(auth): user query columns

- Cargo.toml
- proto/Cargo.toml
- resources/aws-rds/Cargo.toml
- resources/opendal/Cargo.toml
- resources/persist/Cargo.toml
- resources/qdrant/Cargo.toml
- resources/shared-db/Cargo.toml
- resources/turso/Cargo.toml
- runtime/Cargo.toml
- services/shuttle-actix-web/Cargo.toml
- services/shuttle-axum/Cargo.toml
- services/shuttle-poem/Cargo.toml
- services/shuttle-rocket/Cargo.toml
- services/shuttle-salvo/Cargo.toml
- services/shuttle-serenity/Cargo.toml
- services/shuttle-thruster/Cargo.toml
- services/shuttle-tide/Cargo.toml
- services/shuttle-tower/Cargo.toml
- services/shuttle-warp/Cargo.toml
> chore: set package.repository for all crates

- common/Cargo.toml
- common/src/claims.rs
- gateway/src/api/latest.rs
- gateway/src/api/project_caller.rs
- gateway/src/auth.rs
The `User` struct did nothing so got rid of it
NA
> refactor: simplify by getting rid of the unneeded User wrapper

- services/shuttle-poem/Cargo.toml
> feat: bump poem version

- .gitignore
- Cargo.lock
- admin/Cargo.toml
- admin/src/main.rs
- backends/Cargo.toml
- backends/src/project_name.rs
- cargo-shuttle/src/args.rs
- cargo-shuttle/src/provisioner_server.rs
- common/src/templates.rs
- deployer/src/deployment/queue.rs
accumulated during the past week
> fix: various fixes and corrections

- runtime/src/lib.rs
Missing re-export after #1673 
https://discord.com/channels/803236282088161321/1076126506323030017/1228082161630842932
> fix(runtime): re-export Environment

- Cargo.lock
- cargo-shuttle/src/client.rs
- cargo-shuttle/src/lib.rs
- common/src/deployment.rs
- common/src/models/deployment.rs
- common/src/models/service.rs
Output for first time deploy:
```
Current deployment: 'depl_01HV9V3C1CVPMN88ENE67FJ121' - in progress (http://pdo1-ms6ln917sadw.app.iulian.staging.shuttle.rs)
```
For subsequent deploys:
```
Current deployment: 'depl_01HV9V5GMT8WCF5NQHJD03VS3R' - in progress
Running deployment: 'depl_01HV9QJS9JEH5RKMAE7J65MAC5' - running (http://pdo-lum30rp5jxe3.app.iulian.staging.shuttle.rs)
```
Locally.
> cargo-shuttle: update deploy cmd for beta platform 

- cargo-shuttle/src/client.rs
- cargo-shuttle/src/lib.rs
Enable the resource list command in the beta cli.
Tested against my ECS stack.
> feat(cargo-shuttle beta): enable resource list

- resources/turso/src/lib.rs
> fix: change TursoOutput to provide Database

- Cargo.lock
- Cargo.toml
- backends/src/trace.rs
- cargo-shuttle/src/client.rs
- cargo-shuttle/src/lib.rs
- common/src/models/deployment.rs
- docker-compose.dev.yml
> fix: otel-otlp features for http client

- cargo-shuttle/src/client.rs
- cargo-shuttle/src/lib.rs
List teams project on beta when doing a `project list`
On dev account
> feat: list team projects on beta

- cargo-shuttle/src/client.rs
- cargo-shuttle/src/lib.rs
- common/src/models/project.rs
Adds a list struct to store project list responses for beta
Na
> refactor: use list struct for project lists

- common/src/models/error.rs
Adds a few extra helpers to `ApiError`
Na
> refactor: ApiError helpers

- auth/migrations/0005_add_beta_access.sql
- auth/src/user.rs
- common/src/models/user.rs
We don't need to do anything else here, it's just to prepare the shared database.
> feat(auth): add has_access_to_beta column

- DEVELOPING.md
- auth/src/lib.rs
- auth/src/main.rs
- auth/tests/api/helpers.rs
- docker-compose.dev.yml
fixes small things discovered when helping a new user run the stack
> fix: local development

- resources/qdrant/Cargo.toml
- resources/qdrant/src/lib.rs
This updates qdrant docker image to 1.10.0 and the qdrant crate to 1.10.1.
> update to qdrant 1.10

- cargo-shuttle/src/args.rs
- cargo-shuttle/src/lib.rs
> feat(cargo-shuttle): deploy --output-archive <path>

- .circleci/config.yml
- resources/openai/Cargo.toml
- resources/openai/src/lib.rs
- scripts/patches.toml
> Added OpenAI resource

- cargo-shuttle/src/lib.rs
> fix(c-s): windows

- api-client/src/lib.rs
- common/src/certificate.rs
- common/src/models/resource.rs
> feat(common): beta certificate models update

- cargo-shuttle/src/lib.rs
The CLI error suggestions are mostly incorrect for the beta client, disable them for now, and we'll refactor them later.
> feat: disable CLI error suggestions for beta

- common/src/models/error.rs
> fix: remove blanket suggestion to open ticket

- admin/src/args.rs
- admin/src/client.rs
- admin/src/main.rs
> feat(admin): renew certs command

- Makefile
> chore: deployer rust 1.81

- gateway/src/acme.rs
> fix: reduce gateway cert renew sleep

- admin/src/args.rs
- admin/src/client.rs
- admin/src/main.rs
- common/src/models/project.rs
Move ComputeTier to common, add admin endpoint for updating compute tier.
Tested by deploying to dev, then upgrading and downgrading a project.
> feat: compute tier upgrade admin command

- api-client/src/lib.rs
- cargo-shuttle/src/args.rs
- cargo-shuttle/src/lib.rs
`shuttle deployment redeploy <id>`
> feat(cargo-shuttle): redeploy command

- common/src/models/error.rs
- gateway/src/service.rs
We announced that new project creation will be disabled on the 19th of December. This change will enforce that restriction.
Will test on staging.
> feat: deprecate new project creation

- common/src/models/project.rs
- common/types.ts
Add more compute tiers for new platform.
Testing on new platform dev.
> feat: add xl and xxl compute tiers

- cargo-shuttle/src/provisioner_server.rs
- common/src/database.rs
- common/src/resource.rs
- resources/aws-rds/src/lib.rs
- runtime/src/rt.rs
Make RDS resource types compatible with the new platform.
Tested on the new platform dev environment.
> feat: update rds resource type for new platform compatibility

- Cargo.lock
- Cargo.toml
- api-client/Cargo.toml
- api-client/src/middleware.rs
- cargo-shuttle/Cargo.toml
- cargo-shuttle/src/init.rs
- cargo-shuttle/src/lib.rs
- cargo-shuttle/src/provisioner_server.rs
- cargo-shuttle/src/util.rs
- codegen/Cargo.toml
- common/src/models/deployment.rs
- common/src/models/user.rs
- common/src/tables.rs
- runtime/Cargo.toml
- runtime/src/rt.rs
- Axum hello-world dependency tree: **-> 209**
- cargo-shuttle release build dependency tree: **-> 398**
> feat: upgrade axum,http,hyper,reqwest,tokio

- admin/src/client.rs
- admin/src/lib.rs
- api-client/src/lib.rs
- cargo-shuttle/src/args.rs
- cargo-shuttle/src/lib.rs
- cargo-shuttle/src/provisioner_server.rs
- common/src/lib.rs
- common/src/models/deployment.rs
- common/src/models/log.rs
- common/src/models/project.rs
- common/src/models/resource.rs
- common/src/tables.rs
- common/types.ts
- resources/aws-rds/src/lib.rs
- resources/qdrant/src/lib.rs
- resources/shared-db/src/postgres.rs
- runtime/src/plugins.rs
- runtime/src/rt.rs
- runtime/src/start.rs
Breaks all `*Beta` and `*_beta` crate APIs.
CI
> chore: rename all beta models

- cargo-shuttle/src/lib.rs
- runtime/src/rt.rs
- tested local run, with and without RUST_LOG=shuttle
- works in deployment: message is printed as WARN on task shutdown
> feat: runtime print message on exit signal, cli simulate ecs health check

- resources/aws-rds/Cargo.toml
> chore: bump diesel in aws-rds

- Cargo.lock
- Cargo.toml
- common/Cargo.toml
- common/src/models/certificate.rs
- common/src/models/deployment.rs
- common/src/models/project.rs
- common/src/models/user.rs
- common/src/secrets.rs
This is a re-opening of #1924 for internal API testing needs.
This is being used to create API tests for the backend API platform.
> feat(common): Add utoipa attribute macro types

- admin/src/args.rs
- admin/src/client.rs
- admin/src/lib.rs
To test when backend is deployed to dev.
> feat: admin command to change project owner

- admin/src/args.rs
- admin/src/client.rs
- admin/src/lib.rs
> feat: admin commands to upgrade proj to lb, update lb project replica count

- admin/src/args.rs
- admin/src/client.rs
- admin/src/lib.rs
> feat: admin command to update scaling config

- common/src/models/project.rs
Add schema pattern to help contract tests across the API generate appropriate data
Using contract tests on the API
> fix: Add utoipa schema for contract testing

- install.ps1
- install.sh
- Cooler logo
- Success/fail telemetry
- powershell better parity with bash script
test bash version with
```
curl -sSfL https://raw.githubusercontent.com/shuttle-hq/shuttle/refs/heads/installation-telemetry/install.sh | bash
```
and powershell with
```
iwr https://raw.githubusercontent.com/shuttle-hq/shuttle/refs/heads/installation-telemetry/install.ps1 | iex
```
> feat(installer): fixes, anonymous telemetry, parity, cooler logo

- scripts/env-dev2.sh
TODO?:
- Improve switching between envs
> chore: dev2 script

- cargo-shuttle/src/lib.rs
> fix(cargo-shuttle): exit with error when tracked deployment fails

- cargo-shuttle/src/args.rs
> feat: rama init template arg

- common/src/models/project.rs
- common/types.ts
> fix: rename usage response vcpu reserved field to reserved_hours

- install.ps1
- install.sh
Install shuttle in the same directories as cargo install respects https://doc.rust-lang.org/cargo/commands/cargo-install.html
Closes #2068
> fix(installer): respect $CARGO_HOME and $CARGO_INSTALL_ROOT
