shuttle-hq/shuttle

Dockerfile, Dockerfile.dev, docker/supervisord.conf, docker/wait-for-pg-then
This regression occurs because the job processor loop starts before postgres is ready, resulting in us not being able to acquire a connection in `db_state.ensure().await` in `deployment.rs`.
Ideally `supervisord` would have dependencies where you can start program a after program b, but alas this is an open PR: https://github.com/Supervisor/supervisor/pull/1449/files so we'll have to employ the hacky solution of sleeping the job processor thread for 20 seconds on startup.
This is not great as we will have 20 seconds of application downtime, however it is better than not having persistence at all. 
Future improvements can employ a 'retry' system in `ensure()`.
=> fix: persistence regression postgres not ready

examples/rocket/hello-world/Cargo.lock, examples/rocket/hello-world/Cargo.toml, service/src/lib.rs
I just realized we had a bunch of these. So cleaning them up before they end up in code we do not want...
=> chore: remove unneeded async_trait markers

api/src/deployment.rs
This should fix the issue around the routing table not working when the API restarts.
=> fix: routing table start

Cargo.lock, cargo-shuttle/Cargo.toml, cargo-shuttle/src/args.rs, cargo-shuttle/src/config.rs, cargo-shuttle/src/main.rs, cargo-shuttle/tests/integration/README.md, cargo-shuttle/tests/integration/main.rs, examples/README.md, examples/url-shortener/README.md, service/src/lib.rs
Hi all. I added a --name argument to `cargo shuttle status`, so that I could check whether my project was up without `cd`ing into my project dir. I also added a --working-directory arg, while I was at it.
for `--working-directory`, I did a quick:
```bash
for f in  /Users/alsuren/.cargo/bin/cargo* ; do 
echo $f
$f --help | grep dir
done
```
and the only thing that supports any kind of dir arg is:
```
/Users/alsuren/.cargo/bin/cargo-watch
-C, --workdir <workdir>        Change working directory before running command [default: crate root]
```
cargo subcommands tend to accept a --manifest-path flag, instead
```
--manifest-path <manifest-path>      Specify path to Cargo.toml
```
(I only implemented `--working-directory` flag because it felt like a pure refactor, and I like to front-load my PRs …
=> add support for --working-directory and --name parameters to `cargo shuttle status` and friends

cargo-shuttle/src/config.rs
When first trying `cargo shuttle deploy` I got the following output:
```
Error: No valid API key found, try logging in first.
Caused by:
Configuration file: `/Users/xavientois/Library/Application Support/shuttle/config.toml`
```
The error message was confusing to me, as I was not aware that I needed to login to shuttle or how I would do it. This PR aims to improve this message to be more helpful to beginners who are just starting out with Shuttle:
```
Error: No valid API key found, try logging in first with:
cargo shuttle login
Caused by:
Configuration file: `/Users/xavientois/Library/Application Support/shuttle/config.toml`
```
=> feat: improve API key error with command hint

cargo-shuttle/src/lib.rs
Small fix for helping to reduce any initial friction. On firing up a previous project I got the "unexpected end of input while parsing minor version number" due to an old "0.2" version on the shuttle-service. This merge request makes it clearer that the version error is related to the shuttle-service value in Cargo.toml.
Related to #213
=> Feat: improved cargo shuttle version error

service/src/lib.rs
While working through the main documentation examples on the `shuttle_service` crate docs, I reached the point where it gives an example of how to deploy a service that uses a postgres database and sqlx. When I updated my code based on the example, it gave the following error:
```
error[E0432]: unresolved import `sqlx`
--> src/lib.rs:6:5
|
6 | use sqlx::PgPool;
|     ^^^^ use of undeclared crate or module `sqlx`
``` 
While this error was easy enough to fix, it would be a nicer experience if following the example in the docs worked the first time.
This also fixes an incorrect use of "which" rather than "that"
=> docs: add dependency to make example runnable

Cargo.lock, cargo-shuttle/Cargo.toml, cargo-shuttle/src/args.rs, cargo-shuttle/src/main.rs
Part of https://github.com/shuttle-hq/shuttle/issues/248
Migrates the `cargo-shuttle` crate from `structopt` to `clap`.
=> deps(clap): migrate uses of structopt to clap in cargo-shuttle

.github/workflows/fmt.yml, .github/workflows/test.yml, api/users.toml, cargo-shuttle/src/args.rs, cargo-shuttle/src/init.rs, cargo-shuttle/tests/integration/init.rs, cargo-shuttle/tests/integration/run.rs, e2e/tests/integration/main.rs, e2e/tests/integration/poem.rs, examples/poem/hello-world/Cargo.toml, examples/poem/hello-world/Shuttle.toml, examples/poem/hello-world/src/lib.rs, examples/poem/postgres/Cargo.toml, examples/poem/postgres/Secrets.toml, examples/poem/postgres/Shuttle.toml, examples/poem/postgres/schema.sql, examples/poem/postgres/src/lib.rs, service/Cargo.toml, service/src/lib.rs
I added e2e integration tests for the new examples.
I added integration tests in `cargo-shuttle` for the new examples.
I added a `cargo shuttle init` unit test and updated the `cargo shuttle init` integration test.
I deployed with `cargo run --manifest-path ../../../Cargo.toml --bin cargo-shuttle -- deploy` and verified with `curl` that it worked correctly.
Fixes issue #269.
Partially fixes issue #263.
=> feat: poem-web integration

examples/rocket/url-shortener/README.md
Found out that the README of the url-shortener example had an outdated command, which I updated in this quick PR.
=> docs(examples): update url-shortener example README

common/src/project.rs, examples/rocket/url-shortener/README.md
As suggested in #262, naming a project subdomain should allow underscores within the name in the same way it allows hyphens.
In the issue it is stated that the intention is to harmonize with crate naming, but such naming is a still ongoing discussion whether `kebab-case` or `snake_case` should be recommended ([which can be seen here](https://github.com/rust-lang/api-guidelines/discussions/29)). Since one or the other is not standardized, I think shuttle should allow the underscore as well.
Underscores are treated in the same way as hyphens: they can only be within the name of the subdomain, not at the end nor at the start. 
Also, when looking at the code I swapped the implementation of a valid character with a `matches!` macro to use more idiomatic Rust.
=> feat: support underscore in project name

.github/workflows/test.yml, common/src/project.rs
Fixes the new profanity filter test that failed because it wasn't zealous enough. Alternatively words can be added to or removed from the `censor` crate's word lists easily with the addition/subtraction operators, e.g. `Zealous - "bad word"`. So if you think the `Zealous` list is too strict I can remove words.
I've also included the `shuttle-common` crate in the Github `test` workflow so these new tests run in CI.
=> fix: make profanity filter zealous, add tests to CI

CONTRIBUTING.md
A docs update to include the new makefile method of setting up the docke containers/images.
I've never used podman to know if that section needs to be removed or altered in any way.
=> docs: update to include new makefile info

cargo-shuttle/src/init.rs
fixes #313, which needed the prerelease version of `rocket`.
Thanks for the tip @chesedo, and for spotting the issue @Butch78 :smile:
=> fix: init rocket dependency version

Cargo.lock, cargo-shuttle/Cargo.toml, cargo-shuttle/src/lib.rs, cargo-shuttle/tests/integration/run.rs
This makes sure secrets are set for local runs. This does, however, assume the use of a shared PG DB and won't work for an RDS PG (see ENG-119)
This closes ENG-120
=> bug: secret local run

.circleci/config.yml
Also do not build images for `arm64` anymore.
=> ci: do not do make clean before make images on pushing

api/src/deployment.rs
This is a quick workaround for #197.
In a nutshell: secrets are implemented through a separate API endpoint that sets them directly in the DB backend that is attached to a deployment (this is actually pretty unsafe, this should be fixed). However, a DB is attached to a deployment's state only after a successful load and not at all if the factory phase of deployment fails. This leads to a situation where the DB is provisioned but that is not reflected in the deployment's state. And in that case, the secrets endpoints on the API silently fail.
Since a much better approach is on the way in `feat/deployer`, this simple fix will do for now. A client-side update is on the way as well.
=> fix: update meta DB state even on factory failure

service/src/error.rs, service/src/secrets.rs
Client-side for #332 which is a workaround for #197 while we wait for `feat/deployer` to release.
=> fix: helpful error when a secret is not found

CONTRIBUTING.md, deployer/Cargo.toml, deployer/src/deployment/provisioner_factory.rs, deployer/src/deployment/run.rs, deployer/src/main.rs, deployer/src/persistence/mod.rs
Changes references of `project` to `service` to bring the naming up to date with the new architecture in the `feat/deployer` branch.
=> refactor: change references of `project` to `service`

deployer/src/error.rs, deployer/src/handlers/deployment.rs, deployer/src/handlers/error.rs, deployer/src/handlers/mod.rs, deployer/src/handlers/service.rs, deployer/src/handlers/user.rs, deployer/src/persistence/mod.rs
Split up `deployer/src/error`, since the handlers use almost none of its variants.
=> feat(deployer): split up deployer error enum

README.md
- replaced old synth urls
- replaced the `rocket` example with the `axum` example
- added `serenity` & `tide` support
=> readme touchup

Makefile, service/Cargo.toml, service/src/lib.rs
The segmentation fault would happen as soon as we tried to use the Tokio runtime on the other side of the FFI with [this spawn](https://github.com/shuttle-hq/shuttle/blob/dbfb0eec7fc3d52c84db18e48e30d1ed2e029d69/codegen/src/main/mod.rs#L22). [From past experiences](https://github.com/shuttle-hq/shuttle/blob/dbfb0eec7fc3d52c84db18e48e30d1ed2e029d69/service/src/lib.rs#L377) we also know that causing the Tokio runtime to cross FFI boundaries causes issues. So this was likely to be the source of the problem again... but no order of the `Bootstrapper` fields could get rid of this segmentation fault :angry: .
Yet, clearly, the Tokio runtime was the issue again. This lead to checking if the Tokio version changed which led to the issue.
When API compiled `shuttle_service` it used tokio v1.21.1. …
=> bug: segmentation fault

service/src/lib.rs
Rocket is configured with [`Rocket::configure`](https://api.rocket.rs/master/rocket/struct.Rocket.html#method.configure) that completly overwrite the configurations.
This fix makes that only the required fields of the configuration being patched.
This fixes configuration for fairing like `rocket_dyn_templates` :
```rust
#[shuttle_service::main]
async fn rocket() -> shuttle_service::ShuttleRocket {
let figment = rocket::Config::figment().merge(("template_dir", "./dist/templates/"));
let rocket = rocket::custom(figment)
.attach(Template::fairing());
Ok(rocket)
}
```
=> fix(service): rocket config

cargo-shuttle/src/client.rs, cargo-shuttle/src/lib.rs, common/src/models/error.rs, common/src/models/mod.rs, deployer/src/handlers/error.rs, gateway/src/api/latest.rs, gateway/src/lib.rs
Return an error message that is more relevant to the user than "failed to parse response to json" on non-200 responses.
Note: this is a simple and quick solution. We may want to refactor the errors sent from deployer/gateway to hold more information about what happened, so we can also suggest a solution when returning the error to the user.
=> feat(cargo-shuttle): better error messages

cargo-shuttle/src/args.rs, cargo-shuttle/src/init.rs
Update `cargo shuttle init` generated code to match the new features in `0.6.0`.
=> feat(0.6.0): update cargo shuttle init generated code

cargo-shuttle/src/init.rs
=> feat: added field in Cargo.toml to avoid accidental publishing

cargo-shuttle/src/lib.rs, deployer/src/deployment/queue.rs, service/src/loader.rs, service/tests/integration/build_crate.rs
=> feat: build deploys in release mode

.circleci/config.yml, Cargo.lock, cargo-shuttle/src/args.rs, cargo-shuttle/src/init.rs, cargo-shuttle/tests/integration/init.rs, cargo-shuttle/tests/integration/run.rs, e2e/tests/integration/main.rs, e2e/tests/integration/thruster.rs, examples/thruster/hello-world/Cargo.toml, examples/thruster/hello-world/Shuttle.toml, examples/thruster/hello-world/src/lib.rs, examples/thruster/postgres/Cargo.toml, examples/thruster/postgres/Shuttle.toml, examples/thruster/postgres/schema.sql, examples/thruster/postgres/src/lib.rs, service/Cargo.toml, service/src/lib.rs
Adds the [thruster](https://github.com/thruster-rs/Thruster) framework as a launchable target for use with shuttle.rs. Also includes a hello-world and postgres example.
=> feat(service): Add thruster framework as service

examples/warp/hello-world/src/lib.rs, gateway/src/project.rs
Impose memory limits on deployer containers. The hard limit is set at 6GiB, but if low memory is detected on the host a 4GiB limit will be applied. If a container hits the limit it will be killed (signal: 9, SIGKILL).
=> feat(deployer): implement container memory limits

deployer/src/deployment/deploy_layer.rs, deployer/src/deployment/provisioner_factory.rs, deployer/src/deployment/run.rs, deployer/src/main.rs, provisioner/src/main.rs
This PR ensures the connection to provisioner stays alive, but also ensures the connection is shorter lived by only creating to connection when a deployment needs the factory
=> bug: `transport error` when trying to connect to provisioner

cargo-shuttle/src/client.rs, deployer/src/deployment/deploy_layer.rs, deployer/src/deployment/queue.rs, deployer/src/error.rs, deployer/src/handlers/error.rs, deployer/src/handlers/mod.rs, gateway/src/project.rs
I'm not currently sure why sending the stream across threads causes this
=> bug: big archives being cut off at 32 768 bytes

Cargo.lock, Cargo.toml, next/Cargo.toml, next/README.md, next/src/args.rs, next/src/error.rs, next/src/lib.rs, next/src/main.rs
This adds a new binary to the workspace: `shuttle-next` (name TBD). It takes a path to an .so file to load, loads and runs it.
```bash
RUST_LOG=trace cargo run --bin shuttle-next -- -f <path to .so file>
```
=> shuttle next wrapper POC

gateway/src/project.rs
We are doing this because the docker health checks eat up 25% of a single CPU core and we are spinning up many of these containers.
Open issue: https://github.com/moby/moby/issues/39102
Other reports: https://www.reddit.com/r/docker/comments/b68r53/healtchecks_add_high_cpu_load/
=> refactor: do our own health checks on deployer containers

cargo-shuttle/src/lib.rs, deployer/src/deployment/queue.rs, service/src/loader.rs, service/tests/integration/build_crate.rs
=> feat(deployer): add support for building wasm projects

Makefile
And do not run "images" target when targeting "up". 
On my end, this still triggers a build of the images initially, unless when `DOCKER_COMPOSE_FLAGS=--no-build` is set, which matches the [documented behavior](https://docs.docker.com/engine/reference/commandline/compose_up/#description). Contributing guidelines also make it clear you want to run `make images` first in order to sync up images with their most recent versions, and the CircleCI workflows that do `make up` and `make test` also run `make images` prior. So this should not require changing anything else.
=> misc: add more helpful flags to Makefile

gateway/README.md, gateway/src/api/latest.rs, gateway/src/args.rs, gateway/src/main.rs, gateway/src/project.rs
Add a "admin/revive" endpoint to the gateway API, and remove it from the gateway cli.
=> Feat: revive via gateway endpoint

common/src/models/error.rs, gateway/migrations/0002_custom_domains.sql, gateway/src/custom_domain.rs, gateway/src/lib.rs, gateway/src/service.rs
Adds the `custom_domain` table along with methods for creating, finding, and routing to a custom domain.
=> feat(gateway): add custom domains table and routing

gateway/src/api/latest.rs, gateway/src/custom_domain.rs, gateway/src/project.rs, gateway/src/proxy.rs, gateway/src/service.rs
Count recent start events before restarting a stopped container, to prevent it from looping restarts indefinitely.
I tested that it does indeed not attempt to start if it has started 3 times in the last 15 minutes.
=> WIP feat: count recent start events before restart

README.md
I noticed there were a few broken example Links in the Readme and took the liberty to fix them
=> Fixed Links in Readme

gateway/src/api/latest.rs, gateway/src/lib.rs
This is a quick fix to the issue of `cargo project rm` always returning `destroying`. Draft while I look into improving cli feedback.
=> feat: verify project exists before sending destroy task

cargo-shuttle/src/lib.rs, deployer/src/deployment/queue.rs, deployer/src/persistence/log.rs, service/src/loader.rs
Reduce freezes in deployer by spawning less. This reduces complete lockups by deployer and makes deployer responsive to API calls during build jobs
Closes ENG-274
=> bug: deployer freezes

Makefile, docker-compose.yml, gateway/Cargo.toml, gateway/src/project.rs, gateway/src/service.rs, gateway/src/task.rs
This
- Expands the default subnet to `/16`
- Has gateway re-create containers that have disappeared if they used to be ready, keeping the same image and fqdn as before
=> feat: restore removed containers

.circleci/config.yml, Containerfile, common/src/wasm.rs, deployer/src/deployment/queue.rs, deployer/src/handlers/mod.rs, deployer/src/main.rs, deployer/src/persistence/mod.rs, deployer/src/proxy.rs, examples/rocket/hello-world/Cargo.toml, gateway/src/api/latest.rs, proto/runtime.proto, runtime/Cargo.toml, runtime/Makefile, runtime/README.md, runtime/src/axum/mod.rs, runtime/src/legacy/mod.rs, runtime/src/main.rs, runtime/src/next/mod.rs
Add a stop method to `runtime.proto`. We can't currently stop services on the legacy runtime, since we can't actually drop the legacy runtime. I implemented a stop method for it before discovering it was not possible, I left it there but with a comment. I'm happy to replace it with a `todo!()` if that's more tidy for now. 
I implemented stop for wasm serenity and axum, which is tested (manually) and works. We may want to setup integration tests for these runtimes with some helpers for the grpc requests, but maybe in a separate PR?
I opted for `oneshot` channels that are set on each `start`, but on second thought it may have been a mistake. I suppose the runtime should be able to load -> start several services, keeping them all alive until their ID/name receives a stop request. Meaning …
=> Feat(shuttle-next): stop runtime services

.circleci/config.yml, CONTRIBUTING.md, Cargo.toml, Makefile, cargo-shuttle/src/factory.rs, cargo-shuttle/src/lib.rs, deployer/prepare.sh, deployer/src/deployment/deploy_layer.rs, deployer/src/deployment/mod.rs, deployer/src/deployment/provisioner_factory.rs, deployer/src/deployment/queue.rs, deployer/src/deployment/run.rs, deployer/src/deployment/storage_manager.rs, e2e/tests/integration/helpers/mod.rs, resources/static-folder/Cargo.toml, resources/static-folder/README.md, resources/static-folder/src/lib.rs, service/src/lib.rs, service/tests/integration/loader.rs
This resource will allow getting access to the `static` folder in a crate's root as follow
```rust
#[shuttle_service::main]
async fn main(#[shuttle_static_folder::StaticFolder] static_folder: PathBuf) -> ShuttleAxum {
let serve_dir = get_service(ServeDir::new(static_folder)).handle_error(handle_error);
let router = Router::new()
.fallback(serve_dir);
let sync_wrapper = SyncWrapper::new(router);
Ok(sync_wrapper)
}
```
This example is based on the [Axum static-file-server example](https://github.com/tokio-rs/axum/blob/main/examples/static-file-server/src/main.rs)
=> feat: static file support for a single folder

.circleci/config.yml, .gitmodules, Cargo.lock, Containerfile, admin/Cargo.toml, cargo-shuttle/Cargo.toml, cargo-shuttle/tests/integration/run.rs, codegen/Cargo.toml, common/Cargo.toml, common/src/backends/metrics.rs, deployer/Cargo.toml, deployer/src/handlers/mod.rs, deployer/src/handlers/project.rs, deployer/src/persistence/mod.rs, deployer/tests/resources/tests-fail/Cargo.toml, deployer/tests/resources/tests-pass/Cargo.toml, e2e/tests/integration/actix_web.rs, gateway/Cargo.toml, gateway/src/api/latest.rs, gateway/src/auth.rs, proto/Cargo.toml, provisioner/Cargo.toml, provisioner/src/lib.rs, resources/aws-rds/Cargo.toml, resources/shared-db/Cargo.toml, service/Cargo.toml, service/src/lib.rs, service/tests/resources/sleep-async/Cargo.toml, service/tests/resources/sqlx-pool/Cargo.toml
Bump the pinned rust version of containers to 1.64, and update dependencies. I wasn't able to bump `cargo` from 0.64 to 0.66, as it has some conflict over libgit2-sys with `cargo-edit`. I bumped everything else, most of it did not require code changes, except for configuring the timeout for the aws sdk in provisioner and general axum changes. These code changes are in separate commits.
I did not upgrade clap to 0.4 in provisioner, deployer and cargo-shuttle, this might be better to do in a separate PR.
This branch is set to use the updated examples from this branch: https://github.com/shuttle-hq/examples/pull/4, since quite a few of the frameworks will have incompatible version with the current ones in examples `main`. 
Another thing to note is that this PR upgrades our pinned tokio to …
=> feat: bump rust to 1.64, bump dependencies

.circleci/config.yml, Cargo.lock, Cargo.toml, admin/Cargo.toml, cargo-shuttle/Cargo.toml, codegen/Cargo.toml, common/Cargo.toml, deployer/Cargo.toml, gateway/Cargo.toml, proto/Cargo.toml, provisioner/Cargo.toml, service/Cargo.toml
This implements the new workspace inheritance feature from 1.64. For this PR I elected to just add some external crates to the workspace dependencies, since `cargo-chef` does not support local crate workspace deps yet. When it does, we can add more. I'm happy to add more external deps to this PR, but it should also be easy to do as part of other PRs as we see commonly used deps that aren't inherited.
=> feat: implement workspace inheritance

admin/src/args.rs, admin/src/client.rs, admin/src/main.rs, common/src/models/project.rs, gateway/src/api/latest.rs, gateway/src/lib.rs, gateway/src/service.rs
~~Waiting for some cleanups in #473~~
=> feat: find (soon to be) invalid project names

codegen/Cargo.toml, common/Cargo.toml, deployer/src/deployment/queue.rs, service/src/loader.rs
This limits the workers used by `cargo build` to 8 for deployments, reducing memory usage during deployments while still keeping build times low. 
It also set tests that are ran after building a project for deployment to build in the release profile, this means that this step doesn't have to recompile the crates in the debug profile for testing.
=> feat: build tests in release profile, limit build workers

cargo-shuttle/src/lib.rs
When using `init` to bootstrap a project, at the end a user is prompted to create their project container. The path to load the project from is the `ProjectArgs` working directory, which would be different from the the path to the directory the user created via `init` (unless working dir was default `.` and user selected default `.` for project dir). In most cases this would result in an error: "could not locate the root of a cargo project".
=> feat: create `init` project from correct dir

resources/static-folder/src/lib.rs
Prevents use of absolute paths or a path that walk up in the directory tree for static folders
=> bug: hacking static folders

cargo-shuttle/src/lib.rs
On windows attempting to deploy without `--allow-dirty` would lead to an error from the `Shuttle::is_dirty` function:
```
Error: stripping repository path from working directory
Caused by:
prefix not found
```
This was because it was trying to strip the repo path from the working dir, but only the working dir was canonicalized. Fixed by canonicalizing repo path.
=> fix: canonicalize repo path in `Shuttle::is_dirty`

deployer/src/deployment/queue.rs
This way, we don't need to resolve dependencies between deployments each time.
=> fix(deployer): keep Cargo.lock between deployments

Cargo.lock, runtime/Cargo.toml, runtime/src/axum/mod.rs, tmp/axum-wasm/Cargo.toml, tmp/axum-wasm/src/lib.rs
Bump the wasmtime dependencies and fix the shuttle-axum test.
For reference: https://github.com/bytecodealliance/wasmtime/blob/main/RELEASES.md
=> Feat: shuttle next bump deps

cargo-shuttle/README.md, cargo-shuttle/src/args.rs, cargo-shuttle/src/client.rs, cargo-shuttle/src/lib.rs
Remove the auth command from the cargo-shuttle CLI, as it's no longer used.
=> Refactor: remove deprecated auth command

CONTRIBUTING.md
+ add makefile command to convert .sh files to Unix format
+ add relevant documentation in CONTRIBUTING.md
Explanation:
As noted in the CONTRIBUTING.md file, the Makefile currently does not play nicely with Windows and you'll have to set up using WSL/Bash to get anything to work. This isn't necessarily a problem in of itself as you currently need WSL anyway to run Docker Desktop; however, Windows seems to pull files from Git repos in CRLF format rather than LF format which is inconvenient as it breaks `make images`. The added script is intended to simply install dos2unix and then convert the .sh files to Unix format so that `make images` can properly read the .sh files. Relevant documentation has also been added to CONTRIBUTING.MD to explain all of this.
=> ci: add Makefile command for Windows to convert .sh files to LF format

cargo-shuttle/src/args.rs, cargo-shuttle/src/client.rs, cargo-shuttle/src/lib.rs, common/src/models/project.rs, gateway/src/api/latest.rs, gateway/src/service.rs
This change creates a subcommand `cargo shuttle project list` that prints out all the projects that belong to the calling account in a tabular format.
resolves #547
=> feat: create subcommand to list all projects of calling account

deployer/src/lib.rs, deployer/src/persistence/mod.rs
Make deployer cleanup invalid states on startup
=> bug: deployer drifting state

Cargo.lock, codegen/src/next/mod.rs, runtime/Cargo.toml, runtime/src/axum/mod.rs, tmp/axum-wasm/Cargo.toml, tmp/axum-wasm/src/lib.rs
This uses `futures::iter` to create a stream from a `BufReader::bytes()`. I needed to open another filedescriptor for body, since `.bytes()` consumes the FD. 
This improves performance (in simple benchmarks) by about ~30%~20%.
I've also experimented with async wasmtime, which wasn't so hard to set up, but making the cap_std unixstreams async proved difficult. There may not be too much to gain here either, since from what I can gather WASM async still has a ways to go: https://docs.wasmtime.dev/api/wasmtime/struct.Config.html#method.async_support.
=> feat: return streaming body from wasm router

.circleci/config.yml
The `publish-github-release` workflow wasn't working since we can't use interpolated environment variables in circleci paths. To get around this and keep the git tag in the name, I move each binary archive to a subdirectory named after its target, and then flatten these sub-directories before running `ghr`.
Successful workflow run: https://app.circleci.com/pipelines/github/shuttle-hq/shuttle/1391/workflows/8ce94b4f-d14f-456f-bf10-b1fd15575082
=> ci: fix bin builds

.circleci/config.yml, Cargo.lock, cargo-shuttle/src/args.rs, cargo-shuttle/src/init.rs, service/Cargo.toml, service/src/lib.rs
fixes #552
[Example](https://github.com/Anafabula/shuttle-examples/tree/feat/poise-example/poise/hello-world)
`cargo shuttle run` works fine, ~~but so far I haven't been able to deploy _anything_ locally with errors like:~~
<strike>
```
ERROR {error="Build error: failed to get `axum` as a dependency of package `hello-world-fd684ca9-901c-44ff-882b-2b54a0972e6c v0.1.0 (/opt/shuttle/shuttle-builds/hello-world-axum-app)`"} shuttle_deployer::deployment::queue: service build encountered an error
```
</strike>
Deploying on a local instance of shuttle works too when using crates.io directly instead of panamax.
=> feat: Support Poise

common/src/models/project.rs, gateway/src/project.rs
After the VM upgrade a bunch of user containers are no longer connected to any network. This is potentially because they tried to start with the wrong network id (from the old VM). So this PR makes a change to connect to the user layer network when we start up deployers rather than when we create deployers. Moving the network attachment to start means containers that are restarted will also attach to the correct network correctly.
Lastly, the revive command is updated to detect and restart containers which are not on any networks.
=> bug: no networks

runtime/README.md, runtime/src/axum/mod.rs
This improves throughput by about 10%, but the issue of tasks spawning perpetually after a stress test remains.
=> feat: change log read to spawn blocking

Cargo.lock, codegen/src/shuttle_main/mod.rs, service/Cargo.toml, service/src/error.rs, service/src/lib.rs
This PR allows options passed to resources to be string interpolated. For example in this `local_uri` option, the password is being read from the `Secrets.toml` file
```rust
#[shuttle_service::main]
async fn main(
#[shuttle_shared_db::Postgres(
local_uri = "postgres://postgres:{secrets.password}@localhost:16695/postgres"
)]
pool: PgPool,
) -> shuttle_service::ShuttlePoem<impl poem::Endpoint> {
...
}
```
With #596, this closes #497
=> feat: allow string interpolation on resource options

cargo-shuttle/src/args.rs, cargo-shuttle/src/lib.rs
=> added feedback

.circleci/config.yml, Cargo.toml, cargo-shuttle/Cargo.toml, codegen/Cargo.toml, common/Cargo.toml, service/Cargo.toml
[`cargo-binstall`](https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md#support-for-cargo-binstall) needs the crate to have a repository set in its manifest for it to find the binary download. We should only need to set it for `cargo-shuttle`, but it's nice to have for all our published crates. 
There was also an issue with the windows bin build where the tag was not included in the archive name, due to that build running the `make-artifact` command with powershell. I resolved this by changing the shell for the windows build to bash, and using a powershell override for the other commands.
I also changed the name of the directory inside the archive to be [compatible](https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md#examples) with `cargo-binstall`.
And last but …
=> fix: add repo url to cargo-shuttle for binstall

cargo-shuttle/src/args.rs, cargo-shuttle/src/config.rs, cargo-shuttle/src/lib.rs
* add logout function for CLI
Reference: issue #594 
Current queries:
- api_key is currently defined as a String type, which means I've had to set the API key in the logout function as an empty string. This technically works, but I'm wondering if it's more correct to set it as None?
=> feat: add logout function

cargo-shuttle/src/args.rs
It is a common pattern for dev servers to let the `$PORT` environment variable dictate which port they will listen on. This change allows the port to be passed to `cargo shuttle run` via the `$PORT` environment variable in addition to the `--port` argument.
=> Respect $PORT environment variable

cargo-shuttle/src/lib.rs, common/src/models/project.rs, gateway/src/lib.rs, gateway/src/project.rs, gateway/src/service.rs, gateway/src/task.rs
This adds three new project states to improve the stability of project creation:
1. `Recreating` to recreate a container from scratch that failed to connect to the network
2. `Restarting` to try to start a container that failed to start
3. `Rebooting` to reboot container that became unhealthy
This causes the `Stopped` state to become a sink / dead end.
Things still to do:
=> feat: retry on bollard errors

cargo-shuttle/src/client.rs, cargo-shuttle/src/lib.rs, deployer/src/handlers/mod.rs
In the previous implementation stop service would just return a list of the deployments fetched before stopping the service, so it would show as running. This changes it to return a summary of the active deployment and a progress bar until it's stopped (which is almost immediate).
=> feat: show progress bar on stopping service

deployer/src/persistence/mod.rs, gateway/src/main.rs
Up until sqlx 0.6.1 sqlite databases were created in [WAL mode](https://www.sqlite.org/wal.html) by default, which should be more performant. Our gateway DB was created before 0.6.1 and WAL mode is a permanent setting, so it's still in WAL mode. Since we're now on 0.6.2 we need to explicitly set it to WAL mode so new DBs are created in it. 
On top of that, using the `NORMAL` [synchronous setting](https://www.sqlite.org/pragma.html#pragma_synchronous) is durable and corruption-proof in WAL mode, and it is more performant then the default `FULL` setting.
Sources: sqlite docs linked above, https://phiresky.github.io/blog/2020/sqlite-performance-tuning/ and https://activesphere.com/blog/2018/12/24/understanding-sqlite-busy
TODO: stress test this and see if it resolves the deadlock.
=> Feat: optimize sqlite db in deployer and gateway

Cargo.lock, Cargo.toml, auth/Cargo.toml, auth/src/api/builder.rs, auth/src/api/handlers.rs, auth/src/api/mod.rs, auth/src/lib.rs, auth/src/secrets.rs, auth/src/user.rs, auth/tests/api/helpers.rs, auth/tests/api/main.rs, auth/tests/api/session.rs, common/Cargo.toml, common/src/backends/auth.rs, gateway/Cargo.toml
The cookie conversion should be in a next PR, but this allows other PRs to start. ~~I'll put the tests and some cleanup in the next PR.~~
Also close ENG-434
=> feat: session manager

gateway/src/project.rs, gateway/src/service.rs
feat: restore previous custom domain (if any) when recreating a project (#634)
=> (#634) restore custom domain when recreating project

.circleci/config.yml
Remove the target from the binary name to be compatible with binstall, and also switch to using only the short-form git tag.
See first commit's workflow run for successful run, and see the new draft release in releases for a preview of the binaries.
=> Fix: remove target from bin build name

Makefile, extras/otel/otel-collector-config.yaml
We applied these changes after the release, they are live on production.
=> feat: bump panamax, remove docker stats receiver

common/src/backends/auth.rs, common/src/backends/future.rs, common/src/backends/mod.rs, common/src/backends/tracing.rs
Removes the `Box::pin` from the AdminSecret. Also allows more reuse of the future.
=> refactor: unboxing AdminSecret

.github/ISSUE_TEMPLATE/BUG-REPORT.yml, .github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md
This adds a bug report template that users can choose when opening an issue, that requires the user to include some information that is usually needed. To see how it looks rendered, click view file. Or see this link: https://github.com/shuttle-hq/shuttle/blob/f0a5066244b414cec93dabbacf2a4ab0c389dead/.github/ISSUE_TEMPLATE/BUG-REPORT.yml
The user will be able to choose the bug report template or a blank issue (when we add more templates we can disable blank templates), or they can choose to follow a link to our discord.
It also adds a PR template to encourage contributors to self-review and add docs/tests.
Closes #602
=> feat: add bug report and PR templates

Cargo.lock, service/Cargo.toml, service/src/lib.rs
Removes box self from services and syncwrapper from axum service since they are no longer needed.
This PR is based on https://github.com/shuttle-hq/shuttle/pull/675
=> feat: remove box self from services, remove syncwrapper from axum service

resources/aws-rds/Cargo.toml, resources/aws-rds/src/lib.rs, resources/persist/Cargo.toml, resources/persist/src/lib.rs, resources/shared-db/Cargo.toml, resources/shared-db/src/lib.rs, resources/static-folder/Cargo.toml, resources/static-folder/src/lib.rs, service/src/lib.rs, service/src/persist.rs
We no longer need to pass a runtime to the resourcebuilder, so we can remove it and tokio from all the resources.
This has been tested by making sure they all compile and that the tests pass for the resources that have tests.
=> Feature: remove tokio runtime from all resources

CONTRIBUTING.md
Depending on how users clone the repo the tags may not be fetched. Add a note about this and how to do it to contrib.
=> docs: add note about git tags in contrib

resources/static-folder/Cargo.toml, resources/static-folder/src/lib.rs
This fixes static folder projects not starting up correctly after they went into idle mode. This would happen because the static folder resource would move the folder and therefore could not move it a second time when an idle project is woken up.
This change causes the static folder resource to rather copy the folder.
Closes issue #689 
Locally, with a full running setup and the axum websocket example
=> bug: idle static folder

resources/static-folder/Cargo.toml
We are bumping static folder and publishing a release of that, as well as redeploying gateway and deployer so the gateway uses the new deployer, the new deployer is necessary since it uses patched local versions of the resource libraries.
=> chore: v0.11.3

Containerfile
Building the shuttle containers was failing during the `cargo chef cook` step because of a cyclic dependency introduced by an upstream crate. This did not happen when building outside of a container, because the versions pinned by `Cargo.lock` did not contain any cycles.
See https://github.com/tkaitchuck/aHash/issues/95
=> fix: Respect `Cargo.lock` when building containers

codegen/src/shuttle_main/mod.rs, codegen/tests/ui/main/duplicate-main-fn.rs, codegen/tests/ui/main/duplicate-main-fn.stderr
Emit a clear error when a shuttle_runtime::main function is named `main`, which does not work since the codegen generates a main function.
I added a test and I tested a modified example manually.
=> Feature: emit error when shuttle::main function is named main

cargo-shuttle/src/client.rs, cargo-shuttle/src/init.rs, cargo-shuttle/src/provisioner_server.rs, codegen/src/shuttle_main/mod.rs, common/src/models/project.rs, common/src/models/secret.rs, common/src/models/service.rs, common/src/project.rs
Please write a summary of your changes and why you made them. 
Be sure to reference any related issues by adding `closes issue #`.
=> fix: codegen clippy

deployer/src/deployment/run.rs, deployer/src/runtime_manager.rs
Update the runtime manager to run multiple deploys at the same time. This is to allow a new deploy to be loaded while an old deploy stays up running
By running deloyer locally
=> [next] refactor: update runtime manager

Cargo.lock, proto/Cargo.toml, proto/build.rs, runtime/tests/resources/axum-wasm-expanded/Cargo.toml
This embeds protoc in shuttle-proto, so it doesn't need to be installed by the user to install cargo-shuttle.
Seems to work on linux, about to test on windows.
=> feat: embed protoc in shuttle-proto

cargo-shuttle/src/lib.rs
This changes the local run to install the next-runtime from crates.io, not git.
Uninstalled `shuttle-next` runtime, then ran this locally which worked and installed  `shuttle-next` of the latest version.
=> refactor: don't install next-runtime from git in local runs

cargo-shuttle/src/lib.rs, cargo-shuttle/tests/integration/init.rs, cargo-shuttle/tests/integration/run.rs, codegen/src/shuttle_main/mod.rs, resources/static-folder/src/lib.rs, runtime/src/lib.rs
This fixes the bug where `cargo shuttle run` deletes the contents of files in the static assets folder. I also added tests to cargo shuttle for static folder and shuttle-next projects.
Additionally this PR exports `Factory` from `shuttle_runtime` and imports it in the codegen in the `extra_imports` variable, to fix a bug where the codegen was missing the `Factory` trait for static file projects.
Tested with local run, and added a test that runs `axum/static-files` locally.
=> fix: static folder local run clearing file contents, add missing tests in cargo-shuttle

cargo-shuttle/src/lib.rs, codegen/src/shuttle_main/mod.rs, runtime/src/alpha/mod.rs, runtime/src/bin/shuttle-next.rs
Makes sure all the tracings and trace propagations in next hook up correctly.
Currently the propagation link to provisioner is still missing. I suspect this is because run spawns a thread for services to run on and the propagation does not make it across this thread.
Using the full container setup locally and checking our datadog
=> [next] refactor: tracing

Cargo.lock, cargo-shuttle/Cargo.toml, cargo-shuttle/src/args.rs
Cargo has a long-lived problem with [windows paths](https://github.com/rust-lang/cargo/issues/9770), which has affected our users on windows when doing local runs. We have dealt with this by having users `cargo build` before `cargo shuttle run`. This PR uses [dunce](https://crates.io/crates/dunce) to not use UNC paths when canonicalizing paths on windows, while it uses `std::fs::canonicalize` on other platforms.
Local runs with and without this fix on windows, it worked every time.
=> fix: windows local run path bug

codegen/src/shuttle_main/mod.rs, common/src/claims.rs, deployer/prepare.sh, gateway/src/api/auth_layer.rs, runtime/src/alpha/mod.rs
This fixes logging being broken in serenity since a span would fail to drop when using a thread local subscriber.
Also fixes tokens expiring too soon since builds now seem to take longer than 5 minutes.
Logging has been tested locally. ~Still need to test the new expiry status code though~
=> [next] bug: misc fixes

admin/src/args.rs, admin/src/client.rs, admin/src/main.rs, gateway/src/api/latest.rs, gateway/src/project.rs
An extra admin command to destroy old projects which we need to force all users to upgrade
Using the local docker runs
=> feat: admin command to destroy projects

.circleci/config.yml, Cargo.lock, Cargo.toml, Makefile, auth/src/user.rs, cargo-shuttle/Cargo.toml, deployer/Cargo.toml, deployer/src/deployment/queue.rs, deployer/src/error.rs, gateway/src/api/latest.rs, service/Cargo.toml, shell.nix
This bumps our pinned rust version for deployer to 1.68, as well as bumping our `cargo` deps to v1.68. There were some changes to how cargo handles test errors in 1.66, I need to double check to make sure I have implemented these changes correctly on our end. For reference: https://github.com/rust-lang/cargo/pull/11028
Ran deploy tests locally and made images. 
TODO: test on unstable.
=> chore: bump rust and cargo to 1.68

Cargo.lock, Containerfile, Makefile, admin/README.md, admin/src/args.rs, admin/src/client.rs, admin/src/main.rs, auth/src/user.rs, common/src/claims.rs, gateway/Cargo.toml, gateway/src/acme.rs, gateway/src/api/latest.rs, gateway/src/lib.rs, gateway/src/main.rs, gateway/src/project.rs, gateway/src/service.rs, gateway/src/tls.rs
Closes #621 .
This PR adds functionality that enables the periodical renewal of  `LetsEncrypt` certificates. These certificates have a validity window of 90 days and is recommended to be renewed 30 days before expiration. The functionality will cover renewal for:
1) certificates emitted for a custom domain project when requested through the admin gateway API `"/admin/acme/request/:project_name/:fqdn"` or through `shuttle-admin` CLI.
2) the gateway certificate, which is loaded when starting the gateway service or created based on a set of ACME credentials present on the local filesystem.
1) End-to-end manual test of the certificate renewal with all shuttle components deployed locally. I have some issues with the shuttle local deployment that blocks me while testing. I need some more time …
=> Renew LetsEncrypt certificates

Cargo.lock, Cargo.toml, cargo-shuttle/src/lib.rs, codegen/src/shuttle_main/mod.rs, common/src/lib.rs, common/src/models/service.rs, common/src/resource.rs, deployer/migrations/0002_resource_config.sql, deployer/src/deployment/run.rs, deployer/src/persistence/mod.rs, deployer/src/persistence/resource/mod.rs, resources/secrets/Cargo.toml, resources/secrets/src/lib.rs, resources/shared-db/Cargo.toml, resources/shared-db/src/lib.rs, runtime/Cargo.toml, runtime/src/alpha/mod.rs, runtime/src/lib.rs, runtime/src/provisioner_factory.rs, runtime/src/resource_tracker.rs, service/Cargo.toml, service/src/lib.rs
This updates the codegen to correctly record all types of resources being created... including secrets and static folders.
Using the local runner.
=> feat: record resources in codegen

common/src/models/service.rs, common/src/resource.rs, deployer/src/persistence/resource/mod.rs, resources/aws-rds/Cargo.toml, resources/aws-rds/src/lib.rs, resources/persist/src/lib.rs, resources/shared-db/src/lib.rs, resources/shared-db/src/mongo.rs, resources/shared-db/src/postgres.rs, resources/static-folder/Cargo.toml, resources/static-folder/src/lib.rs
This updates the resources with the changes in https://github.com/shuttle-hq/shuttle/pull/746, which needs to be merged before this.
Local runs.
=> Feat: update resources with resourcebuilder changes

cargo-shuttle/src/args.rs, cargo-shuttle/src/client.rs, cargo-shuttle/src/lib.rs, common/src/lib.rs, common/src/models/deployment.rs, common/src/models/mod.rs, common/src/models/resource.rs, common/src/models/service.rs, deployer/src/handlers/mod.rs, resources/aws-rds/src/lib.rs, resources/shared-db/src/lib.rs, resources/shared-db/src/mongo.rs, resources/shared-db/src/postgres.rs, service/src/lib.rs
This switches the CLI to use the new resources API. It also trims some extra fluff from the other API endpoints.
By running deployer locally
=> refactor: switch to resource endpoint

deployer/src/persistence/resource/mod.rs
Fixes a bug where resources other than databases were not recognized due to missing match arms in the `FromStr` impl for `persistence::resource::Type`. Error message below:
```bash
Error: 500 Internal Server Error
message: Persistence failure: Database error: error occurred while decoding column "type": 'secrets' is an unknown resource type
```
Local deploy of the postgres poem example after adding `shuttle_secrets` to it, and also tested with all resources in https://github.com/shuttle-hq/shuttle/pull/750 with the fix from this branch.
=> fix: unknown resource type

cargo-shuttle/src/lib.rs, common/src/models/deployment.rs, common/src/models/resource.rs, common/src/models/secret.rs, common/src/models/service.rs
This polishes the resource tables by:
- Adding the service name in bold to the table description
- Making the table headers bold
- Making the static folder display only the name of the folder, not the full path
- Changing the small tables to not use full width (making them consistent with the secrets table).
- Updating the existing tables (deployment list, secrets) with the above changes to be consistent.
- Making the service name bold in `cargo shuttle status` output.
What I did not do in this PR was remove the `cargo shuttle secrets` command, since I don't want to make this last-minute PR too large. I suggest we do it for the next release.
Tested locally on this branch: https://github.com/shuttle-hq/shuttle/pull/749, with the `postgres` poem example, but with all resources (database, …
=> feat: polish CLI after 0.13 updates

gateway/src/main.rs, gateway/src/service.rs
When the gateway starts it should serve a default certificate which is fetched either from the filesystem or from the letsencrypt server.
N/A
=> gateway/certs: serve certificate as default

resources/static-folder/Cargo.toml, resources/static-folder/src/lib.rs
The static folder will fail to be provisioned on windows due to path canonicalization converting the input path to UNC. This PR fixes that by using the `dunce` crate, like we did in cargo-shuttle.
Tested local run of `examples/axum/static-files` with and without this fix on windows. Without this fix, it will fail to provision the static folder for local runs, but deployments work.
=> fix: windows path canonicalization bug in static folder

resources/static-folder/Cargo.toml
Bump static folder to 0.13.1, a new release that includes #762 fix for windows.
=> chore: bump static folder to 0.13.1

Containerfile, cargo-shuttle/src/provisioner_server.rs, docker-compose.yml, extras/otel/Containerfile, extras/panamax/Containerfile, extras/postgres/Containerfile, provisioner/tests/helpers.rs
This is useful for users of Podman, which isn't configured out-of-the-box to use the `docker.io` registry. It's also a good security practice, in case of a misconfigured default registry.
=> Reference container images by full name

proto/Cargo.toml, proto/build.rs, proto/src/generated/provisioner.rs, proto/src/generated/runtime.rs, proto/src/lib.rs, proto/tests/bootstrap.rs
This commit uses a test to compile and generate the `.proto` files, which we then commit, and with the test running in CI we ensure that the generated files are up-to-date if any changes are made to the `.proto` files. This means the protobuf compiler does not need to be installed to compile `shuttle-proto`, which also means it won't be required to install the `cargo-shuttle` CLI.
Protoc will still be required to run/build shuttle projects until we update `opentelemetry-otlp` to 0.19, which has been released, we just need to wait for `tracing-opentelemtry` to be updated as well (or do it ourselves). After upgrading these crates `protoc` will no longer be required for shuttle users, it will only be required to make changes to the `.proto` files in `shuttle-proto`.
With this PR we should …
=> feat: commit generated proto files

cargo-shuttle/src/lib.rs, deployer/src/deployment/queue.rs, runtime/tests/integration/helpers.rs, service/src/builder.rs, service/src/lib.rs, service/tests/integration/build_crate.rs, service/tests/resources/workspace/Cargo.toml, service/tests/resources/workspace/alpha/Cargo.toml, service/tests/resources/workspace/alpha/src/main.rs, service/tests/resources/workspace/next/Cargo.toml, service/tests/resources/workspace/next/src/lib.rs, service/tests/resources/workspace/shared/Cargo.toml, service/tests/resources/workspace/shared/src/lib.rs
Allows compiling of an entire workspace. With this, a deploy / local run works from a workspace. For the time being a `Shuttle.toml` is needed to know the name of the project.
Closes #417 
New tests have been added. A local deployer and the local runner was also used to make sure everything still works.
=> feat: compile an entire workspace

cargo-shuttle/src/args.rs, cargo-shuttle/src/config.rs, cargo-shuttle/src/lib.rs
This PR improves how we get the name of the project and how we identify the root `Cargo.toml` file in a project.
This is the preferred order for a project name:
1. Name given on command line                           
2. Name from Shuttle.toml file                          
3. Name from Cargo.toml package if it's a crate         
3. Name from the workspace directory if it's a workspace
By running the tests locally and adding new tests. Note, the tests require shuttle-hq/examples#35
=> refactor: getting project name

.circleci/config.yml, deployer/prepare.sh
This switches deployers to use sparse registries, this way each deployer does not need to download the entire index before compiling a project. We might also see some performance gains in CI by switching to sparse registries, I'll try that out as well (hence the draft).
I have deployed this to unstable and deploying a service on a fresh deployer takes about 2/3 the time. I am not seeing the new sparse registry progress bar, but we didn't see the progress bar for fetching the entire index either so maybe compiling with the cargo crate doesn't support that. :shrug:
=> feat: use sparse registry in deployers

cargo-shuttle/src/lib.rs, deployer/src/deployment/queue.rs, runtime/src/next/mod.rs, runtime/tests/integration/helpers.rs, service/Cargo.toml, service/src/builder.rs, service/tests/integration/build_crate.rs, service/tests/resources/workspace/Cargo.toml, service/tests/resources/workspace/Shuttle.toml, service/tests/resources/workspace/alpha/Shuttle.toml
This makes it so all services in a workspace are started for local runs. This required making some changes to build_crate and refactoring the runtime enum so we can get the working directory of each crate, as well as the service name.
TODO:
Tested by running updated tests and local runs of the `service/tests/resources/workspace` project.
=> feat: start all services in a workspace for local runs

common/src/lib.rs, common/src/models/resource.rs, resources/aws-rds/src/lib.rs, resources/persist/src/lib.rs, resources/secrets/src/lib.rs, resources/shared-db/src/mongo.rs, resources/shared-db/src/postgres.rs, resources/static-folder/src/lib.rs, runtime/src/resource_tracker.rs, service/src/lib.rs
This change causes `ResourceBuilder`s to output the build config they were constructed with. This allows for richer info when building the resource tables.
Using the local runner
=> refactor: get the static folder name from the

cargo-shuttle/src/lib.rs, deployer/src/deployment/deploy_layer.rs
This fixes the bug where the deploy command would error if the working tree is dirty, rather than display the warning about the working tree being dirty and the suggestion to us --allow-dirty.
Fixes https://github.com/shuttle-hq/shuttle/issues/775
Tested by deploying to unstable (on windows).
=> fix: is_dirty path bug on windows

CONTRIBUTING.md
With the addition of the auth service, how we start the deployer for local development has changed quite a bit. This PR updates the guide in contributing.md with the new steps.
This PR does make any changes to make starting the deployer locally easier, it just documents how it can be done currently.
Tested by starting the deployer locally and deploying examples to it.
=> docs: update deployer local run guide

cargo-shuttle/src/lib.rs
Revert the use of portpicker to get the port to start a service on for local runs.
Local runs.
=> fix: revert use of portpicker for local run

CONTRIBUTING.md, README.md, cargo-shuttle/README.md, cargo-shuttle/tests/integration/main.rs, common/src/models/error.rs, e2e/tests/integration/helpers/mod.rs, runtime/src/lib.rs
Fixes some missing renames of project commands, and update some tests that now give an error from cargo metadata rather than cargo.
Ran the updated tests.
=> fix: cargo shuttle integration tests, project cmd renaming

.circleci/config.yml, .circleci/qa-docker.sh, .circleci/qa-wasm.sh, .circleci/qa.sh, cargo-shuttle/src/lib.rs
This sets up a CI workflow to test our QA on Linux before a release.
The CI will do that :wink:
=> ci: linux QA

cargo-shuttle/src/args.rs, cargo-shuttle/src/lib.rs, deployer/src/persistence/mod.rs
Closes #743 
/claim #743
Adds the described functionality.
Tested against my projects in production. Works as expected.
=> feat: Add `cargo shuttle logs --latest`

CONTRIBUTING.md, deployer/src/handlers/error.rs, deployer/src/handlers/mod.rs
This makes the 404 messages for deployer more understandable for users, and also includes a suggestion to run deploy.
Closes #766 
Running deployer locally and testing all the commands.
=> feat: improve deployer 404 messages

resources/static-folder/README.md
Following discussion on https://github.com/shuttle-hq/shuttle/issues/763 add information about shuttle-static-folder to the documentation.
Note. Example link assumes that https://github.com/shuttle-hq/examples/pull/38 has been merged to examples.
Intended to close https://github.com/shuttle-hq/shuttle/issues/763
Docs change so not really testable, but I checked the that .md renders ok in CLion.
=> docs: clarify shuttle_static_folder will not be adjacent to executable

.circleci/config.yml, Cargo.lock, cargo-shuttle/Cargo.toml, common/src/models/project.rs, gateway/src/project.rs
This fixes some minor development bug fixes, namely:
- When releasing a new version some old projects without `idle_minutes` set will be deserialized without it, leading to panics. Added a serde default to `ProjectCreating` to remedy this.
- Removed the unused shuttle-secrets dependency from cargo-shuttle that was causing the new version of cargo-chef to fail to cook.
The idle-minutes change is hard to test since we're not entirely sure which projects caused it, but we should not see the panics anymore. The cargo-chef fix is tested by running `make images`.
=> fix: minor development bug fixes

common/Cargo.toml, common/src/database.rs, common/src/deployment.rs, common/src/log.rs, common/src/models/deployment.rs, common/src/models/project.rs, common/src/models/secret.rs, common/src/models/service.rs, common/src/models/stats.rs, common/src/resource.rs, deployer/Cargo.toml, gateway/Cargo.toml
User projects have a dependency on `shuttle-common`, which depends on `utoipa`. Howerver, `utoipa` dependency is not relevant to the user projects so this PR is feature gating the use of `utoipa` dependency and makes it optional when consuming `shuttle-common`.
Created a shuttle-rocket project, built it, and verified that `utoipa` is not appearing as a dependency in the `target` directory.
=> fix(common): feature flagged utoipa dependency

cargo-shuttle/Cargo.toml, cargo-shuttle/src/lib.rs, proto/src/lib.rs, runtime/src/alpha/mod.rs, runtime/tests/integration/helpers.rs, runtime/tests/integration/loader.rs
Running user services locally through `cargo shuttle run` will run a runtime that will load/start a service as a tokio task. If the task panics, the shuttle-runtime will live on because of tokio behavior: https://github.com/tokio-rs/tokio/issues/2002.
This is not the case anymore. I haven't seen this making any difference for our use cases. Removing it to have the `bind_panic` test succeed.
~~Extra: set to true the `kill_on_drop` flag for started shuttle-runtimes to make sure we either `.wait()` or `.kill()` on them or if dropped, the `kill` is automatically issued: https://docs.rs/tokio/latest/tokio/process/struct.Command.html#method.kill_on_drop.~~
Run locally the `hello-world-rocket-app` example with panic in it. Consequent local runs without the fix hang with the `Address in use` …
=> cargo-shuttle: fix address in use error when service panicked in a previous run

cargo-shuttle/src/lib.rs
Separated `local_runs` per target family. Runtime checking the target family will not compile on all platforms because we use platform specific APIs which can not be compiled on all platforms.
Same as for #805 .
=> cargo-shuttle: separate local runs per target family

.circleci/config.yml, Cargo.lock, Cargo.toml, Containerfile, Makefile, README.md, common/Cargo.toml, deployer/prepare.sh
Since we are still waiting for upstream PRs to get merged, we can't remove protoc yet, since we can't publish crates with a git dependency.
=> revert: protoc removal

.circleci/qa-wasm.sh
Shuttle-next example returns "Hello, World", not "Hello, world".
=> fix: wasm qa casing

.circleci/config.yml
The docker qa is failing due to a spurious error on first local runs of a project with a postgres database, one the second run it succeeds. I verified locally that this is indeed the case. I am disabling this test until we can fix that, and also the requirement for qa to complete for the bin builds to start (the published release will be a draft anyway).
=> fix: disable docker QA

CONTRIBUTING.md, deployer/src/args.rs, docker-compose.dev.yml, runtime/src/alpha/args.rs
Closes #851
On MacOs, port 5000 is used by AirPlay receiver which will make the 'make up' command described in CONTRIBUTING.md fail for Mac users
All occurrences of using port 5000 for the provisioner were changed to use port 3000 instead.
Tested by activating the AirPort receiver (on port 5000) and running 'make up' - works. `docker ps` shows that the provisioner is running on 3000.
=> build(docker): Change default provisioner port to 3000

Cargo.lock, cargo-shuttle/src/args.rs, cargo-shuttle/src/client.rs, cargo-shuttle/src/lib.rs, deployer/Cargo.toml, deployer/README, deployer/src/api/mod.rs, deployer/src/args.rs, deployer/src/handlers/deployment.rs, deployer/src/handlers/error.rs, deployer/src/handlers/local.rs, deployer/src/handlers/mod.rs, deployer/src/lib.rs, deployer/src/main.rs
This endpoint is still authenticated and will require a JWT corresponding to a user API key (existing in the auth persistence). It's not guarded by an `AdminLayer`.
Added a README that goes through the steps.
=> deployer: add a mock POST /deploy/:project_name endpoint

runtime/src/alpha/mod.rs, runtime/tests/integration/loader.rs, runtime/tests/resources/bind-panic-owned/Cargo.toml, runtime/tests/resources/bind-panic-owned/src/main.rs, runtime/tests/resources/loader-panic-owned/Cargo.toml, runtime/tests/resources/loader-panic-owned/src/main.rs, runtime/tests/resources/loader-panic/Cargo.toml, runtime/tests/resources/loader-panic/src/main.rs
Downcast panic message to `String` or `&str`.
closes issue #843 
Causing panics with Option and Result types.
=> fix: some panic messages get lost

.circleci/qa-wasm.sh, .circleci/qa.sh, CONTRIBUTING.md, cargo-shuttle/README.md, cargo-shuttle/src/init.rs, cargo-shuttle/tests/integration/init.rs, cargo-shuttle/tests/integration/run.rs
These are changes related to changing the /hello to '/' route in the examples repo
Issue: https://github.com/shuttle-hq/shuttle/issues/841
Related PR in the examples repo: https://github.com/shuttle-hq/shuttle-examples/pull/41
Each framework sample was manually deployed and tested (using curl and hitting the root route)
We wanted to test it with e2e tests but there seems to be an issue there, see https://github.com/shuttle-hq/shuttle/issues/849
Going to watch CI tests below as well
We may need to merge the examples repo into main first since this is a multiple repo change
=> feat: remove /hello from tests/ci

CONTRIBUTING.md, Makefile
SHUTTLE_DETACH can be set to disable, so when `make up` is run docker-compose stays attached. This was discussed in batch-tech.
I ran `make up` with SHUTTLE_DETACH set and without it set.
=> feat(Makefile): add option to disable --detach on make up

.circleci/config.yml, resources/shared-db/Cargo.toml, resources/shared-db/README.md, resources/shared-db/src/lib.rs
Adds feature `postgres-rustls` to `shuttle-shared-db`, allowing to use Postgres without relying on bindings to native SSL implementation.
Closes issue #690.
Created new example in https://github.com/shuttle-hq/shuttle-examples/pull/43, local run with both `postgres` and `postgres-rustls` feature is working:
`postgres`:
`postgres-rustls`:
=> add option to use rustls instead of native-tls in `shuttle-shared-db`

codegen/src/shuttle_main/mod.rs, codegen/tests/ui/main/missing-return.stderr, codegen/tests/ui/main/return-tuple.stderr
Updated doc string URL to match current URL for resource.
Please write a summary of your changes and why you made them. 
URL in returned error doesn't  point to current Shuttle Service docs.
Be sure to reference any related issues by adding `closes issue #`.
Ran `cargo clippy --tests --all-targets` and `cargo check`
=> Match doc links with Shuttle Service current doc url

common/src/claims.rs
Fix a bug where the scopebuilder was simply duplicating the standard scopes, not extending with admin scopes.
=> fix:  set correct admin scopes in scopebuilder

Cargo.lock, common/Cargo.toml
Bump and publish common 0.16.2 with scopebuilder fix.
=> chore: bump common to 0.16.2

cargo-shuttle/README.md
This PR updates the README.md of `cargo-shuttle` for expanding the installation section.
I recently packaged `cargo-shuttle` for Arch Linux and now it can be installed via `pacman`: https://archlinux.org/packages/community/x86_64/cargo-shuttle/
Also, I added a [repology](https://repology.org/) badge for viewing the other distribution packages.
\-
=> docs: add installation instructions for Arch Linux

Cargo.lock, deployer/Cargo.toml, deployer/src/deployment/queue.rs, deployer/src/error.rs
* feat: remove cargo dependency
Replace the cargo crate with a process call to the cargo cli and send stdout to the message pipe.
closes issue #903 
Tested by modifying the rocket authentication test to fail.
=> feat: show output of failed tests

Cargo.toml, auth/Cargo.toml, auth/src/api/builder.rs, auth/src/api/handlers.rs, auth/src/user.rs, auth/tests/api/users.rs, cargo-shuttle/src/args.rs, cargo-shuttle/src/client.rs, cargo-shuttle/src/lib.rs, gateway/src/api/auth_layer.rs
A user should be able to reset their api-key, this is important functionality to have in case users leak their key. This should generate a new api-key and persist it in the users table.
Fixes #838.
=> feat: allow resetting a user's API-key

Cargo.lock, runtime/Cargo.toml, runtime/src/alpha/args.rs, runtime/src/alpha/mod.rs, runtime/src/args.rs, runtime/src/bin/shuttle-next.rs, runtime/src/lib.rs, runtime/src/next/args.rs
This removes the `shuttle_runtime` dependency on `clap`, by explicitly implementing very simple argument parsing.
I hope you like macros :innocent:.  If not, I'll just replace the macro with its expansion - which is exactly the code I wrote before converting it to a macro.
Closes #819
/claim #819
=> feat(runtime): Remove dependency on clap

CONTRIBUTING.md
Update api-key for deployer local runs, and update casing of shuttle which was done in shuttle docs (but should have been done here).
=> docs: contributing updates

Cargo.lock, Cargo.toml, deployer/Cargo.toml, gateway/Cargo.toml
I'm trying to package cargo-shuttle for nixpkgs, and this fixes `cargo vendor`
```
error: failed to sync
Caused by:
found duplicate version of package `hyper-reverse-proxy v0.5.2-dev` vendored from two sources:
source 1: https://github.com/chesedo/hyper-reverse-proxy?branch=bug/host_header#5f82b7df
source 2: https://github.com/chesedo/hyper-reverse-proxy?branch=master#e73a7660
```
Be sure to reference any related issues by adding `closes issue #`.
=> chore: promote hyper-reverse-proxy to a workspace dependency

cargo-shuttle/src/lib.rs
=> suggest next logical command

gateway/src/service.rs
Gateway certificate renewal API checks whether the certificate entered its last 30 days of validity before actually processing the renewal. However, the check doesn't account for an expired certificate and the logic breaks the renewal even if it's the case to renew.
N/A
=> fix(gateway): handle certificate expiration as well

Containerfile, Makefile, deployer/prepare.sh
We'll need to remove the crates.io patches for the local repository when deploying to production. The idea of the change is to forward the `PROD` argument from `make images` command to the `deployer/prepare.sh`. The script will account for patching the `crates.io` or not depending on how the images are built. When building the production images in `.circleci`  we set the `PROD` argument to `true` when building `make images`.
Tested the bash `if .. else` branch on my zsh terminal and works well.
=> release(prod): gate against local crates.io patch

.circleci/config.yml
Our crates depend on protoc so we need to install it on the executor which does the crates publishing. Also, fixed the services dependency on shuttle-runtime. 
N/A
=> release(prod): add protoc dependency and fix the crates order

services/shuttle-axum/src/lib.rs
Made `AxumService` generic to be able to use it with `axum::State` and updated the `From` impl for it. This won't have any impact on existing usages as it defaults to the unit type, e.g.:
```rust
pub struct AxumService<S = ()>(pub axum::Router<S>);
```
I also created an [`axum/with-state` example](https://github.com/morlinbrot/examples/tree/feat/axum-with-state) to test this, let me know if you want this in the examples repo.
Built all the axum examples with it.
=> feat(shuttle-axum) Make AxumService generic to be able to use state

cargo-shuttle/src/config.rs
This PR allows users to run cargo shuttle commands from outside a cargo folder when the `--name` option is provided.
closes issue #927 .
Ran the command `cargo shuttle stop --name helloworld` locally. It no longer throws the "could not find Cargo.toml" error.
=> fix: --name was ignored when not running from cargo folder

.circleci/config.yml, Cargo.lock, Cargo.toml, Containerfile, Makefile, README.md, common/Cargo.toml, deployer/prepare.sh
This bumps the otel crates so we no longer need protoc installed to use shuttle.
Closes #916 
Tested in CI, tested in previous removal PR, tested again with `PROTOC="" cargo run --bin cargo-shuttle ...`.
=> chore: bump otel crates and remove protoc dep

cargo-shuttle/src/lib.rs
This PR adds info level log for each file added to the archive. Users will be able to see these logs if they set the appropriate level in the RUST_LOG env var. E.g. `RUST_LOG=cargo_shuttle=info`.
closes issue #930 .
Ran the `cargo shuttle deploy` command locally.
=> fix: log files packed in archive

Cargo.lock, gateway/Cargo.toml, gateway/src/proxy.rs
If users don't properly handle input paths then they can open themselves up to path traversal vulnerabilities. We can protect all our users by taking care of this at our proxy layer.
Using the local dev environment to ensure path traversals are removed from all proxy requests.
=> refactor: sanitize all path on the user's proxy

.circleci/config.yml, Cargo.lock, Cargo.toml, common/Cargo.toml
`comfy-table` exposes crossterm types publicly, and crossterm had a breaking change in 0.26, so when comfy-table updated their crossterm version in a patch release it broke the install of `cargo-shuttle`, since comfy-table was automatically updated (unless --locked is passed to install) but crossterm was not.
Verified that upgrading comfy-table before upgrading crossterm causes compile-error in shuttle-common, and upgrading both fixes it.
=> fix: crossterm/comfytable conflict

deployer/prepare.sh
Closes #807.
Added some common (C) build tools when installing deployer.
This allows crates such as `audiopus` to build.
If there are more tools needed, they can be suggested or added in subsequent PRs.
Deployed a crate with `audiopus v0.2.0` locally. https://crates.io/crates/audiopus/
=> feat: pre-installed build environment in deployer

runtime/src/logger.rs
Closes #955
Tested on my serenity bot (0.12) and hello world example (0.11) - no more spam, back to normal amount of logs as before
Tide hello world gives the same amount of logs before and after
=> fix: Ignore span logs below WARN

.circleci/config.yml
Our dev AWS creds were set for the `.circleci` machine when deploying Shuttle to prod because the environment variables names are the standard AWS environment variables names for credentials and are picked up by `aws-ecr/ecr-login` step, which conflicts with how we set the ecr-login in our `.circleci/config.yaml` file. At the same time, the PROD variables' names used in the `.circleci/config.yaml` had a typo 🙈  (which might have been the main reason why the ecr-login failed, besides the standard env variable names issue). To fix everything this PR changed the dev environment variables' names to non-standard names, so as to not be picked up by the `aws-ecr/ecr-login` step and double-checked the env vars used in the `.circleci/config.yaml` to be the ones from the circleci project settings. …
=> fix/release(prod): unstable AWS creds clashed with prod

cargo-shuttle/src/lib.rs
#862 flipped the order of deployment list, making the --latest flag get the oldest deployment.
=> fix: logs --latest flipped order

Cargo.lock, runtime/Cargo.toml, runtime/src/bin/shuttle-next.rs
Re-adds the `--version` flag.
Closes #992.
Ran locally.
=> fix: re-add `--version` flag

auth/src/api/builder.rs, auth/src/api/handlers.rs, auth/tests/api/session.rs, auth/tests/api/users.rs
When working on the `auth` service we created some endpoints that would be called by the console, but that the console was not ready to use yet at the time of implementation. When we did this we missed the admin guard on one of these routes, meaning it was callable by anyone. If this endpoint was called with a users ID it would return their user data (user ID, api-key and account tier). When we realized this was the case we closed the endpoint and deployed the fix to production immediately.
This was an oversight on our part, but we have verified with our telemetry data that this vulnerability has never been exploited, as the endpoint has never been called successfully outside of our testing. We have also reviewed our `auth` service for other vulnerabilities and ensured all sensitive …
=> fix: remove auth login endpoint

cargo-shuttle/src/args.rs
This commit adds a couple of example `cookbook` style commands to the `--help` subcommand of `cargo-shuttle`. 
It took some time for me to realise the difference between `deploy` and `deployments`, or to discover that I could watch my logs in real time via `logs --follow`. My hope is that this extended help assists newcomers in figuring out what cargo-shuttle can do.
As a side note, I understand that this adds a bit of bloat to the help command, and maybe this sort of information is better off somewhere in the docs or in the descriptions for each of the subcommands, so feel free to close this PR if it does not fit in with the overall goals of where information should be.
=> Add commands cookbook to cargo-shuttle --help

common/src/lib.rs
Title~
Came up in a discussion about secrets https://discord.com/channels/803236282088161321/1107140940759568384/1118625700824485928
Added test
=> feat(secrets): Implement into_iter for SecretStore

Cargo.lock, provisioner/src/lib.rs
When we provision an rds database we use the engine name for the database name, this does not work for mysql. As a quick fix I changed it so mysql uses "msql" instead, because we currently don't have any mysql databases (it has not been possible). If we were to change the naming for all databases, we'd have to rename all the existing databases, which we don't want to prioritize right now.
Deployed the changes to unstable and deployed a mysql project. I might have uncovered a newer bug where a deployment with an rds database crashes (or incorrectly returns crashed) when it starts waiting for the rds instance to be ready, but looking at aws and provisioner logs the database did get successfully provisioned.
We need to renew the unstable certificate so we should do that and double check this …
=> fix: mysql provisioning bug

.circleci/config.yml, cargo-shuttle/tests/integration/run.rs
We forgot to remove this before merging the rustls PR, so it caused production CI binary builds to fail. A cleanup PR was also merged in the examples that changed an endpoint we used for testing in cargo-shuttle.
=> fix: remove vendored-openssl from CI and broken axum test

.circleci/config.yml, Cargo.lock, cargo-shuttle/Cargo.toml
`cargo-generate` needs openssl, so we can't remove it currently.
=> fix: cargo-generate needs openssl

deployer/src/handlers/mod.rs
Since we no longer just stream the entire body when receiving an archive to deploy, we are hitting the default body size limit in axum of 2MB for several projects. This PR increases the limit to 50MB.
Thanks to @jonaro00 for debugging and testing this!
Tested with a 5MB project, which worked after the layer was applied.
=> fix: increase body size limit for deploy

cargo-shuttle/src/lib.rs
Moved this to a separate PR instead of together with unrelated stuff in #1012 
Original comment:
Hardcode to not upload the .git folder at deploy (the metadata is gathered before upload). This can shrink the upload size by a bit. If a project uses the local repo at build time for inserting, say, commit ID or something, this will break it. So perhaps add an option to include it? Or make a bunch of metadata available as a resource, like https://github.com/shuttle-hq/shuttle/issues/562
=> fix: Don't deploy .git folder to save space

Cargo.lock, cargo-shuttle/Cargo.toml
We recently set the body size limit for archives sent with `deploy` to 50MB, but a lot of .git repositories are larger than this. We don't need to send the .git repositories, however, so it was excluded in https://github.com/shuttle-hq/shuttle/pull/1036. We will release a patch version of the cargo-shuttle CLI that implements that fix.
=> chore: cargo-shuttle v0.19.1

builder/Cargo.toml, common/src/backends/auth.rs, common/src/claims.rs, deployer/Cargo.toml, deployer/migrations/0000_init.sql, deployer/src/dal.rs, deployer/src/deployment.rs, deployer/src/lib.rs, deployer/src/project/docker.rs, deployer/src/project/service/mod.rs, deployer/src/project/service/state/a_creating.rs, gateway/src/lib.rs, proto/deployer.proto, proto/src/generated/deployer.rs
* Added project events streaming for the deployer.
* Added project_id and last_updated to the services table.
Tested locally by:
* creating user services and looking at the event stream messages, seeing how the services go through all the states
* very important, once the service is in `Running` state, it should send the service socket addr.
=> [scaling] deployer: added project events streaming

common/src/models/deployment.rs, deployer/src/persistence/deployment.rs
I added the new `git_*` fields to the table output of `cargo shuttle deployment list`. 
Closes #981 
I created a new project via the rocket example and made local changes to check that the `git_dirty` field rendered correctly, and that truncating the commit ID and message worked as intended. I also created some deployments with a version prior to the addition of the new metadata to make sure the `Option` values correctly displayed `No Data` in the table.
=> feat: add new deployment metadata to table

CONTRIBUTING.md, README.md, cargo-shuttle/src/lib.rs, deployer/README.md, deployer/src/deployment/queue.rs, proto/src/lib.rs, resources/static-folder/src/lib.rs, service/src/lib.rs
- Got rid of 2 second sleep by polling instead. It was at first needed due to the runtime not having time to open a socket on that port. I now use a 5ms polling time for 500ms. My test took <3ms to connect (with 1ms poll time), so I set the poll time to 5ms.
- Code and docs cleanup
EDIT: Moved .git exclusion to #1036 to not clutter this PR too much.
Local run.
Let's see if CI likes it.
=> fix(runtime): Remove 2s startup sleep

cargo-shuttle/src/lib.rs, proto/src/lib.rs, runtime/src/alpha/mod.rs
Fixes more Windows issues discovered here https://discord.com/channels/803236282088161321/1122643649503694919
- Added more timeout to the runtime wait.
- The stopped_tx send calls are now ignored if they fail, because there is only a subscriber in deployment.
No further proof than Samarth's code working.
=> fix: windows local run + log clarifications

deployer/src/deployment/deploy_layer.rs, deployer/src/deployment/mod.rs, deployer/src/deployment/queue.rs, deployer/src/deployment/run.rs, deployer/src/lib.rs
The `shuttle-deployer` tests are sometimes failing when unrelated changes are made. This can be seen both during CI as well as when working locally (we faced that when working on the pagination).
It's quite hard to reproduce, but if we look at CircleCI errors (https://app.circleci.com/pipelines/github/shuttle-hq/shuttle/3134/workflows/c461d70f-616c-416a-a1e5-148ca2afa854/jobs/59077, https://app.circleci.com/pipelines/github/shuttle-hq/shuttle/3134/workflows/bd9ea5b5-c6bf-4262-bc58-2d82ce416341/jobs/59040, https://app.circleci.com/pipelines/github/shuttle-hq/shuttle/3109/workflows/aeefba11-ae65-48b7-b522-30b7931e32a9/jobs/58417, among others), we often get this error:
```
2023-06-05T08:35:40.737556Z ERROR builder:build_failed{error=InputOutput(Custom { kind: Other, error: "background task …
```
=> Attempt at fixing sporadic failures of `shuttle-deployer`

.circleci/config.yml, CONTRIBUTING.md, common/src/models/resource.rs, common/src/resource.rs, deployer/prepare.sh, deployer/src/persistence/resource/mod.rs, resources/turso/Cargo.toml, resources/turso/README.md, resources/turso/src/lib.rs, service/src/lib.rs
This adds support for Turso but without provisioning.
Close #986.
Locally yes, both with a local and a remote database.
- Clarify the few `XXX` in the code.
=> feat(resources): add support for turso client w/o provisioning

Containerfile
There was a bug where if the bash conditional evaluated to false, it would fail, I am not sure why. Changing it away from the shorthand resolved it.
Tested by running `make shuttle-provisioner` with and without PROD=true and both cases work.
=> fix: bash bug in containerfile

CONTRIBUTING.md
This fixes the parsing error in [the docs](https://docs.shuttle.rs/community/contribute). 
Tested with `yarn mintlify dev` in the docs repo on latest mintlify.
=> fix: remove md that is incompatible with docs

.gitmodules
I'm not an expert when it comes to git submodules, but the way they are specified at the moment made it hard for me to use the repo in a `Cargo.toml` via direct git links, i.e.
```toml
shuttle = { git = "https://github.com/shuttle-hq/shuttle" }
```
With the current implementation, I got the error
```
error: failed to get `shuttle-axum` as a dependency of package `blah v0.1.0 (/home/robw/repos/shuttle-examples/axum/diesel-postgres)`
Caused by:
failed to load source for dependency `shuttle-axum`
Caused by:
Unable to update https://github.com/RobWalt/shuttle?branch=feat/shared-db-diesel
Caused by:
failed to update submodule `examples`
Caused by:
failed to fetch submodule `examples` from https://github.com/RobWalt/examples.git
Caused by:
failed to authenticate when downloading repository
* …
```
=> chore: make git submodule path absolute to make life easier for forks

.circleci/config.yml
This corrects the incorrect path to the turso resource in the publish crates job.
=> ci: incorrect path to turso resource

Makefile, cargo-shuttle/src/lib.rs, common/src/lib.rs, deployer/src/deployment/deploy_layer.rs, deployer/src/deployment/run.rs, proto/runtime.proto, proto/src/generated/runtime.rs, proto/src/lib.rs, runtime/src/alpha/mod.rs, runtime/src/logger.rs
We were incorrectly assuming the state to be running in the logs received from a deployment, but they could also be loading (and they will be loading for a while in the case of rds). This lead to the client reporting that the deployment crashed since it received the running state in the logs stream, but the deployment was still loading (an unexpected state since we received running in logs). 
Closes #1029 
TODO: 
- We're not getting the logs from runtime during loading, although I think we used to (I remember seeing the "deploying <db_type>, this could take a while..." output). :thinking:  This means we get "loading service" from the deployer run function, and then nothing until loading is complete.
- Should we use rwlock for the logger state? Does it matter?
Tested by deploying tide rds …
=> fix: rds deploy crash

Cargo.lock, gateway/Cargo.toml
This bumps tower-sanitize-path to an updated version that does not normalize away trailing slashes, closing https://github.com/shuttle-hq/shuttle/issues/1028 once this change is deployed on Monday.
Tested in https://github.com/shuttle-hq/tower-sanitize-path/pull/6
=> chore: bump tower-sanitize-path

gateway/src/api/latest.rs, gateway/src/service.rs
When testing h2 project support, I discovered some broken gateway tests. These have (understandably) slipped through since we don't run them in CI, which is the bigger problem here. :smile:  The status test was not updated to reflect the changes we made to the gateway status check for the shuttle status page, and the pagination tests in service were not deterministic.
Run `USE_PANAMAX=disable make shuttle-deployer`, then run the test command from the gateway readme: 
```
SHUTTLE_TESTS_RUNTIME_IMAGE=public.ecr.aws/shuttle-dev/deployer:latest SHUTTLE_TESTS_NETWORK=shuttle-dev_user-net cargo test --package shuttle-gateway --all-features -- --nocapture
```
=> fix: broken gateway pagination and status check tests

cargo-shuttle/src/lib.rs
This commit modifies the command hint `cargo shuttle deploy` that appears at the end of `cargo shuttle init` so that it includes the `--allow-dirty` flag.
Without this flag, `cargo shuttle` will fail every time a newbie tries to init a new project because shuttle adds files to the project but doesn't commit them to git. Shuttle then notices that there are uncommitted files, and doesn't allow the newbie to deploy the project without specifically allowing the dirty files. This is a bit of a bad experience, because the newbie is just following instructions but also being told that those instructions were wrong.
This PR is a bit of a nit-pick, so feel free to close!
=> Add --allow-dirty to command hint at end of init

gateway/build.rs, gateway/migrations/0005_refactor_to_ulid_primary_key.sql, gateway/src/lib.rs, gateway/src/main.rs, gateway/src/service.rs
This adds a ULID for project IDs to gateway. This will be needed for the new resource recorder.
It also replaces the need for a `created_at` field since the ULID has a timestamp in it.
Most of gateway still uses the project name (and not this new id) everywhere. I think this is fine for now as the deployer update will take care to switch over to the IDs.
By running all the tests locally
=> feat: add a project_id to gateway

common/src/models/resource.rs, common/src/resource.rs, deployer/src/persistence/mod.rs, deployer/src/persistence/resource/mod.rs, resource-recorder/src/type/mod.rs, service/src/lib.rs
The `shuttle-common::resource::Type` misses the `Type::Custom` variant that gets to be used when provisioning custom resources according to the `service` crate docs.
Locally against https://github.com/shuttle-hq/shuttle-examples/pull/73 and on unstable.
=> Added the missing support for creating custom resources

Containerfile, Makefile, cargo-shuttle/src/args.rs, docker-compose.yml, resource-recorder/prepare.sh, resource-recorder/src/main.rs
Added a docker-compose service for resource-recorder and `Makefile` tag env variable.
Started Shuttle locally and it worked. Tested on unstable too.
=> resource-recorder: update the docker compose file

CONTRIBUTING.md, docker-compose.yml, extras/otel/otel-collector-config.yaml
This enables honeycomb but for local runs only. There will be a separate PR to update the CI for production
By checking the traces in my honeycomb account.
=> feat: honeycomb for local runs

cargo-shuttle/src/lib.rs, common/src/deployment.rs, deployer/src/deployment/deploy_layer.rs, deployer/src/deployment/run.rs, deployer/src/persistence/state.rs, deployer/src/runtime_manager.rs, docker-compose.yml, proto/src/lib.rs, runtime/src/alpha/mod.rs
Fixed runtime logs sending to the deployer.
Locally, by deploying a project and querying for the service logs. I was able to see the rocket logs of a rocket service.
=> deployer: fixed runtime logs receiving

CONTRIBUTING.md, auth/src/args.rs, auth/src/lib.rs, auth/src/main.rs, auth/src/user.rs, common/src/claims.rs
Makes it possible to add a new machine user that will have deployer rights
By creating new tests and running the updated contributing flow
=> feat: add deployer tier to auth

CONTRIBUTING.md, Makefile, docker-compose.yml, gateway/src/args.rs, gateway/src/lib.rs, gateway/src/project.rs, gateway/src/service.rs, gateway/src/task.rs
Expands gateways args with the key that will allow it to start up old deploys.
The work of converting the key to a JWT and starting the last idle deploys forms part of another ticket.
By trying to start gateway locally (with the Makefile) to confirm every works correctly
=> feat: expand gateways args to receive the key for the machine user

README.md
Closes #1083 and remove some outdated/unused info.
=> fix: Update information in README

resources/aws-rds/Cargo.toml, resources/shared-db/Cargo.toml
We need to upgrade sqlx to 0.7 in our resources, since users expect to be able to use it and it was released a while ago, but our current resources return a 0.6 pool.
Closes #1085
Local run of all examples that use the resources on this branch: https://github.com/shuttle-hq/shuttle-examples/pull/75
=> chore: bump sqlx in resources

cargo-shuttle/src/lib.rs
Gracefully handling windows signal to interrupt local run for #872.
/claim #872
Tested by running on windows, with Ctrl+C
=> feat: Handling regular signals sent to cargo-shuttle on Windows

docker-compose.yml
We had two reports of MongoDB databases resetting recently. The reason is that the shared MongoDB container was remade, and it was never assigned a volume, so the data was not persisted. 
Deployed the container with the new volume without losing the current data in our staging environment.
=> fix: add volume to mongo container

Containerfile, deployer/prepare.sh
~~This ensures the shuttle-next runtime binary is installed in the deployer, which shuttle-next services expect. This means building the deployer image will always need to install shuttle-next, which is not ideal.~~ 
The shuttle-next binary was failing to install for production builds since the prepare.sh had already ran once and set the registry to panamax, so when the prepare.sh for shuttle-next install was ran it was trying to fetch the crates from panamax (which is not available when we build the images, it is for deployers to use at runtime). 
In the future, we should consider releasing the shuttle-next binary like we do for the cargo-shuttle CLI, so it can simply be downloaded from GitHub.
Closes #1096 
Deployed new image to unstable and it's working now.
=> fix: install shuttle-next runtime in deployers

cargo-shuttle/src/lib.rs, runtime/src/alpha/mod.rs, runtime/src/bin/shuttle-next.rs, runtime/src/lib.rs
Add a version flag check to the alpha runtime and check if its version is the same as the version of cargo-shuttle. Warn the user if that is not the case and give hints. The next runtime already has such a check.
Closes #1053
=> feat(runtime): add alpha runtime version check

gateway/src/project.rs
We try to access the project id on the container in the code below, but we never set it.
https://github.com/shuttle-hq/shuttle/blob/609411c2d98e52f20d24830aa527598a4347dc9f/gateway/src/project.rs#L107-L114
Nan
=> bug: project_id label missing

.circleci/config.yml
Upgrading to the m1 mac for the mac binary builds should improve speed, see: https://circleci.com/blog/m1-mac-resource-class/
The mac machine we were using was also about to be deprecated in october.
Tested in CI. Reduced total time of job from ~11 min to ~4 min, and I verified the binary still works on arm and intel macs.
=> ci: upgrade mac bin build machine

Containerfile
This PR updates the base image of Containerfile to `lukemathwalker/cargo-chef` to avoid installing `cargo-chef` via `cargo install`.
\-
=> chore(container): use pre-installed cargo-chef image

resources/static-folder/src/lib.rs
We want to copy the contents of the build storage for the static file to the runtime storage. That can happen during the `ResourceBuilder::build` call.
Locally, deploying an axum static-files project, and checking that at a second deployment the assets were updated.
=> fix: static folder is not updated

resources/static-folder/src/lib.rs
Fixed clippy for static-folder tests.
Run `cargo clippy --tests` locally against static-folder.
=> static-folder: fix clippy

cargo-shuttle/Cargo.toml
This dependency is not used anywhere in cargo-shuttle.
cargo-udeps and CI.
=> fix: unused sqlx dep

.circleci/config.yml, DEVELOPING.md, Makefile, common/src/models/resource.rs, common/src/resource.rs, deployer/prepare.sh, deployer/src/persistence/resource/mod.rs, e2e/tests/integration/helpers/mod.rs, resources/service-info/Cargo.toml, resources/service-info/README.md, resources/service-info/src/lib.rs
This PR adds a new `ServiceInfo` type of resource which provides some information about the current service's runtime environment.
Closes #562.
I've tested this a tiny amount in a project I have running locally but don't really trust it yet - would love if someone can test it better!
---
Note: I'm getting married this weekend then going straight on my honeymoon so won't really have time to follow up on this for a couple of weeks! 💒 🌴 Please feel free to push any fixes up, or make a completely different branch if needed, and merge whenever you're happy.
=> feat: add service-info resource to obtain Shuttle service info

DEVELOPING.md, common/src/backends/tracing.rs, deployer/src/deployment/mod.rs, deployer/src/handlers/mod.rs, deployer/src/lib.rs, deployer/src/main.rs, deployer/src/persistence/mod.rs, proto/src/lib.rs
Updated `get_logs` and `get_logs_stream` deployer methods to be based on `shuttle-logger`.
This PR is rebased on top of #1139 .
N/A, pending on #1139 .
=> deployer: update logs APIs  to fetch the logs from shuttle-logger

logger/src/dal.rs, logger/tests/integration_tests.rs
Previously we dropped on any span name information, but we'll need them to be shown in `cargo-shuttle`.
Through integration tests. Need to follow up with more local/unstable testing soon.
=> logger: store span names 

.circleci/config.yml, Cargo.lock, DEVELOPING.md, cargo-shuttle/Cargo.toml, deployer/prepare.sh, e2e/tests/integration/helpers/mod.rs, resources/aws-rds/Cargo.toml, resources/aws-rds/README.md, resources/aws-rds/src/lib.rs
Replaces #1017. 
- CI improvements. Optimized caches and core count to both speed up and reduce costs.
- added rustls feature flags to aws-rds
- cargo update
Lots of testing done: https://app.circleci.com/pipelines/github/shuttle-hq/shuttle?branch=pull%2F1167
=> ci: refactor and improve speed and caching. add rustls flags to aws-rds

Cargo.lock, cargo-shuttle/src/lib.rs, deployer/Cargo.toml, deployer/src/deployment/deploy_layer.rs, deployer/src/deployment/run.rs, deployer/src/main.rs, deployer/src/runtime_manager.rs, proto/src/lib.rs
Simply capture logs and send them to the logger service.
yolo.
=> feat(deployer): send runtime logs to the logger service

Cargo.lock, runtime/Cargo.toml, runtime/src/alpha/mod.rs, runtime/src/lib.rs, runtime/src/provisioner_factory.rs, runtime/src/resource_tracker.rs
Removes the tracing dependency from runtime since we can use stdout instead.
Using `cargo shuttle run` on a postgres project
=> refactor: remove tracing from runtime

logger/src/lib.rs
Changes all `println!` inside shuttle-logger with some tracing call
NaN :see_no_evil:
=> refactor: remove println from shuttle-logger

runtime/src/bin/shuttle-next.rs, runtime/src/next/mod.rs
Fixes the following build failure:
```
error[E0432]: unresolved import `tracing`
--> runtime/src/next/mod.rs:26:5
|
26 | use tracing::{error, trace, warn};
|     ^^^^^^^ help: a similar path exists: `shuttle_common::tracing`
```
=> refactor(runtime): replace trace with println

common/src/models/error.rs, gateway/src/service.rs
The command `cargo shuttle project start` fails if a project with the same name is already present. The error message that's printed now tells the caller that their project is already running if they are the project owner.
Closes #1155
One assertion has been added to the relevant test for each new case. They make sure that the new error variant `ErrorKind::ProjectAlreadyRunning` is returned if either the owner or an admin tries to recreate a running project.
=> feat(gateway): special error if own project is already running

resources/persist/src/lib.rs
Small simplification of persist API that also f i x e s [an error in examples ](https://github.com/shuttle-hq/shuttle-examples/pull/40#issuecomment-1703842094)
=> fix(persist): don't use lifetime in error

common/src/models/error.rs, gateway/src/lib.rs, gateway/src/service.rs
`cargo shuttle project start` fails if the project already exists. If the existing project is owned by the caller of the command, new error messages are now  displayed. They automatically provide the project owner with the current status of their project, and they indicate that her or his project is running. Depending on the current state, different hints are also provided.
Extends #1192
The assertions added in #1192 have been updated to match the changes.
=> feat(gateway): inform project owner about running state

common/src/log.rs, deployer/src/runtime_manager.rs
Fixes start error because service name is unknown
Using the mob :smile:
=> bug: service name being unknown

README.md, cargo-shuttle/src/args.rs, cargo-shuttle/src/lib.rs, cargo-shuttle/src/main.rs, cargo-shuttle/tests/integration/init.rs, cargo-shuttle/tests/integration/main.rs, codegen/src/lib.rs, common-tests/src/cargo_shuttle.rs, runtime/README.md, runtime/src/lib.rs
- Giving template and proj name but no path used to assume path='.', but will now correctly see that you didn't provide path, and prompt you.
- Warning can let you quit the init:
Added a test that tests one version of these two changes in combination.
=> feat(cargo-shuttle): prompt for init path when not given, warn if init dir not empty

codegen/src/shuttle_main/mod.rs, runtime/src/resource_tracker.rs
Rebased on top of #1209.
* Runtime resource tracker emit logs prepended by a timestamp we add explicitly. This was removed.
* Our default tracing fmt layer formats events by prepending a timestamp, but we also emit the timestamp for each line from the runtime stdout collecting logic. I changed the default tracing layer to format events without a timestamp.
Note:
* users custom tracing is not touched and if they emit timestamps they will pop up in the deployment logs. I think this should be expected behavior and leave the users the choice to format their logs as wanted. 
Tested locally:
* with the default tracing
* without the default tracing
=> refactor(runtime,codegen): avoid double timestamps problem

Cargo.toml, cargo-shuttle/src/lib.rs, codegen/src/shuttle_main/mod.rs, common/src/deployment.rs, deployer/src/deployment/queue.rs, deployer/src/deployment/run.rs, runtime/Cargo.toml, runtime/src/alpha/mod.rs, service/src/builder.rs
=> feat(codegen): restore default log level, improve error messages

Containerfile
Moves build steps around to reduce deployer rebuild time by ~40s.
Hopeful for [this](https://github.com/LukeMathWalker/cargo-chef/pull/241), as it should improve rebuild times even more.
=> feat(containerfile): improve deployer build caching

services/shuttle-poise/src/lib.rs, services/shuttle-serenity/src/lib.rs
Enable auto-sharding in shuttle-poise for Discord bots in 2500+ servers/guilds to work.
This PR shall resolve #1215.
Natsuki, my Discord bot, is happily running on shuttle.rs right now.
https://github.com/jdh8/natsuki
https://console.shuttle.rs/project/natsuki
https://discord.com/application-directory/410315411695992833
I only removed the dangling submodule `examples` in the `deploy` branch.  It is otherwise the same as the main branch.
=> Enable auto-sharding in shuttle-poise

extras/otel/otel-collector-config.yaml
Restores the exporters we disabled to ease local testing when we used the otel collector to export traces to our logger. This is a rollback to the previous code.
Only tested that the local environment runs as normal with this change. The otel collector fails with missing api-keys, as it always has for local environments.
=> fix(otel): restore honeycomb and dd exporters

common/src/log.rs, deployer/src/handlers/mod.rs, deployer/src/lib.rs, runtime/src/alpha/mod.rs, runtime/src/lib.rs
=> fix: truncate log item strings

common/src/backends/metrics.rs
We're no longer seeing the tracelayer logs in the deployer, since it's now defaulting to INFO. This changes the tracelayer span to INFO so we can see it. 
PS. this macro is also used in gateway and auth.
Verified we can see the tracelayer output in a local environment.
=> feat(common): change request_span macro to info level

logger/src/dal.rs, logger/src/lib.rs
We used a while let loop in the logger, if the channel overflowed it would return a lagged error. This way we can rather trace the error and see clearly when it occurs (and keep listening on the channel).
Tested by deploying to staging.
=> feat(logger): refactor to loop, add traces

Cargo.lock, logger/src/dal.rs, logger/src/lib.rs
This adds a debug trace of the logger broadcast channel queue size at an interval of 10 seconds.
The lockfile changes were missed in the logger branch cleanup PR.
Tested in local environment, will test in staging too.
=> feat(logger): logger queue size trace

Cargo.lock, cargo-shuttle/src/provisioner_server.rs
I was fiddling with shuttle and got this error message: 
```
2023-05-28T14:00:28.144975Z ERROR cargo_shuttle::provisioner_server: got unexpected error while inspecting docker container: error trying to connect: No such file or directory (os error 2)
2023-05-28T14:00:28.146904Z ERROR cargo_shuttle: failed to load your service error="Custom error: failed to provision shuttle_aws_rds :: Postgres"
```
Which isn't super helpful. But after googling, I managed to see that it's explained in the docs. This commit just links the docs so that future travelers will know where to go to look for help.
=> Add helpful error message on docker container error

docker-compose.yml
The default network subnet overlapped with our VPC subnet, leading the logger service to not be able to reach the rds instance via DNS.
Applied to staging environment.
=> fix: default network subnet overlap

gateway/src/project.rs
Projects sometimes seem to get stuck in a startup loop when the startup accidentally runs with a project stop command. That is because this `refresh` function, maybe being called from the ambulance task, maybe from something else, would have incorrectly put a project that is starting up, directly after a restart, back into the restart state.
By starting gateway locally and messing with the container state to first reproduce it and then to confirm the fix is working.
=> bug: project entering a state loop

deployer/src/deployment/mod.rs, deployer/src/deployment/queue.rs, deployer/src/deployment/state_change_layer.rs, deployer/src/lib.rs, deployer/src/main.rs
Deployer handles now gracefully connection failure to builder.
Tested locally.
=> fix(deployer): handle gracefully builder connection failure

Cargo.lock, Cargo.toml, builder/Cargo.toml, builder/src/lib.rs, service/Cargo.toml
Utilize `os_pipe` to both capture stdout and stderr of `nix build` command.
In progress.
=> feat(builder): improve the nix build capturing of stdout/stderr

Cargo.lock, Cargo.toml, gateway/Cargo.toml, orchestrator/Cargo.toml, orchestrator/src/lib.rs
This PR simply creates a new library in the workspace called `shuttle-orchestrator`.
Let me know if anything else is needed.
`cargo build`
=> feat(orchestrator): initialize shuttle-orchestrator as a library

.github/pull_request_template.md, Cargo.lock, Containerfile, Makefile, cargo-shuttle/Cargo.toml, cargo-shuttle/src/init.rs, cargo-shuttle/src/lib.rs, logger/src/dal.rs, runtime/src/alpha/args.rs
- Use higher level of gzip compression, so that more files can squeeze into the deployment request.
- Update code for modifying config files after a cargo shuttle init.
- Bump deps.
- `make cargo-clean` for deep cleaning target directories.
Tested all changed code paths locally.
=> feat(cargo-shuttle): better compression & handling of config files after init

DEVELOPING.md, deployer/src/args.rs, docker-compose.dev.yml
The auth service started locally should have the same name as the one found in `docker-compose.yml` for a successful merge between dev and 'prod' compose files.
Did a `make up`, a `project stop/start` and `deploy`.
=> fix(docker-compose.dev): adjust auth dev dependency

Cargo.lock, cargo-shuttle/Cargo.toml, cargo-shuttle/src/init.rs, cargo-shuttle/src/lib.rs, cargo-shuttle/tests/integration/init.rs, cargo-shuttle/tests/resources/copyable-project/Cargo.toml, cargo-shuttle/tests/resources/copyable-project/src/main.rs
`cargo-generate` has been removed as a dependency of `cargo-shuttle`, and all functionality of `cargo-shuttle` that was used by the `cargo shuttle init` command has been re-implemented.
The `openssl` dependency introduced by cloning the template Git repositories using the `git2` crate has also been removed. Instead, `gix` is used to clone repositories, which uses `rustls`.
Closes #1269
/claim #1269
The applicable tests have been updated where required. Additional tests have been added to ensure that the new parsing-logic accepts many relevant examples (e.g. those in [the `shuttle-examples` README](https://github.com/shuttle-hq/shuttle-examples#how-to-clone-run-and-deploy-an-example). Also, some previously ignored tests now pass.
=> refactor(cargo-shuttle): remove `cargo-generate` dependency

Containerfile
Allows shuttle to start in docker on M1 Pro MacBooks, there might be additional change needed for other Apple CPUs, I have no way to test.
This change achieves this by adding the `TARGETPLATFORM` value used by Docker on the mentioned MacBook to the list of platforms for which an arm64 version of the `ulid0.so` should be used.
Before this change gateway container wouldn't start on an M1 Pro MacBook during the `make up` step of the [running-locally](https://github.com/shuttle-hq/shuttle/blob/main/DEVELOPING.md#running-locally) guide, now it does.
I was able to successfully deploy an example locally after the change.
=> fix: gateway container startup on apple m1

.circleci/config.yml, Cargo.lock, deployer/src/deployment/queue.rs, service/src/builder.rs
- unstable is no longer part of the ci job
- makes approving/cancelling/rerunning unstable job much cleaner
- less filters for jobs that already depend on filters
- faster
Works with and without the filter commented
=> ci: separate ci and unstable jobs, better caching

cargo-shuttle/src/args.rs, cargo-shuttle/src/client.rs, cargo-shuttle/src/config.rs, cargo-shuttle/src/lib.rs, cargo-shuttle/tests/integration/init.rs, common/src/models/error.rs, common/src/models/project.rs, gateway/src/api/latest.rs, gateway/src/service.rs
What still remains:
- *Should we allow user to use the name even though it is taken? Prompt y/n for the rename?*
- It's a bit tricky and not a killer. Using `--name` gets you around this check.
Bonus:
All 3 scenarios tested locally
Updated tests
=> feat(cargo-shuttle): check project name available

deployer/prepare.sh
!! Wait until #1247 before merging this, mold is not in Debian 10's apt.
- Add lld and mold linkers, for people that want to use them (#1000)
Let ppl test it in production :tf:
=> feat: add lld and mold linkers

deployer/src/deployment/run.rs, deployer/src/runtime_manager.rs, proto/src/lib.rs
* Handled errors around runtime unexpected behavior by logging the errors and killing the runtime process.
When user services are CPU bound the runtime logs stream handled by the deployer can break with a broken pipe error (I haven't confirmed the root cause yet because it is not that straightforward - big stack based on tonic, hyper, and h2, but I expect it to happen because the runtime becomes CPU bound and it can not respond in time to the client keep-alive messages, which will be followed by closing the corresponding end of the tonic channel), exiting the `run` task with panic.
N/A
=> fix(deployer): added runtime error handling

install.sh
This PR adds the installer script for easily installing `cargo-shuttle` on different platforms.
Currently, it supports:
- Native installation on Arch Linux (and derivaties) via `pacman`
- Installing via `cargo-binstall` (if `cargo-binstall` is installed)
- Installing pre-built binaries from GitHub (only Linux/MacOS for now)
- Installing directly via `cargo install` (installs `cargo` via `rustup` if it is not found)
On my local machine by running `./install.sh`
We need to test this on MacOS as well.
=> feat(installer): add installer script

README.md, cargo-shuttle/README.md, cargo-shuttle/src/lib.rs, runtime/src/lib.rs
=> docs: add installer script option

.circleci/config.yml, Containerfile
The gateway container uses curl for health checks.
Tested by deploying to staging with the https://github.com/shuttle-hq/shuttle/pull/1262 commit dropped, as it was causing other problems.
=> fix(gateway): install curl for health checks

cargo-shuttle/src/args.rs
See https://docs.rs/clap/latest/clap/struct.Command.html#method.debug_assert
`cargo test -- "test_shuttle_args"`
=> test(cargo-shuttle): add debug assertion for command-line arguments

.circleci/config.yml
The xlarge machine is 5x more expensive than large, and cargo-shuttle barely utilized its resources, so downgrading to see its performance. The other two use even less.
All of them use much less sccache after the docker split of jobs, checking if this is enough.
=> ci: use smaller machines for docker tests

.editorconfig
Add indentation settings for shell scripts (e.g. for `install.sh`)
I ran `editorconfig-checker` locally.
=> chore(editorconfig): add indentation settings for shell scripts

cargo-shuttle/src/lib.rs
`cargo-shuttle` init was not authorizing the client in the event that the api-key was already set in the config. It was also the case that if passing certain args, the interactive flow was disabled, which meant if the user wasn't logged in and didn't pass --api-key in the command, they would get an error about trying to login but failing. I fixed that too, but it does mean the path prompt will be interactive even if given. The init logic is quite complicated, so I'm very open to suggestions here.
Tested running `cargo run -p cargo-shuttle -- --wd ./  init --from https://github.com/shuttle-hq/eurorust-demo --name unique-name --create-env
./unique-name` when logged in with config file, with --api-key, and neither.
=> fix(cargo-shuttle): fix init login bugs

cargo-shuttle/src/provisioner_server.rs
Fixes a bug where running a project with the shared DB for the first time could result in a failure to connect, which could be fixed simply by running it again.
The connection attempt is made too quickly (some would say it's blazingly fast) and the Postgres database doesn't have the time to start accepting connection. A simple wait is enough.
With the Eurorust demo, 2nd step, and simply doing `cargo shuttle run`. I'm using Podman, and I can consistently hit the bug simply by removing the running PSQL container and trying again.
=> fix(resources/shared-db): retry initial connection a few times

Cargo.lock, cargo-shuttle/Cargo.toml
Update packages to remove several `cargo audit` issues. There is only one left with `wasmtime`, but the current version constraint is 7.0.0 while the last one is 13, and I need more time to check this one. Went through the updates done to the lockfile, there doesn't seem to be any breaking change we care about.
=> build: update dependencies

deployer/src/error.rs
The deployment tests failed error message lacks some clarity about it being the users tests that failed. It will be clear if the tests run and fail, since the output will be displayed, but if the tests fail to compile due to a missing native dependency the error won't be clear. I also added a hint about how you can re-run with --no-test.
Tested with a local environment and a an axum service with failing tests.
=> refactor(deployer): improve deployment test failure msg

resources/turso/Cargo.toml
Unpinned the libsql-client in the Shuttle Turso crate and bumped it to version 0.32.0, per issue #1324 
Ran unit tests from within the Shuttle Turso crate, tests were all green.
=> improvement: unpin libsql-client, bump to v0.32.0

cargo-shuttle/src/args.rs, cargo-shuttle/src/lib.rs, common/src/models/deployment.rs, common/src/models/project.rs, common/src/models/resource.rs, common/src/models/secret.rs
- Closes #1315 by adding `--raw` flag to `deployment list` and `project list` commands, as well as `resource list` and `secrets`
- Closes #962 by removing colouring from `impl Display` for `Project::State`
- Functions `get_table` in two locations renamed to `get_projects_table`/`get_secrets_table` to match naming of `get_deployments_table`
- New `raw` table format ignores terminal width and has no borders
- Project state returns `&str` like Deployment state, `impl Display` for state has no styling, styling done at call site when appropriate
- Commands `--raw` flag do not output styled messages when flag is used
The following commands were run, inspecting the output manually: (nano is a project I have running)
- `cargo run --bin cargo-shuttle -- --api-url https://api.shuttle.rs deployment …
=> feat(cargo-shuttle): raw table output, fix table column alignment

logger/src/dal.rs, logger/src/lib.rs
This adds the instrumentation required to track the broadcast queue size warnings happening in the tokio task spawned in `dal::Postgres::from_pool`. 
I set up a trigger in HoneyComb (not in the production environment yet), it will trigger if the count of warning events is >= 10 within a 5 minute duration, and the query is ran every 5 minutes. I am still not set on the numbers here, we may have some false alerts during high load peaks, but I think we can start with this and then fine-tune it. 
For some context, the `warn` event will be triggered when the database receiver queue is >= 200. The database receiver queue will start growing if it cannot write the received logs faster than they are coming in. So it may fill up a bit during spikes (or if the database has problems), but it will …
=> feat(logger): add instrumentation needed for alert

runtime/src/alpha/mod.rs, service/src/error.rs
Make errors from resources failing to provision visible to the users. In the past we would just show a message of:
```
loading service failed: failed to provision shuttle_turso :: Turso
```
And this was not very helpful. Now it shows:
```
loading service failed: failed to provision shuttle_turso :: Turso: Unknown scheme: file. Make sure your backend exists and is enabled with its feature flag
```
Using the local runner
=> bug: resource provisioning errors not showing

codegen/src/shuttle_main/mod.rs
Fixes compiling failing when using secrets after #925 
By using `cargo check` on a project that uses secrets inside a resource config
=> bug: compile fails with secrets in resource configs

codegen/src/shuttle_main/mod.rs, runtime/src/alpha/mod.rs, runtime/src/bin/shuttle-next.rs, runtime/src/lib.rs, runtime/src/resource_tracker.rs, services/shuttle-poise/src/lib.rs
*finally a well isolated PR...*
- Move internals into hidden module, which hides them from the cargo doc page (docs.rs).
- Re-export tokio, allows user code to not have tokio in Cargo.toml, unless they need it for something ofc :)
=> refactor(runtime): hide internals from public-facing API, export tokio

cargo-shuttle/Cargo.toml
Should allow cargo to deny the install if outdated.
TODO: eventually add CI for checking this when we care more about it.
ref: https://github.com/shuttle-hq/shuttle-docs/pull/210
Installing with 1.69 fails, 1.70 works :heavy_check_mark:
=> feat(cargo-shuttle): state MSRV in Cargo.toml

resources/turso/Cargo.toml
The latest version of Turso fails to compile. So reverting it back to the last working version.
More details are on libsql/libsql-client-rs#52.
Using the local runner
=> bug: revert turso version update

deployer/src/persistence/mod.rs
This ensures that when deleting the secrets resource, the secrets are also deleted from the deployer persistence secrets table.
I still want to explore whether secrets should still be persisted in the deployer, and perhaps if secrets should be deletable by key, but that's for a future PR.
I first reproduced the bug locally by: deploying with secrets, deleting secrets and removing Secrets.toml, re-deploying and secrets returned.
After my change, this was no longer the case, secrets remained deleted on re-deploy.
=> feat(deployer): delete secrets from deployer persistence on secrets resource delete

cargo-shuttle/src/lib.rs, common/src/models/deployment.rs, common/src/models/project.rs
Adds adaptive page hints to cargo-shuttle by adding 1 to the specified limit and checking if we reach that adjusted limit. This is not breaking as it requires no API changes and is just a small change to client-side logic. Only thing worth mentioning is technically you can only specify a limit up `u32::MAX - 1` because we always adjust the limit to be `limit + 1` however I cannot really see a case where someone would ever need that high of a limit so it is basically irrelevant.
Closes issue #1316 
Also can close my other 2 PRs #1334 and #1320 as this resolves all the issues addressed in those.
Tested with local setup
=> feat: adapative page hints (client-side only)

Cargo.lock, Cargo.toml, builder/Cargo.toml, cargo-shuttle/Cargo.toml, cargo-shuttle/src/args.rs, cargo-shuttle/src/lib.rs, deployer/Cargo.toml, deployer/src/deployment/queue.rs, deployer/src/error.rs, deployer/src/handlers/mod.rs, deployer/src/persistence/error.rs, deployer/src/persistence/mod.rs, runtime/Cargo.toml, runtime/tests/integration/helpers.rs, service/Cargo.toml, service/src/builder.rs, service/tests/integration/build_crate.rs
Fixes #1322 and some more
- Using blocking crossbeam channels was causing logs to be delayed. Switched over to tokio channels everywhere possible.
- Initial logs from deployment now appear instantly, and one line is printed if the fetching takes time.
- Do a manual cargo fetch when building, and don't let metadata commands fetch. (this is causing CI fail, will look for compromise.)
Local run works as usual, with and without crates cached.
Deployment works for axum hello world with and without --no-test, with and without failing test.
=> fix(deployer): handle cargo fetch without blocking logs, use async channels

cargo-shuttle/src/lib.rs, common/src/models/error.rs
Additional context when project is not ready on delete command.
See image above
=> feat: suggest project restart when trying to delete

Cargo.lock, Cargo.toml, cargo-shuttle/Cargo.toml, cargo-shuttle/src/lib.rs, common/Cargo.toml, common/src/constants.rs, common/src/lib.rs, common/src/models/resource.rs, proto/src/lib.rs
- resource list with show secrets now shows correct hostname
- a db url coming from c-s local provisioner is now shown
- if local_uri is a valid URL, its password is now hidden at runtime
- Checking for the runtime's version now errors if the check fails, for instance if the binary is not using shuttle-runtime or if the cargo config targets the wrong binary.
Tested all of the above on local projects
=> fix: database uri password hiding, runtime version check

cargo-shuttle/README.md
I packaged `cargo-shuttle` for [Alpine Linux](https://alpinelinux.org/): https://pkgs.alpinelinux.org/packages?name=cargo-shuttle
This PR simply updates README.md about installation instructions.
N/a
=> docs(readme): add instructions for installing on Alpine Linux

.gitignore, admin/src/args.rs, admin/src/client.rs, common/src/models/admin.rs, common/src/models/error.rs, common/src/models/mod.rs, common/src/models/project.rs, gateway/src/api/latest.rs, gateway/src/lib.rs
admin compiles, the rest should be non-breaking
=> refactor: make admin compile, scope project models to backends

cargo-shuttle/Cargo.toml
`cargo-shuttle` failed to publish with `shuttle-common-tests` as a workspace dependency.
Tested cargo publish with --dry-run, then published the crate on this branch.
=> fix(cargo-shuttle): revert shuttle-common-tests to path dep

services/shuttle-rocket/Cargo.toml
Bumped rocket to version 0.5.0-rc.4 in the dependencies section of Cargo.toml, under /services/shuttle-rocket. I studied the list of breaking changes and they don't appear to impact implementation of the Shuttle Service trait for Rocket.
There don't seem to be any integration tests within the services crate for shuttle-rocket.  There also doesn't seem to be any unit tests. I ran `make test` from the root of my repo, but the tests seemed to fail and I don't quite understand why. Doing a trial PR to trigger CI and see what I get.
=> improvement: rocket 0.5.0-rc.4

gateway/src/service.rs
This should only fix the lowercase Ulid issue, but not the duplicate insertion.
Not at all yet.
=> fix(gateway): use project_id argument when inserting project

.circleci/config.yml, auth/src/api/handlers.rs, auth/src/lib.rs, auth/src/main.rs, auth/src/user.rs, auth/tests/api/auth.rs, auth/tests/api/helpers.rs, auth/tests/api/session.rs, common-tests/src/lib.rs, common/Cargo.toml, common/src/backends/auth.rs, common/src/claims.rs, common/src/lib.rs, common/src/limits.rs, gateway/src/api/latest.rs, gateway/src/lib.rs, gateway/src/service.rs
Add a `Limits` struct that will hold all the account limits to the JWT `Claim`, and also add the `AccountTier` (moved to shuttle-common) to the `Claim`, so we can use it in instrumentation. I left adding it to instrumentation out of this PR, that will be done in a follow-up.
I used an extension trait for the methods to extract the limits from the `Claim`. This allows us to have the methods for extracting limits from the claim only available where they are needed. An alternative would be to implement the methods on Claim directly, or make the fields of `Claim` public, but that would make us more exposed to [breaking changes](https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md#structs). I'm not sure that breaking changes will be an issue here, though, since we create …
=> feat: add limits and tier to jwt claim

gateway/src/api/latest.rs
=> feat(gateway): temporary conditional project limit increase

docker-compose.yml
Use an auth service health-check when deploying the stack.
Locally, by querying the container state before and after the health check addition.
E.g. before the health-check, this `docker inspect --format='{{json .State.Health}}' <container_id>`, returns `null`,  while after adding the healthcheck, it shows something along:
```
{"Status":"healthy","FailingStreak":0,"Log":[{"Start":"2023-11-16T15:10:22.278007509Z","End":"2023-11-16T15:10:22.362298051Z","ExitCode":0,"Output":"  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:-- …
```
=> misc(auth): added service healthcheck

deployer/src/deployment/run.rs, runtime/src/alpha/mod.rs
=> fix: merge new&old secrets in deployer

common/src/models/error.rs, gateway/src/auth.rs, gateway/src/service.rs
Fixes endpoints with ScopedUser that are called with an invalid project name. Returns proper project name error instead of panic. The error is also properly logged instead of a panic printout.
Bonus change: red :red_square: 
Before:
```
cs --name äö project status
Getting project status failed
If getting project status failed repeatedly, please check Shuttle status at https://status.shuttle.rs before contacting the team on the Discord server.
Error: 502 Bad Gateway
Message: response from gateway is invalid. Please create a ticket to report this
```
After:
```
cs --name äö project status
INFO: Targeting non-standard API: http://localhost:8001
Getting project status failed
If getting project status failed repeatedly, please check Shuttle status at https://status.shuttle.rs before contacting …
```
=> fix(gateway): handle invalid project names in ScopedUser

deployer/prepare.sh
Remove the panamax registry override from the deployers. This PR does not remove panamax entirely, we should hold off on that until we are confident in our migration to crates.io.
=> feat: remove panamax registry override from deployers

cargo-shuttle/src/args.rs, cargo-shuttle/src/lib.rs, cargo-shuttle/tests/integration/init.rs
Useful if you are initing a project with a name that you already own.
`--force-name` arg disabled name validation and taken check.
In interactive, "reply" with the same name again to a failed validation to use the name anyways.
All combinations of with/without arg and with/without interactive works as expected.
=>  feat(cargo-shuttle): ability to force a name to be used in init

.gitattributes, cargo-shuttle/src/lib.rs, common/src/models/error.rs, common/src/models/project.rs, service/src/builder.rs
=> fix: better error hints & formatting + nits

services/shuttle-serenity/Cargo.toml
Serenity has entered RC stage for 0.12. We only use their `Client`, and there is no breaking changes in that interface.
Also moved rustls to a default feature to allow native tls.
Having this released ahead of time means that we will support serenity 0.12 from the same moment it is released.
Compiled serenity hello world with 0.11 and their 0.12-rc branch, both worked.
=> feat(shuttle-serenity): support serenity 0.12 and 0.11, optional native tls feature

common/src/backends/auth.rs, common/src/limits.rs, provisioner/src/lib.rs, resource-recorder/src/lib.rs
Adds an `rds_access` field to the `Claim::Limits` struct, which will only be true for pro and team users. This enables us to restrict provisioning of RDS instances to pro/team users.
Tested with local environment, it errors for free users:
```
2023-11-21T16:08:14.944+01:00 [Deployer]  INFO shuttle_deployer::deployment::run: Loading resources
2023-11-21T16:08:14.944+01:00 [Deployer]  INFO shuttle_deployer::persistence: {service_id="01HFS6P6VQWVCPM8S9B9G4SEFF"} Getting resources from resource-recorder
2023-11-21T16:08:14.952+01:00 [Deployer]  INFO shuttle_deployer::persistence: Got no resources from resource-recorder
2023-11-21T16:08:14.953+01:00 [Deployer]  INFO shuttle_deployer::persistence: {resources="Ok([])"} Local resources
2023-11-21T16:08:14.955+01:00 [Runtime] TRACE …
```
=> feat: limit rds access to pro users

docker-compose.yml
CircleCI staging/prod deployment will fail because the `start_period` and `start_interval` configs for `healthcheck` are not handled gracefully when deploying the stack. The deployment will fail due to using a Docker Engine version that does not support the configs.
This PR comments on the configs explaining why, and when we'll upgrade, we can uncomment them.
Releasing on staging for #1402 .
=> auth: comment healthcheck `start_period` & `start_interval`

common/src/resource.rs
We're missing the `Custom` resource type conversion from `str`.
Reproduced when I deployed the `custom-resource/pdo` example.
TODO: test the project deployment again after the fix.
=> fix(common): type conversion from str for a custom resource

Cargo.lock, gateway/Cargo.toml, gateway/src/api/latest.rs, gateway/src/args.rs, gateway/src/lib.rs, gateway/src/project.rs, gateway/src/service.rs, gateway/src/task.rs
Causes the delete command to start up destroyed (stopped) projects to be able to delete them.
By making new gateway tests. Use the following steps to run them
```
USE_PANAMAX=disable make up # To start up the other service on your local environment
SHUTTLE_TESTS_NETWORK=shuttle-dev_user-net cargo test --package shuttle-gateway # to run all the gateway tests
```
If your tests take too long to run and eventually errors with `503` then make sure your firewall is not blocking any requests. See comments in the code.
=> bug: delete a project even if the current state is destroyed

.circleci/config.yml
This fixes the recent [CI errors](https://app.circleci.com/pipelines/github/shuttle-hq/shuttle/5032/workflows/da1d8d48-aabe-446d-87a7-eaf5c709f51b/jobs/119097) caused by serenity needing rust 1.74, and also bumps the rust version used for other jobs and bin builds.
CI passes after the change.
=> ci: bump docker-rust rust version

common/src/models/error.rs, gateway/src/api/latest.rs, gateway/src/lib.rs
Handle an errored project automatically when trying to delete it.
By adding new tests
=> refactor: delete errored projects

gateway/src/api/latest.rs
Old CLIs will still try to do a dry run. This PR makes sure that we ignore that request gracefully.
Na
=> bug: don't do anything on delete dry run

gateway/src/api/latest.rs
=> feat(gateway): override idle timer for cch projects

cargo-shuttle/src/args.rs, cargo-shuttle/src/lib.rs, common/src/log.rs
--raw does not display timestamp or log origin. Makes the logs a lot clearer if needed for parsing in some way.
Tested against prod (client change only)
=> feat(cargo-shuttle): --raw flag on logs

gateway/src/api/latest.rs, gateway/src/lib.rs
We already suspected that delete works for stopped projects. This test confirms that.
Added new test
=> tests: confirm that stopped projects delete successfully

cargo-shuttle/src/lib.rs
I found on my machine running `cargo shuttle run` on the latest version i was getting a time out as described in #1436 and not allowing me to run my project. After finding the location of the error and moving it up from a timeout of `500` to `1000` my project runs and the check passes. Open to any suggestions on possible chnages to PR or issue. Thank you!
Verfied the timeout resolved my issule and the project could run after the change
=> fix(cargo-shuttle): increase runtime version check timeout

services/shuttle-serenity/Cargo.toml, services/shuttle-serenity/src/lib.rs
tested a newly inited serenity project with patches against this, both with (default + serenity0.11) and with (no default + flag + serenity0.12)
CI fails due to features being mutually exclusive. Can be fixed later.
=> fix(shuttle-serenity): support serenity 0.12 through feature flag

common/src/models/error.rs, common/src/models/project.rs, gateway/src/api/latest.rs, gateway/src/args.rs, gateway/src/lib.rs, gateway/src/main.rs, gateway/src/service.rs
Stop the creation of new cch projects or the starting of idle cch projects when we are close to hitting our active container limits.
By adding new tests
=> feat: protect ourselves from going over the 1k limit

common/src/backends/auth.rs
While implementing the hard limits I could not figure out why the test kept failing for a pro user. After some debuging I fount that gateway did not think the API request was coming from a pro user. I thought the claim serialization / deserialization might be wrong. So I added a test to confirm this.
That was not the issue, but this test is helpful none the less. Hence, this PR.
This is a test :smile:
=> test: add an extra property claim test for pro users

gateway/src/api/latest.rs, gateway/src/args.rs, gateway/src/lib.rs, gateway/src/service.rs
Prevent the creation of new projects or the starting of idle projects that will overload our servers
Updating the tests
=> feat: protect pro tier projects and our services

.circleci/config.yml, admin/src/args.rs, admin/src/client.rs, admin/src/main.rs, gateway/src/api/latest.rs, gateway/src/project.rs, gateway/src/service.rs
Add an admin endpoint to forcefully idle cch projects, so we can idle projects that are not correctly idled by the ambulance task.
TODO
=> feat(gateway): add cch projects idle admin endpoint

gateway/src/task.rs
See saw a lot of the below calls that we suspect overloaded Docker yesterday (meaning about 1k happening in less that a second for the same container). So this causes us to backoff a bit between Docker calls
https://github.com/shuttle-hq/shuttle/blob/23ba41b197a8a8d1ff8a2d80494577cf601501bf/gateway/src/project.rs#L508
Local run
=> feat: don't overload docker with requests

gateway/src/task.rs
Just reduce the backoff so that we don't wait forever
Na
=> refactor: reduce backoff

gateway/src/main.rs, gateway/src/service.rs
We just do nothing for all the other dead end states anyway. And for the intermediate states, the tasks that started them will drive them to completion anyway.
=> refactor: only ambulance ready projects

.circleci/config.yml, services/shuttle-axum/README.md, services/shuttle-serenity/Cargo.toml, services/shuttle-serenity/README.md
With Axum 0.7 and Serenity 0.12 the pipeline has been failing a couple of checks. Hopefully, this resolves them by breaking them into a feature check for each feature. I was not sure about adding rustls_backend to the serenity cargo.toml, Was the only way I could get the check to pass. I could not figure out how to pass two to the -F/--feature flag.
Made sure the commands generated by the pipeline pass.
=> ci: fix tests with axum and serenity feature flags

common/src/backends/tracing.rs, extras/otel/otel-collector-config.yaml
The issue was that previously I was setting it as an attribute instead of a resource (i.e. a tag in Datadog naming convention). Attributes are at the event levelt, while resources are at the service/host level.
Locally, and it works.
=> fix(optl): correctly set deployment.environment resource

cargo-shuttle/src/args.rs, cargo-shuttle/src/lib.rs
Allow to skip confirmation for deleting projects.
=> feat(cargo-shuttle): add --no-confirmation flag to project deletion

cargo-shuttle/src/args.rs, cargo-shuttle/src/lib.rs
Nice to have before the feature is released.
checked that help pages are printed correctly
=> feat(cargo-shuttle): change no_confirmation flag to -y/--yes, add it to resource delete

gateway/src/service.rs, gateway/src/task.rs, gateway/src/worker.rs
Removes a bunch of unused generics in the state machine so that it is easier to reason about it. It will be best to review this on a per commit basis
Clippy is still happy
=> refactor: remove generics

.cargo/audit.toml, Cargo.lock
This PR removes updates our dependencies using `cargo update`, this resolves one of the cargo warnings, with pertains to the yanked wasm-bindegen version 0.2.88. 
The other warning is for https://rustsec.org/advisories/RUSTSEC-2023-0071.html, which is pulled in by `sqlx/mysql`, which we don't use, but it is pulled in due to a bug in cargo, see https://github.com/launchbadge/sqlx/issues/2911 and https://github.com/rust-lang/cargo/issues/10801. We should be safe to ignore the warning for `rsa`. A fix for the vulnerability is also [underway](https://github.com/RustCrypto/RSA/pull/394), but we'd need to wait for it to be finished and pulled into `sqlx`. I am following the `rsa` PR, so I will be notified when it is merged, we can then remove this ignore (when `sqlx` updates their `rsa` …
=> fix: cargo audit failures

resource-recorder/tests/integration.rs
This should resolve these spurious ci failures: https://app.circleci.com/pipelines/github/shuttle-hq/shuttle/5230/workflows/98babb6a-6d17-4fd8-87c6-2bb78d23e754/jobs/125877
Locally and in CI.
=> tests(resource-recorder): allow server time to start

.circleci/config.yml, provisioner/src/lib.rs
A call should not be mad to provision a database that already exists, but this may change in the future, so I added a safe-guard to ensure only new RDS instances will be deleted if the subscription update fails.
Tested on staging, a new instance still has its subscription updated as expected.
=> fix(provisioner): only delete new rds on failed subscription update

Cargo.lock
Bump `zerocopy` to fix audit failure, for context see https://github.com/google/zerocopy/issues/716 and https://rustsec.org/advisories/RUSTSEC-2023-0074.html
CI.
=> chore: bump zerocopy

gateway/src/args.rs, gateway/src/lib.rs, gateway/src/main.rs, gateway/src/service.rs
Gateway is unable to start the last deploy when starting idle / stopped projects because it is not getting a JWT from auth. The reason it is not getting a JWT from auth is because auth expects an admin key to be present since #1487 and we missed plugging this flow too :see_no_evil: 
Using the local runner
=> bug: missing gateway key when trying to get jwt

service/src/builder.rs, service/src/runner.rs
Allows collecting traces for analysis of which shuttle crates are being used. Includes semver requirement. Example:
```
2023-12-28T02:07:02.747609Z  INFO shuttle_service::builder: Compiled workspace member with shuttle dependencies name="hello-world" deps=["shuttle-axum '^0.35.0, >=0.34.0'", "shuttle-runtime '^0.35.0'"]
```
Local run with RUST_LOG produced the above.
=> feat(service): emit trace with shuttle dependencies

cargo-shuttle/src/args.rs, cargo-shuttle/src/init.rs, cargo-shuttle/src/lib.rs
- Added a new property in `InitArgs` struct. 
- Used that new property value and passed to the `generate_project` function
- changed init.rs file so that `--no-git` flag can work
Closes #1497 
> I haven't tested this yet, I just wanted to know if gist of this code looks good or do i need to change anything.
=> feat: `--no-git` to `cargo shuttle init`

README.md, install.ps1
Adds Powershell script, following steps as in bash install script, closes #1496.
Install command added to readme will work once shuttle-hq/www#220 is merged.
Tested locally on multiple machines, including commenting out codepaths to check both sides of branches. The section for downloading a binary may need to be updated in the future if CI is updated to produce aarch64 windows binaries.
=> feat(installer): add windows installer script

.circleci/config.yml, cargo-shuttle/tests/resources/archiving/Cargo.toml, runtime/src/lib.rs, service/tests/resources/is-bin/Cargo.toml, service/tests/resources/not-shuttle/Cargo.toml, service/tests/resources/workspace/alpha/Cargo.toml, services/shuttle-axum/Cargo.toml, services/shuttle-axum/README.md, services/shuttle-axum/src/lib.rs
Merge with https://github.com/shuttle-hq/shuttle-examples/pull/123
Tested both configurations locally
=> chore(shuttle-axum): use axum 0.7 by default

gateway/src/api/latest.rs, gateway/src/service.rs
Simplified the `renew_gateway` handler, and returned more info to differentiate between renewing the gateway vs not renewing it because there are more than 30 days of validity, which means we can wait for a little longer until we renew the certificate.
N/A
=> refactor(gateway): renew gateway certificate returns more info about success

gateway/migrations/0006_uppercase_ulid.sql
Worked locally on two dummy rows.
Needs to test on unstable.
=> fix(gateway): uppercase old ulids

deployer/src/deployment/run.rs, deployer/src/persistence/mod.rs, deployer/src/proxy.rs, gateway/src/api/latest.rs, gateway/src/api/mod.rs, gateway/src/api/tracing.rs, gateway/src/project.rs
Two commits for two changes:
1. For the `gateway`, any call to a route that has `:project` in it will now add to the current span `shuttle.project.name`. This isn't perfect, ideally we would want to set it to every child span as well, but this is already an improvement.
2. Update several places where we set `shuttle.service.name`, but not `shuttle.project.name`. I could have dropped `shuttle.service.name` since we're not really using the concept of a service, but that's fine for now.
Updated the otel-collector to send trace to a local `jaeger` instance instead of DD/HC, and the attribute showed up as expected :)
=> Traces: set shuttle.project.name in more places

gateway/src/proxy.rs
Prevents the `Some(foo.bar)` in Datadog attributes.
Not tested.
=> fix(proxy): record http.host after parsing to avoid Some(..) in the attr

.circleci/config.yml, Containerfile, Makefile, common/src/backends/tracing.rs
This goal is to enable Datadog to track versions, deployments, and to
be able to automatically detected regressions or new bug associated with
a version.
Locally, with Datadog configured in the `local` environment.
=> Traces add shuttle version

.circleci/config.yml
Current image is being deprecated this year. Replacing it with `default` which uses latest ubuntu, as recommended here https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177
Works for the ci runs
=> ci: use default ubuntu machine image

.circleci/config.yml, codegen/src/shuttle_main/mod.rs, common/src/lib.rs, common/src/models/resource.rs, proto/src/lib.rs, resources/README.md, resources/aws-rds/Cargo.toml, resources/aws-rds/src/lib.rs, resources/metadata/src/lib.rs, resources/persist/src/lib.rs, resources/secrets/Cargo.toml, resources/secrets/src/lib.rs, resources/shared-db/Cargo.toml, resources/shared-db/README.md, resources/shared-db/src/mongo.rs, resources/shared-db/src/postgres.rs, resources/turso/src/lib.rs, runtime/src/lib.rs, runtime/src/provisioner_factory.rs, runtime/src/resource_tracker.rs, service/Cargo.toml, service/src/lib.rs, services/shuttle-poem/Cargo.toml
Supersedes #1515
Main function arg's type declaration determine which type is returned from a resource, allowing DB plugins to return the connection string.
BREAKING: Postgres projects with the sqlx connector need to add a feature flag to keep the same behaviour. Also breaking changes in the public API of shuttle-service.
TODO:
All examples build with the PR above
=> feat(resources)!: get db connection string from resources, refactor ResourceBuilder

Cargo.lock, auth/Cargo.toml, auth/migrations/0001_sync_updated_at.sql, auth/migrations/0002_subscriptions.sql, auth/src/lib.rs, auth/src/user.rs, auth/tests/api/users.rs, common/src/limits.rs
Add a subscriptions table to auth to support multiple types of subscriptions, and update the claim limits with an rds quota.
Existing tests pass without modification, but new tests will be needed as we add functionality to add more than a pro subscription.
=> feat(auth): add subscriptions table to auth, add rds quota to claim limits

Cargo.lock, Cargo.toml, common-tests/Cargo.toml, common-tests/src/gateway.rs
PR to resolve the current cargo audit failure. We should wait a bit and see if wiremock 0.6 is fully released before merging this. We could also move wiremock out of the workspace dependencies and keep using 0.5 for now.
CI, and I ran tests that use wiremock locally.
=> chore: update wiremock to resolve cargo audit

cargo-shuttle/src/lib.rs
Hey there! This change just adds a copy-paste friendly command for when the
shuttle runtime is out of date. It looks something like `cargo add shuttle-runtime@{version}`.
This lets the user quickly copy-paste the given line, instead of having to
manually edit `Cargo.toml`. Note that if the user is using other shuttle
crates (ie `shuttle-aws-rds`, `shuttle-rocket`, etc), this copy-paste line will
_not_ update those, and the user _will_ have to update them by manually editing
`Cargo.toml`. I didn't add `shuttle-*` crates to the `cargo update`
command, because that would install every crate, even if the user isn't using
them.
Maybe someone on the team knows if it's easy enough to tell which `shuttle-*`
crates a project is using, and then we can amend the command to explicitly
include those …
=> Improve shuttle-runtime out-of-date hint

.circleci/config.yml, services/shuttle-poise/Cargo.toml, services/shuttle-poise/README.md, services/shuttle-poise/src/lib.rs, services/shuttle-serenity/Cargo.toml, services/shuttle-serenity/README.md, services/shuttle-serenity/src/lib.rs
- Adds `poise` and `poise-0-6` feature flags, with `poise` enabled by default
- Note similar to `shuttle-serenity` added to readme
- `cargo clippy`
- `cargo clippy --no-default-features -F poise-0-6`
=> feat(shuttle-serenity): make serenity 0.12 default, support poise 0.6, deprecate shuttle-poise

gateway/src/api/latest.rs
Change `scope` field for route_project to shuttle.project.name, to match our convention.
Not tested, but the same is done here: <https://github.com/shuttle-hq/shuttle/blob/main/gateway/src/api/latest.rs#L316>, and that works as expected in Datadog.
=> fix(gateway): rename scope field to shuttle.project.name

extras/otel/otel-collector-config.yaml
We're seeing messages of "Payload in channel full. Dropped 1 payload.", which indicates that we should increase the size of the buffer. The default is 10, the value of 25 is arbitrary, we'll see how it goes.
=> fix(otel): increase trace_buffer for dd exporter

Cargo.lock, Cargo.toml, common/Cargo.toml, common/src/database.rs, common/src/deployment.rs, common/src/lib.rs, common/src/log.rs, common/src/models/admin.rs, common/src/models/deployment.rs, common/src/models/project.rs, common/src/models/service.rs, common/src/models/stats.rs, common/src/resource.rs, deployer/Cargo.toml, deployer/src/handlers/error.rs, deployer/src/handlers/mod.rs, deployer/src/persistence/deployment.rs, deployer/src/persistence/state.rs, gateway/Cargo.toml, gateway/src/api/latest.rs
These docs were not being actively used and they make the code harder to work with.
To help Console development we should instead add `typeshare` soon. I've tried it on a different project and it should work well.
=> chore: remove utopia openAPI docs

resources/turso/README.md
Minor documentation changes to go along with #1531. I had forgotten to add them there.
=> docs(shuttle-libsql): update docs for turso libsql change

gateway/src/service.rs, gateway/src/task.rs
Each new project task gets created in the context of a parent span. With open telemetry, this boils down to spans linked through context propagation, which can be easily visualized with Datadog in APM Traces. What is difficult though is to filter spans based on the relationship between them (which should get easier after the GA of [1], thanks @Kazy for pointing me to the article), so that only a certain selection of spans can be returned and counted for certain metrics.
In my specific case, I want to filter for all spans created by the `poll` function of a `ProjectTask` that has an attribute called `ctx.operation_name`. This attribute is attached to the span only in case the result of the `poll` function is `TaskResult::Done(_)`. This is relevant because `ProjectTask`s are created and …
=> gateway: add operation_name field for task polling

common/src/models/error.rs, gateway/src/service.rs
If 20 cch23 projects are active, all traffic to all cch23 projects is blocked. They will then proceed to start idling (still 5 minutes).
This is not a perfect solution (everyone get locked out), but this limit should be hard to reach anyways, and it should quickly recover.
Tested that admin can still excede the limit, and a normal user can not access the projects when the limit is reached.
lmk if a unit test must be written
=> feat: limit concurrent active cch23 projects

cargo-shuttle/src/init.rs, cargo-shuttle/tests/integration/init.rs
cloning a workspace template incorrectly set a package name in the workspace manifest.
bonus fix: never copy target dirs from local templates (I wasted 150 GB disk space when testing :skull: )
added a test
=> fix(cargo-shuttle): set name in Shuttle.toml when cloning a workspace

Containerfile, Makefile, deployer/src/main.rs, docker-compose.yml
Builder will be rewritten, so having this version build things is a waste of resources until the new version is ready.
Local stack goes up and deployments go through. Deployers never depended on the builder.
=> chore: disable unused builder service until it is needed

.circleci/config.yml, Makefile, Makefile.toml, proto/README.md, proto/integration.sh
Aims to make the common CI tasks runnable locally, ie `cargo make ci-workspace`.
Also `cargo make proto`, `cargo make changelog 0.x.0`, and `cargo make audit`
CI + local tests
=> wip: use cargo-make for tasks and ci

auth/src/error.rs, common/src/backends/metrics.rs, deployer/src/handlers/error.rs, gateway/src/lib.rs
- We were emitting two events for every 5xx, one from the IntoResponse implementation, which can know more about what the error was, and one from the trace layer [on_failure default implementation](https://docs.rs/tower-http/0.4.4/src/tower_http/trace/on_failure.rs.html#84-100), which only knows the status code (and some metadata).
- We were emitting error events for 4xx in the IntoResponse implementation, but they don't really warrant an error event. Trying to fetch a project that doesn't exist isn't possible, so it's not something we need to highlight as an error. The span will still have the 404 status code.
- With the trace_layer on_failure disabled, we only get the error event in IntoResponse, and we still set the status code on the span so we can track 4xx's.
- With the current …
=> feat: disable trace_layer on_failure, only emit error event for 500s

Cargo.lock, cargo-shuttle/src/lib.rs, common-tests/src/builder.rs, common-tests/src/logger.rs, deployer/src/args.rs, deployer/src/deployment/mod.rs, deployer/src/deployment/queue.rs, deployer/src/deployment/run.rs, deployer/src/deployment/state_change_layer.rs, deployer/src/lib.rs, deployer/src/main.rs, deployer/src/persistence/mod.rs, deployer/src/runtime_manager.rs, proto/Cargo.toml, proto/src/lib.rs, runtime/Cargo.toml, runtime/src/alpha/mod.rs, runtime/src/provisioner_factory.rs, runtime/tests/integration/helpers.rs, service/Cargo.toml, service/src/runner.rs
During the RDS work a pattern was starting for client code to connect to our internal services. This PR extends that pattern to the clients of all our services.
Ie. the client of a service can be found at: `use service_mod::Client`.
And the client can be constructed using `service_mod::get_client().await`.
The compiler is still happy :smile:
=> refactor: uniform client wrappers

.circleci/config.yml, Makefile.toml, auth/integration.sh, auth/integration_docker.sh, builder/integration.sh, cargo-shuttle/integration.sh, cargo-shuttle/integration_docker.sh, deployer/integration.sh, logger/integration_docker.sh, proto/integration.sh, provisioner/integration_docker.sh, resource-recorder/integration.sh, runtime/integration.sh, service/integration.sh
Reduces number of CI jobs 36 -> 30.
The CI cache pruning is a test that will need to run for a while until we see results.
=> ci: move more tasks to cargo make

Makefile, shell.nix
CI (and local development) still uses MSRV (1.75)
=> chore: Rust 1.76

install.sh
Hey 👋 This is my very first contribution that I dared 👉👈
Closes https://github.com/shuttle-hq/shuttle/issues/1603
- `_install_cargo()` function is checking if cargo and rustup are installed in the mid of `_install_unsupported()` whereas it could have been checked earlier to propose better ways of installation. I hope this would make sense and help distinguishing flows better
- checked for syntax mistakes
- ran through chat gpt lol
- ran locally and updated cargo-shuttle
=> feat(installer): always check for cargo install first

.dockerignore, Containerfile
Improves docker cook step slightly. Will look if there is some other win to pick up.
Stack builds
=> misc: use cargo-chef 0.1.64 --bin flags

Makefile, deployer/src/deployment/queue.rs, deployer/src/deployment/run.rs, deployer/src/handlers/mod.rs, deployer/src/lib.rs, deployer/src/persistence/mod.rs, deployer/tests/integration_run.rs, deployer/tests/resources/bind-panic/Cargo.toml, deployer/tests/resources/load-panic/Cargo.toml, deployer/tests/resources/main-panic/Cargo.toml, deployer/tests/resources/sleep-async/Cargo.toml
- Make deployer always start its last running deploy on startup (restart / wakeup) instead of waiting for gateway's request for doing it manually
- Save resources when a service is started with a claim (deployment request with contact with backends), and read it on subsequent wakeups/restarts to not need any backend request.
- Fix incorrect deployment id of 'running' service being returned by `status`
- On staging, no 503/502 was observed on first idle hit against a hello world, (same test gave 502 on prod)
=> feat(deployer): load phase caching, automatic startup

cargo-shuttle/src/args.rs, cargo-shuttle/src/lib.rs, common-tests/src/cargo_shuttle.rs
Allow non-standard secrets file on run and deploy commands.
Added test,
Local run works,
Deploy works
=> feat(cargo-shuttle): `--secrets` arg to use non-default secrets file

cargo-shuttle/src/lib.rs
Replicates #1628 changes for c-s windows
=> fix(cargo-shuttle): windows build

install.ps1
- Changed the algorithm of installation script to following: attempt installing with cargo-binstall, attempt to install rust and cargo, attempt to install with binary, and as a last step to install with cargo
Closes https://github.com/shuttle-hq/shuttle/issues/1603
=> feat(install): change powershell installation script

.circleci/config.yml, common/src/constants.rs, deployer/src/deployment/run.rs, gateway/src/api/latest.rs, gateway/src/api/project_caller.rs, gateway/src/proxy.rs, gateway/src/service.rs
Fixes (?) the `{"message":"Project returned invalid response","status_code":502}` error on the first hit on an idled project by checking the TCP port of the service before proxying the request.
An axum project that had a 2s sleep in the main function was deployed. (2s delay between "ready" and `bind`; simulates slow setup logic or other lag in that phase)
The wakeup proxy hits correctly waited and got 200.
=> fix(gateway): proxy wait for service port to open

.circleci/config.yml, Cargo.lock, auth/Cargo.toml, auth/migrations/0003_user_ids.sql, auth/src/lib.rs, auth/src/user.rs, gateway/migrations/0007_user_ids.sql
First phase to have proper user ids on our backend. This step is needed to be able to correctly link up the user ids in gw's project table.
Running the migrations locally
=> feat: migration for user_id

Cargo.lock, Cargo.toml, common/src/backends/client/gateway.rs, gateway/src/lib.rs, proto/src/lib.rs
Shuttle is using a very outdated version of `test-context`. I am updating it to the last version.
=> chore: update test-context dependency

Cargo.lock, Cargo.toml, cargo-shuttle/Cargo.toml, cargo-shuttle/src/args.rs, cargo-shuttle/src/init.rs, cargo-shuttle/src/lib.rs, cargo-shuttle/tests/integration/init.rs, cargo-shuttle/tests/integration/main.rs, common-tests/src/cargo_shuttle.rs, common/Cargo.toml, common/src/constants.rs, common/src/templates.rs
New flow in the init command that allows browsing the full list of templates.
WIP preview:
updated tests
=> feat(cargo-shuttle): new template system for init

common/src/backends/mod.rs, deployer/src/deployment/run.rs
For now, the resources config are not relevant for the provisioning, so caching based on them is not required.
Furthermore, the way the codegen creates the resource configs in the `loader` is based on the resources input 
builder default implementation, which for databases depends on `DbInput`, which is "{ 'local_uri': null, 'db_name': null }".
Comparing this to the way we store the configs for any resource in resource-recorder: `serde_json::Value::Null`, then
when checking the cache we'll always get a miss given we check for configs equality.
Existing projects must upgrade their deployers to be able to provision RDSs and do subsequent deployments.
On staging, provision database is not called anymore on subsequent deployments once the db was provisioned.
=> fix(deployer): check correct config field(s) in resource cache

Cargo.lock, gateway/Cargo.toml, gateway/src/api/latest.rs
Check the deployer version based on its container inspect response and restart the project before trying to delete it.
We assume it doesn't matter whether the project will be running afterward, or if the deployment will crash, given the
user wants to delete it. What's important is for the deployer to be able to handle the delete request.
N/A
=> gateway: delete project restarts them first if oudated

.circleci/config.yml, deployer/src/handlers/mod.rs
If users' deployments accumulate too many logs that will be fetched in one request our logger/deployer channel will not be able to send/receive all of them at once. This is a current limitation that will be solved by #1629 , by providing the ability to
fetch a partial amount of logs.
Tested on staging.
=> misc(deployer): improve get_logs out_of_range error

Makefile.toml, resources/shared-db/Cargo.toml, resources/shared-db/src/postgres.rs
This is the upstreaming of [`shuttle-diesel-async`](https://github.com/aumetra/shuttle-diesel-async), it adds support to output `diesel-async` resources from `#[shuttle_shared_db::Postgres]`.
Supported resources are:
- `diesel_async::AsyncPgConnection`
- `diesel_async::pooled_connection::bb8::Pool` (for the above mentioned `AsyncPgConnection`)
- `diesel_async::pooled_connection::deadpool::Pool` (for the above mentioned `AsyncPgConnection`)
This is essentially 1:1 the code upstreamed from the repository, the code was used by me in a few projects and has been used by the community as well.
=> feat: Add `diesel-async` support for `shuttle-shared-db`

cargo-shuttle/src/lib.rs, deployer/src/deployment/queue.rs
We look for Secret.toml in the *crate* directory, making placing it in the workspace root a common papercut.
This allows you to do both, with the crate dir taking prio.
Tested with local run and local deployment
=> feat: fall back to finding Secrets.toml in workspace root

logger/src/dal.rs
Added a sleep outside the thread. Project failed to restart during that time.
Added a sleep in the thread. Project restarted successfully during that time.
=> fix(logger): don't block when deleting old logs

Cargo.lock, cargo-shuttle/Cargo.toml, cargo-shuttle/src/client.rs, common/Cargo.toml, common/src/constants.rs
Our APIs should be stable enough where the retry logic is no longer relevant.
Adds a version header that can be used for better version checking later on.
against netcat
=> feat(cargo-shuttle): remove retry client, add version header

.circleci/config.yml
- Makes all internal branches except prod able to approve unstable deploy
- Skips secret-dependant backend tests for forked branches
- internal branch worked for #1697
- testing fork branch here, worked
=> ci: filter jobs based on if PR is from fork

resources/turso/Cargo.toml, resources/turso/src/lib.rs
Fixes https://discord.com/channels/803236282088161321/1219248199588515890/1220612866256801832
Bumps to .1 for a patch release
updated tests
=> fix(shuttle-turso): use open_remote when using local_addr

auth/src/args.rs, auth/src/lib.rs, auth/src/main.rs
Adds a command to auth to allow manual syncing with permit
Tested against Permit testing environment
=> feat: auth sync users with permit

.circleci/config.yml, Cargo.lock, auth/src/args.rs, auth/src/lib.rs, auth/src/main.rs, auth/src/user.rs, auth/tests/api/users.rs, backends/Cargo.toml, backends/src/client/permit.rs, backends/src/test_utils/gateway.rs, backends/tests/integration/main.rs, backends/tests/integration/permit_tests.rs, cargo-shuttle/Cargo.toml, common-tests/src/lib.rs, common-tests/src/permit_pdp.rs, common-tests/src/postgres.rs, common/src/claims.rs, common/src/deployment.rs, deployer/src/handlers/mod.rs, deployer/src/persistence/state.rs, docker-compose.dev.yml, docker-compose.yml, gateway/src/acme.rs, gateway/src/api/latest.rs, gateway/src/lib.rs, gateway/src/main.rs, gateway/src/proxy.rs, gateway/src/service.rs, gateway/src/tls.rs
Adds Permit logic to the project create+delete actions. This will be released without taking control of permission checking to allow a background migration between releases.
Things for upcoming PRs:
- Implement organizations (commented parts) in the permit client + tests
- Command in gateway to trigger a sync of project data
- Let Permit take over the Permission checks in ScopedUser
- Add CORS + update Console
=> feat: generated Permit client, project permission logic

.circleci/config.yml, Cargo.lock, Makefile, auth/src/error.rs, auth/src/lib.rs, backends/src/client/permit.rs, backends/src/test_utils/gateway.rs, backends/tests/integration/permit_tests.rs, common/src/claims.rs, docker-compose.yml, gateway/src/api/latest.rs, gateway/src/args.rs, gateway/src/lib.rs, gateway/src/main.rs, gateway/src/service.rs, runtime/Cargo.toml
Improves the error model from permit and adds a project sync command
Tested against permit's dev env from local stack
=> feat: gateway command to sync permit

docker-compose.yml, gateway/Cargo.toml, gateway/src/api/latest.rs, gateway/src/args.rs, gateway/src/lib.rs, gateway/src/main.rs
Allow the console to call gw directly by adding CORS support to gw and setting the origin as the console.
By starting gw locally and updating a console route to call gw directly
=> feat: CORS support on gateway

backends/src/client/permit.rs, backends/tests/integration/permit_tests.rs, docker-compose.yml, gateway/src/api/latest.rs, gateway/src/auth.rs, gateway/src/project.rs, gateway/src/service.rs, gateway/src/task.rs
Compare project access to Permit project access.
Use Permit for project list.
Remove project list pagination.
Staging
=> feat(gateway): compare permission checks to permit

Cargo.lock
We might be exposed to this attack vector: https://seanmonstar.com/blog/hyper-http2-continuation-flood/. The patches should resolve it (for the most part, we may need to tweak `SETTING_MAX_HEADER_LIST_SIZE`, but the patches are a good start).
CI
=> chore: bump h2 to patch continuation flood vulnerability

gateway/src/auth.rs
We saw no errors in the last 24 hours nor any results different from our old internal checks. So it is safe to switch fully to permit.
The compiler :grin:
=> refactor: only use permit to check project permissions

backends/src/headers.rs, backends/src/lib.rs, backends/src/resource.rs
See ecs-shuttle PR for description of changes.
=> feat: add resource request struct to backends

shell.nix
=> misc: nix shell update

backends/src/client/permit.rs, backends/src/test_utils/gateway.rs, backends/tests/integration/permit_tests.rs, common-tests/src/permit_pdp.rs, common/src/models/error.rs, common/src/models/mod.rs, common/src/models/organization.rs, gateway/src/api/latest.rs, gateway/src/lib.rs, gateway/src/service.rs
Adds basic support for having organizations on Shuttle. Membership to orgs will follow soon.
New tests were added
=> feat: orgs

Cargo.lock, admin/Cargo.toml, admin/src/args.rs, admin/src/client.rs, admin/src/config.rs, admin/src/main.rs, backends/src/client/permit.rs, backends/src/test_utils/gateway.rs, gateway/src/api/latest.rs, gateway/src/lib.rs, gateway/src/service.rs
Admin command to change project owner.
Some improvements to admin internals and permit client errors.
- On local stack with permit dev env
=> feat(admin): change project owner

Cargo.lock, backends/Cargo.toml, backends/src/client/permit.rs, backends/src/test_utils/gateway.rs, backends/tests/integration/permit_tests.rs, common/src/models/organization.rs, gateway/src/api/latest.rs
Allow orgs to have members
New tests were added
=> feat: org members

cargo-shuttle/Cargo.toml, cargo-shuttle/src/args.rs, cargo-shuttle/src/client.rs, cargo-shuttle/src/config.rs, cargo-shuttle/src/lib.rs, cargo-shuttle/tests/integration/main.rs, common-tests/src/cargo_shuttle.rs, common/src/lib.rs, common/src/models/project.rs
=> feat(cargo-shuttle): beta flag, remove project list pagination logic

backends/src/headers.rs, backends/src/resource.rs, common/src/lib.rs
See ecs repo PR for detailed description of changes.
~~This is a draft because I want to see if I can quickly refactor the `DatabaseInfo` struct and methods.~~
We don't need to change DatabaseInfo yet, but we can likely simplify it in the future. I'll make a note of it.
Tested with new provisioner.
=> feat: add models and header for new ecs provisioner

Cargo.lock, runtime/Cargo.toml, runtime/src/alpha.rs
I was taking the kill tx no matter if the condition to kill the runtime was fulfilled, so it was dropped either way when the timeout passed. This could still be done with a oneshot with some changes, but a cancellation token was simpler.
Deployed to my stack, it no longer restarts after the timeout passes.
=> fix: runtime panic

backends/src/project_name.rs
Reverts #1729 since it is too loose now
Tests are green again
=> misc: revert severity level on allowed project names

Cargo.lock, backends/src/client/permit.rs, common/src/models/deployment.rs, common/src/models/error.rs, common/src/models/mod.rs, common/src/models/project.rs, common/src/models/resource.rs, gateway/Cargo.toml, gateway/src/acme.rs, gateway/src/api/latest.rs, gateway/src/api/project_caller.rs, gateway/src/auth.rs, gateway/src/lib.rs, gateway/src/main.rs, gateway/src/project.rs, gateway/src/proxy.rs, gateway/src/service.rs, gateway/src/task.rs, gateway/src/tls.rs, gateway/src/worker.rs
We used to have code that went from `ApiError` -> `ErrorKind` -> `ApiError`. During this conversion to `ErrorKind` we would remove friendly errors which would have been helpful to our end users. So this removes the `ErrorKind` enum.
Instead, each module has its own `Error` know and knows has to convert it to `ApiError` to be as friendly as possible while not exposing sensitive information to users.
With this it is also easier to isolate the proxy errors so they now return a custom `600` error code if the proxy fails
Starting the local stack
=> refactor: errors

backends/src/client/mod.rs
Add a new method to the ServicesApiClient, which is useful in places where we want to set some headers on all requests. The `new_with_bearer` method is similar, but it's specific for bearer auth and it only takes the token. On the new architecture, we want to pass a secret on all requests to the new provisioner, and this new method makes it simpler.
Tested on new platform, CI.
=> feat: add services client constructor for default headers

backends/src/client/gateway.rs, backends/src/client/permit.rs, backends/src/test_utils/gateway.rs, backends/tests/integration/permit_tests.rs, cargo-shuttle/src/client.rs, cargo-shuttle/src/lib.rs, common/src/models/project.rs, docker-compose.dev.yml, gateway/src/api/latest.rs, gateway/src/main.rs
Add more details to projects to know who their owners are
Allow get the details of a single org
And allow only getting projects the user is the direct owner of
Added more tests and started the local stack
=> feat: get project owners and only personal projects

Cargo.lock, cargo-shuttle/Cargo.toml, cargo-shuttle/src/lib.rs, common/src/models/deployment.rs, service/src/builder.rs
=> feat(cargo-shuttle): beta deploy zip file, package name

cargo-shuttle/src/args.rs, cargo-shuttle/src/client.rs, cargo-shuttle/src/lib.rs, common/src/deployment.rs, common/src/models/deployment.rs
Returns the list of all deployments sorted by `updated_at` column.
No pagination yet.
Will handle the ID for `depl_latest` as a reference to the latest running deployment, if any (it is just a partial replacement for `cargo shuttle status` for now).
Locally.  Example cmd:
```
SHUTTLE_BETA=true cargo run -p cargo-shuttle -- --api-url http://iulian-control-alb-fae7fb2-914574683.eu-west-2.elb.amazonaws.com deployment status --wd examples/custom-resource/pdo/ depl_latest
```
Output:
```
Current deployment: 'depl_01HVM1YNS3VR0V5PKKT60Q3277' - running (http://pdo-yvm4dhkducmt.app.iulian.staging.shuttle.rs)
```
=> cargo-shuttle: added beta deployment status 

cargo-shuttle/src/lib.rs, common/src/lib.rs, common/src/log.rs
I know I've pushed against having v1/v2, we'll refactor later, but that's the cleanest way I've found.
=> Add log streaming in beta platform

Cargo.lock, cargo-shuttle/Cargo.toml
gix required a significant bump to resolve the failure, but we're not seeing any breakages in our usage of gix. 
CI.
=> fix: rustls and gix cargo audit failures

backends/src/client/permit.rs, backends/src/test_utils/gateway.rs, backends/tests/integration/permit_tests.rs, cargo-shuttle/src/client.rs, cargo-shuttle/src/lib.rs, common/src/models/error.rs, common/src/models/mod.rs, common/src/models/project.rs, common/src/models/team.rs, gateway/src/api/latest.rs
Renames all references of organizations to teams
The compiler :see_no_evil: and careful manual labour
=> refactor: rename organizations to teams

service/src/builder.rs, service/tests/integration/build_crate.rs
Supersedes https://github.com/shuttle-hq/shuttle/pull/1757
Improves logic for which workspace member(s) that are chosen for building by ignoring crates with no binary target.
Tested on a local example.
Having libs with runtime now works. Having no members with binaries now prints the new error.
=> fix(service): improve workspace member discovery and error

gateway/src/api/latest.rs
This is needed for the coming console updates
The compiler :smile:
=> refactor: return team details when creating a new team

backends/src/test_utils/mod.rs, backends/src/test_utils/provisioner.rs, backends/src/test_utils/resource_recorder.rs, common/src/models/deployment.rs, gateway/src/api/latest.rs, gateway/src/args.rs, gateway/src/lib.rs, gateway/src/project.rs, gateway/src/service.rs, gateway/src/task.rs
Better handling of project delete by completely restarting the container to make sure it has the latest deployer
Using pre-existing tests
=> bug: project delete

docker-compose.dev.yml, docker-compose.yml
Missed updating the docker args in #1762 
Starting a local stack
=> bug: arg for provisioner-uri

logger/tests/integration_tests.rs
Fixes failing test in logger due to broadcast channel being to slow / fast to get the correct logs
CI will be green again
=> tests: fix failing logger tests

.circleci/config.yml, cargo-shuttle/src/lib.rs
Fixes the Windows binaries failing to build
On the CI
=> ci: windows builds

cargo-shuttle/src/args.rs, cargo-shuttle/src/lib.rs, common/src/models/deployment.rs, common/src/models/project.rs
Unifying the raw/fancy versions into one more compact version that does not wrap words in cells.
The raw flag can then be replaced with supporting JSON output.
=> feat(cargo-shuttle): beta compact project and deployment tables

cargo-shuttle/src/client.rs
(Transfer encoding header is not used in HTTP/2)
=> feat(cargo-shuttle): beta deploy endpoint

common/src/claims.rs
Small update to align with the recording of the user id on the new platform
Na
=> refactor: record the correct shuttle.user.id for the new platform

common/Cargo.toml, common/src/models/error.rs, common/src/resource.rs, resource-recorder/src/dal.rs, resource-recorder/src/lib.rs
Improve `ApiError` to make error handling on headroom easier
Na
=> refactor: better errors

cargo-shuttle/src/args.rs, cargo-shuttle/src/client.rs, cargo-shuttle/src/lib.rs, common/src/deployment.rs, common/src/models/deployment.rs
uses fixed /current deployment endpoint for deployment status and logs command.
updates deployment response model with more relevant fields:
- created_at
- URIs is a Vec
- leaving out git metadata to leave room to rethink: it probably belongs in build metadata
=> feat: beta deployment response, current deployment & logs

backends/src/client/permit.rs
Headroom uses the `PermissionDal` behind an `Arc` and needs this
The compiler
=> refactor: implement permission dal when behind an arc

backends/src/client/permit.rs
The impl added in https://github.com/shuttle-hq/shuttle/pull/1784 was recursive, this changes it to call the methods on a reference to the inner value instead.
Deploying test stack with this change.
=> fix: recursive permissionsdal impl

backends/src/resource.rs
Remove a model that was needed on the new platform when the provisioner was an external service.
Tested on my test account.
=> misc: remove model used for external provisioner reqs

gateway/src/proxy.rs
For HTTP clients that were sending the full URL as the request target, e.g. [rama](https://github.com/plabayo/rama), the location header had the full URL appended to the header, rather than just the path.
Tested with `curl --request-target <full url>`, rama and telnet on staging.
=> fix(gateway): use req.path in bouncer

Makefile.toml, cargo-shuttle/src/lib.rs, common/src/models/resource.rs, service/src/builder.rs
Allows setting a custom set of feature flags on Shuttle via the 'shuttle' feature flag.
https://github.com/shuttle-hq/shuttle-examples/pull/171
=> feat: use 'shuttle' feature flag if it exists

backends/src/resource.rs, cargo-shuttle/src/lib.rs, common/Cargo.toml, common/src/resource.rs, deployer/src/deployment/run.rs
This moves resourcestate to common, since the runner will also need it.
Tested on my stack.
=> feat: provisioner idempotence changes

Cargo.lock, gateway/Cargo.toml, gateway/src/proxy.rs
curl with a url encoded path gives proper response instead of panic
=> fix(gateway): drop tower-sanitize-path

resources/aws-rds/Cargo.toml, resources/aws-rds/src/lib.rs
The following commits bring support to output `diesel-async` resources from all of the following databases:
- `#[shuttle_aws_rds::Postgres]`
- `#[shuttle_aws_rds::MariaDB]` 
- `#[shuttle_aws_rds::MySql]`
closely following the changes made in https://github.com/shuttle-hq/shuttle/pull/1664
It closes: https://github.com/shuttle-hq/shuttle/issues/1692
I have a local project for PoC which I can upload to github if needed.
=> feat: Add `diesel-async` support for `shuttle-aws-rds`

backends/src/client/gateway.rs, backends/src/lib.rs, backends/src/test_utils/gateway.rs, cargo-shuttle/src/lib.rs, gateway/src/auth.rs, resource-recorder/src/lib.rs
- allow checking project endpoint with the project id. this simplifies and corrects the check in r-r for project permission.
tested on staging
=> fix(resource-recorder): check project permission by project id

common/src/deployment.rs
Fixes typo in `cargo deploy` successful deployment message (in Terminal). Closes #1854
=> fix: ⌨️ fix typo

common/src/deployment.rs
Revert #1855 and add a comment about why we are keeping the typo around.
=> feat(deployer): revert typo fix

backends/src/client/permit.rs
Instrument permit client calls, and add a common field to group them.
=> feat: instrument permit calls

install.sh
Added flag for install.sh, such that for Arch Linux, it does not try to ask for confirmation.
I modified the Dockerfile I used for replicating the bug, such that it runs install.sh instead of downloading the script from the Shuttle website. It seems to work fine
=> fix: failing install on Arch Linux (#1810)

.circleci/config.yml, DEVELOPING.md, docker-compose.yml, extras/otel/otel-collector-config.yaml, logger/src/dal.rs
=> chore: disable honeycomb export, remove vars

cargo-shuttle/src/lib.rs
The teams feature is disabled on the beta platform, so we get a 404 if we try to call that endpoint.
Tested in beta dev environment.
=> fix: remove teams call for beta project list

Cargo.lock, cargo-shuttle/src/lib.rs, runtime/Cargo.toml, runtime/src/beta.rs, runtime/src/lib.rs, runtime/src/start.rs
=> feat(runtime): improve beta tracing

cargo-shuttle/src/args.rs, cargo-shuttle/src/lib.rs, common/src/models/resource.rs
- deploying to non-existent project name creates it
- local run requires `--name` or to link a project
- don't ask to select `[CREATE NEW]` if user has no projects
- minor refactors
-
=> fix(cargo-shuttle): beta: create missing project on deploy, fix local run, better project link dialogue

cargo-shuttle/src/config.rs, cargo-shuttle/src/lib.rs
Renames...
- assets -> deploy.include
- build_assets -> build.assets
...with fallback to previous names. (no breaking change)
A fully utilized Shuttle.toml for beta would be
```toml
[deploy]
include = ["assets/*"]
deny_dirty = true
[build]
assets = ["assets/*"]
```
=> feat(cargo-shuttle): Shuttle.toml new key names

cargo-shuttle/src/config.rs, cargo-shuttle/src/lib.rs
- Don't prompt for project linking on local run. 
- Refactor init to prompt the .dev client user if they want to create the project
Tested locally and against the .dev api.
=> fix: don't attempt project linking on local run, create project and link on beta init

Cargo.lock, codegen/Cargo.toml, codegen/src/lib.rs, codegen/src/shuttle_main.rs
closes #1873 
Added `proc-macro-error-2` and removed `proc-macro-error` dependency.
=> added proc-macro-error2 dependency

.circleci/config.yml, Makefile, common/Cargo.toml
Five of our resource crates now have MSRV of 1.81 due to an update of the cargo `home` crate msrv in a patch release, which causes failures in our CI. I'm bumping our general MSRV since 1.81 was released in early September, with 1.83 being the current, and 1.84 being released on the 9th of January.
=> feat: bump common msrv to 1.81, our images to 1.83

resources/turso/Cargo.toml
Bumped the `libsql` dependency in the Turso resource to version 0.6.0.
Ran the unit tests associated with the Turso crate.
=> improvement: update the Turso resource to use libsql 0.6.0

Cargo.lock, gateway/Cargo.toml, gateway/src/api/latest.rs, gateway/src/main.rs, gateway/src/service.rs
As of the 1st of January 2025, making new deployments on the shuttle.rs platform has been deprecated, and users will be directed to upgrade to the shuttle.dev platform.
Will test in staging.
=> feat: deprecate new deployments

cargo-shuttle/src/lib.rs, runtime/src/start.rs
Fixes RUST_LOG override in `shuttle run` reported in https://discord.com/channels/803236282088161321/1318703796007735306
Local run with `RUST_LOG=trace` now shows `trace!()` logs from the user code.
=> fix(cargo-shuttle): don't override user provided RUST_LOG on local run

admin/src/args.rs, admin/src/client.rs, admin/src/lib.rs, api-client/src/lib.rs, cargo-shuttle/src/lib.rs, runtime/src/rt.rs
Admin CLI requires longer timeout for certain operations.
=> feat: make api-client timeout configurable, increase in admin cli

Cargo.lock, auth/Cargo.toml, auth/src/lib.rs, auth/src/user.rs, backends/Cargo.toml, backends/src/key.rs, backends/src/lib.rs, common/Cargo.toml, common/src/lib.rs, common/src/models/user.rs, gateway/Cargo.toml, gateway/src/api/auth_layer.rs
- debloats common
- prevents mistake of binding an AccountTier and db not finding the type
=> chore: move ApiKey type to backends, remove AccountTier sqlx::Type

services/shuttle-salvo/Cargo.toml
updated examples on develop branch
=> chore(shuttle-salvo): bump salvo version

services/shuttle-actix-web/src/lib.rs, services/shuttle-axum/src/lib.rs, services/shuttle-poem/src/lib.rs, services/shuttle-rocket/src/lib.rs, services/shuttle-salvo/src/lib.rs, services/shuttle-serenity/src/lib.rs, services/shuttle-thruster/src/lib.rs, services/shuttle-tide/src/lib.rs, services/shuttle-tower/src/lib.rs, services/shuttle-warp/src/lib.rs
PR re-exports the top-level crate of each "wrapped" / supported web framework. This frees Shuttle users from having to pin a version of their preferred framework *and* a version of the framework's Shuttle wrapper.
This change is purely a quality-of-life change, and does not require users to change anything about their existing code or dependency manifests. It simply allows this ...:
```rust
use axum::{routing::get, Router};
async fn hello_world() -> &'static str {
"Hello, world!"
}
#[shuttle_runtime::main]
async fn main() -> shuttle_axum::ShuttleAxum {
let router = Router::new().route("/", get(hello_world));
Ok(router.into())
}
```
... to become this:
```rust
use shuttle_axum::{ShuttleAxum, axum::{routing::get, Router}};
async fn hello_world() -> &'static str {
"Hello, world!"
} …
```
=> feat: re-export supported framework crates

Cargo.lock, Cargo.toml, codegen/src/shuttle_main.rs, common/src/resource.rs, runtime/Cargo.toml, runtime/src/alpha.rs, runtime/src/lib.rs, runtime/src/rt.rs, runtime/src/start.rs, runtime/src/trace.rs
PR expands on the existing `tracing` setup/configuration feature in `shuttle-runtime`, adding an enhanced subscriber that includes an [OpenTelemetry](https://crates.io/crates/tracing-opentelemetry) layer and enables exporting all telemetry data (traces, metrics, and logs) generated by a Shuttle project to any compatible OTLP collector.
The new behavior is gated behind a new `setup-telemetry` feature flag.
> [!IMPORTANT]
> PR changes the default `RUST_LOG` configuration from `info` to `info,{crate_name}=debug`
=> feat: user project telemetry

runtime/Cargo.toml, runtime/src/telemetry.rs
PR removes the need to manually keep pinned version of `opentelemetry-sdk` in sync with static string value in `runtime/src/telemetry.rs`
> **Credit:** [lalitb](https://github.com/lalitb)'s suggestion [here](https://github.com/open-telemetry/opentelemetry-rust/pull/2504#discussion_r1936042877)
=> chore: use `TelemetryResourceDetector` for telemetry sdk values when creating default resource

Cargo.lock, Cargo.toml, common/Cargo.toml, common/src/models/deployment.rs, common/src/models/log.rs, common/src/models/telemetry.rs
PR adds a `Debug` variant of the `TelemetrySinkConfig` enum for internal use in developing, testing, and debugging generated configurations for user telemetry data export.
=> feat: telemetry debugging variant

resources/shared-db/Cargo.toml
Upgrades `shuttle-shared-db`'s dependency on `diesel-async` from v0.4.1 to v0.5.2.
Clippy gives no warnings, compilation is successful.
=> build(shared-db): upgrade diesel-async to v0.5.2

.gitmodules, resources/openai/Cargo.toml
Update async-openai to 0.28.0
The async-openai upstream version has more Voices available in the text to speech api.
https://platform.openai.com/docs/guides/text-to-speech
Locally on my branch.
=> Update async-openai to 0.28.0

admin/src/args.rs, cargo-shuttle/src/args.rs, cargo-shuttle/src/config.rs, cargo-shuttle/src/lib.rs, common/src/constants.rs, common/src/models/auth.rs
Forward compatible change to move console url logic to the api
Also renamed a constant
=> feat(cargo-shuttle): use api-provided console url on login if available

admin/src/args.rs, admin/src/client.rs, admin/src/lib.rs, common/Cargo.toml, common/src/models/project.rs, common/types.ts
Remove the update compute_tier functionality, replace with a freeform runtime configuration admin functionality.
=> feat: Add client capability to set replicas

api-client/Cargo.toml, cargo-shuttle/src/args.rs, cargo-shuttle/src/init.rs, cargo-shuttle/src/lib.rs, cargo-shuttle/src/provisioner_server.rs, common/Cargo.toml, common/src/models/deployment.rs, common/src/models/log.rs, common/src/models/project.rs, common/src/models/resource.rs, common/src/models/team.rs, common/src/models/telemetry.rs, common/src/models/user.rs, common/src/secrets.rs, common/types.ts, service/src/lib.rs
Philosophy: Add Unknown variants to enums that clients parse (responses), but not to enums that only the backend parses (requests).
- Adds the Unknown variant in a feature flag that only the api-client lib (and thus cargo-shuttle) enables, as it is only those clients that we want to parse future variants.
- Breaking: Removes unnecessary Unknown variant and Default impl on BuildArgs
- Random docs & clippy fixes, nits
=> feat(common): add forward-compatible variants on user facing enums

cargo-shuttle/src/args.rs, cargo-shuttle/src/bin/cargo-shuttle.rs, cargo-shuttle/src/bin/shuttle.rs, cargo-shuttle/src/config.rs, cargo-shuttle/src/lib.rs, cargo-shuttle/tests/integration/init.rs, cargo-shuttle/tests/integration/main.rs, cargo-shuttle/tests/integration/run.rs, common/src/constants.rs, scripts/env-dev.sh, scripts/env-dev2.sh, scripts/env-prod.sh, scripts/env-staging.sh, scripts/set-env.sh
Adds `--shuttle-api-env` / `SHUTTLE_API_ENV` which
- uses a separate config file for that env
- sets the url (SHUTTLE_API) for you (but you can still override it)
This allows you to be logged into multiple envs, and switch between them with this var.
The env scripts were also combined for easy switching.
Tested by logging in to dev2, and the key was placed in `~/.config/shuttle/config.dev2.toml`
```
cargo r --bin shuttle -- --shuttle-api-env dev2 account
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.12s
Running `target/debug/shuttle --shuttle-api-env dev2 account`
INFO: Using non-default global config file: dev2
INFO: Targeting non-default API: https://api.dev2.shuttle.dev
Account info:
User ID: user_01J...
Account tier: basic
cargo r --bin shuttle -- --shuttle-api-env …
```
=> feat(cargo-shuttle): SHUTTLE_API_ENV for separate global configs and automatic api urls

api-client/src/lib.rs, cargo-shuttle/src/args.rs, cargo-shuttle/src/lib.rs
API Endpoint is deprecated.
Used by almost noone and times out due to too many/old logs to fetch in typical use case.
=> chore(cargo-shuttle): remove logs --all-deployments

api-client/src/util.rs, cargo-shuttle/src/lib.rs, common/Cargo.toml, common/src/models/error.rs
- add `new()` for brevity
- allow constructing 400, 401, 403, 404, and 503 with Error or string as the message
- feature gate tracing events and dependency
- emit a `tracing::error!` on `ApiError::internal()` (prev only on `ApiError::internal_safe()`)
- remove complicated context constructors that are unused
=> refa(common): better ApiError constructors & getters, feature gate tracing

Cargo.lock, Cargo.toml, admin/src/client.rs, api-client/Cargo.toml, api-client/src/lib.rs, api-client/src/util.rs, cargo-shuttle/src/lib.rs, runtime/README.md
Switches the error condition (when we should read the body as ApiError) from
`not(200 or 101)` to `4xx or 5xx`.
And makes sure each call with a plain verb uses one of the `to_*` methods to parse and return an error if there is one.
=> feat(api-client): always catch 4xx and 5xx errors regardless of body type

admin/src/client.rs, admin/src/lib.rs, api-client/src/lib.rs, api-client/src/util.rs, cargo-shuttle/src/args.rs, cargo-shuttle/src/lib.rs, cargo-shuttle/tests/integration/main.rs, cargo-shuttle/tests/integration/run.rs, runtime/src/rt.rs
Supersedes #2058 
Adds `--output json` so relevant commands print the json response instead. Not 100% coverage but the important ones have it.
breaking: generate command's `--output` arg renamed to `--output-file` (somewhat matches `deploy --output-archive`)
=> feat(api-client, cargo-shuttle): json output mode

runtime/src/rt.rs, runtime/src/start.rs
Allows services and other internals to `Drop` before the runtime calls `exit()`
=> fix(runtime): drop service before sys exit

.circleci/config.yml, Cargo.lock, Cargo.toml, builder/Cargo.toml, builder/src/lib.rs, builder/templates/cargo-chef.Dockerfile, builder/templates/runtime-base.Dockerfile, builder/templates/rust.Dockerfile.jinja2, builder/tests/rust.Dockerfile, cargo-shuttle/Cargo.toml, cargo-shuttle/src/args.rs, cargo-shuttle/src/builder.rs, cargo-shuttle/src/lib.rs, cargo-shuttle/src/util/mod.rs, cargo-shuttle/tests/integration/builder.rs, cargo-shuttle/tests/integration/run.rs, common/src/models/deployment.rs
Introduces (hidden commands + prints a warnings about being experimental):
- `shuttle build` which builds the runtime natively with `cargo build`, just like `shuttle run` does.
- Supports `--release/-r` and `--bacon` args from `run`
- Supports `--output-archive`
- `shuttle build --docker` which uses the same archiving logic as deploy, and the same dockerfile pipeline as the platform.
- Great for debugging the platform's build system.
- `--tag/-t [tag]` can be used to tag the image (in addition to the default image tag `shuttle-build-[project_name]`) so that it can later be used to `docker push` somewhere. *Enables adding a `--push` arg in the future.*
- Does not support `--bacon`.
- Always builds in release mode (like platform) (can be changed).
- (experimental) `shuttle run --docker` …
=> feat(builder, cargo-shuttle): build and run with docker locally

cargo-shuttle/src/args.rs, cargo-shuttle/src/builder.rs, cargo-shuttle/src/lib.rs, cargo-shuttle/src/util/mod.rs
Unify all `cargo metadata` calls with `--no-deps`, which prevents fetching crates from index, which speeds up all project-related commands significantly.
=> feat(cargo-shuttle): speed up metadata call
